- elide-core/pom.xml
- elide-dbmanager/elide-dbmanager-hibernate3/pom.xml
- elide-dbmanager/elide-dbmanager-inmemorydb/pom.xml
- elide-dbmanager/pom.xml
- elide-integration-tests/pom.xml
- pom.xml
Updating code for [maven central compliance](http://central.sonatype.org/pages/requirements.html)
> Maven Central Compliance

- .travis.yml
- travis/bintray_template.json
- travis/settings.xml
Once we use DPL to publish to bintree we can add an after_publish
step to have bintree sync the new version to Maven Central.
[Bintree API](https://bintray.com/docs/api/#_sync_version_artifacts_to_maven_central)
> Publish through travis

- README.md
> Fix logo url

- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/core/DatabaseManager.java
- elide-dbmanager/elide-dbmanager-hibernate3/src/main/java/com/yahoo/elide/dbmanagers/hibernate3/HibernateManager.java
- elide-dbmanager/elide-dbmanager-hibernate5/src/main/java/com/yahoo/elide/dbmanagers/hibernate5/HibernateManager.java
- elide-dbmanager/elide-dbmanager-hibernate5/src/main/java/com/yahoo/elide/dbmanagers/hibernate5/PersistenceManager.java
- elide-dbmanager/elide-dbmanager-inmemorydb/src/main/java/com/yahoo/elide/dbmanager/InMemory/InMemoryDB.java
Allow DatabaseManager to differentiate between read-only and updating transactions.
> Support read only transactions

- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/CollectionTerminalState.java
- elide-core/src/test/java/com/yahoo/elide/core/EntityDictionaryTest.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-integration-tests/test/java/com/yahoo/elide/endpoints/ResourceIT.java
- elide-integration-tests/test/java/example/AssignedId.java
- elide-integration-tests/test/resources/ResourceIT/assignedId.json
- elide-integration-tests/test/resources/ResourceIT/assignedId.req.json
- elide-integration-tests/test/resources/ResourceIT/assignedIdWithoutId.req.json
- elide-integration-tests/test/resources/ResourceIT/createParentWithoutId.req.json
- Persists provided ID value when ID field is not `@GeneratedValue`
- Allows not providing ID value when ID field is `@GeneratedValue`
> Refactor ID handling

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
Minor performance optimization to push down getting a collection element by ID down to the DataStore.
> Push get by id to predicate

- elide-core/src/main/java/com/yahoo/elide/utils/coerce/CoerceUtil.java
- elide-core/src/main/java/com/yahoo/elide/utils/coerce/converters/FromMapConverter.java
- elide-core/src/test/java/com/yahoo/elide/utils/coerce/CoerceUtilTest.java
- elide-core/src/test/java/com/yahoo/elide/utils/coerce/converters/FromMapConverterTest.java
- elide-core/src/test/java/com/yahoo/elide/utils/coerce/converters/ToEnumConverterTest.java
- elide-integration-tests/src/test/groovy/com/yahoo/elide/tests/UserTypeIT.groovy
- elide-integration-tests/src/test/java-hibernate3/usertypes/JsonType.java
- elide-integration-tests/src/test/java-hibernate5/usertypes/JsonType.java
- elide-integration-tests/src/test/java/example/AddressFragment.java
- elide-integration-tests/src/test/java/example/Person.java
- elide-integration-tests/testngIT.xml
> Add support for usertypes

- elide-core/src/test/java/example/BaseId.java
- elide-core/src/test/java/example/Parent.java
- elide-core/src/test/java/example/Post.java
- elide-datastore/elide-datastore-hibernate3/src/test/java/example/Filtered.java
- elide-datastore/elide-datastore-hibernate5/src/test/java/example/Filtered.java
- elide-integration-tests/src/test/java/example/BaseId.java
- elide-integration-tests/src/test/java/example/Parent.java
- elide-integration-tests/src/test/java/example/Post.java
BaseId parent class should define the ID annotation.
> Correct BaseId as MappedSuperclass

- elide-core/pom.xml
- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/annotation/OnCommit.java
- elide-core/src/main/java/com/yahoo/elide/annotation/OnCreate.java
- elide-core/src/main/java/com/yahoo/elide/annotation/OnDelete.java
- elide-core/src/main/java/com/yahoo/elide/annotation/OnUpdate.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityBinding.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/main/java/com/yahoo/elide/extensions/JsonApiPatch.java
- elide-core/src/test/java/com/yahoo/elide/core/LifeCycleTest.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-core/src/test/java/example/Author.java
- elide-core/src/test/java/example/Book.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java
- elide-datastore/elide-datastore-multiplex/src/main/java/com/yahoo/elide/datastores/multiplex/MultiplexManager.java
- elide-datastore/elide-datastore-multiplex/src/main/java/com/yahoo/elide/datastores/multiplex/MultiplexTransaction.java
- elide-datastore/elide-datastore-multiplex/src/main/java/com/yahoo/elide/datastores/multiplex/MultiplexWriteTransaction.java
- elide-integration-tests/src/test/java/example/Post.java
Implementation of life cycle triggers.
See https://github.com/yahoo/elide-doc/pull/2
> Life cycle triggers

- .travis.yml
- README.md
- elide-core/README.md
- elide-core/src/main/java/com/yahoo/elide/annotation/OnCommit.java
- elide-core/src/main/java/com/yahoo/elide/annotation/OnCreate.java
- elide-core/src/main/java/com/yahoo/elide/annotation/OnDelete.java
- elide-core/src/main/java/com/yahoo/elide/annotation/OnUpdate.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityBinding.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/test/java/example/User.java
- elide-datastore/README.md
- elide-datastore/elide-datastore-hibernate3/README.md
- elide-datastore/elide-datastore-inmemorydb/README.md
- elide-datastore/pom.xml
- elide-example/elide-hibernate3-mysql-example/pom.xml
- elide-integration-tests/README.md
- elide-integration-tests/pom.xml
- pom.xml
- Add test coverage for integration tests
- Versioneye plugin and aggregate result up to parent pom project
- Cleanup: Javadoc, version updates, removed readmes without content
> integration test coverage

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-core/src/test/java/example/FirstClassFields.java
PR addresses issue: https://github.com/yahoo/elide/issues/72
> Added support for field permission precedence.

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
Avoid access exception on create for read restricted relationships
> Forbidden access logging

- README.md
- adding maven central badge that links to the built artifact and displays version.
> maven central badge

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResourceSet.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
Supports interruptible lists by not accessing resource until needed.
> Stream resource list as set of PersistentResource

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/exceptions/InvalidOperationException.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/RecordState.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/RecordTerminalState.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/ResourceIT.java
- elide-integration-tests/src/test/java/example/OneToOneNonRoot.java
- elide-integration-tests/src/test/resources/ResourceIT/oneToOneNonRootUpdatedRelationship.json
- elide-integration-tests/src/test/resources/ResourceIT/oneToOneRootUpdatedRelationship.json
- elide-integration-tests/src/test/resources/ResourceIT/updateOneToOneNonRoot.json
PR addressing https://github.com/yahoo/elide/issues/105
> Fixed posting to to-one relationships.

- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/main/java/com/yahoo/elide/core/SecurityMode.java
- elide-core/src/main/java/com/yahoo/elide/core/exceptions/ForbiddenAccessException.java
- elide-core/src/main/java/com/yahoo/elide/core/exceptions/HttpStatusException.java
- elide-core/src/main/java/com/yahoo/elide/extensions/JsonApiPatch.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/CollectionTerminalState.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/ResourceIT.java
SecurityMode.VERBOSE_ERRORS returns information about the particular
security failure that caused the request to fail.
> Add new SecurityMode

- elide-core/src/main/java/com/yahoo/elide/parsers/state/RelationshipTerminalState.java
Fix a bug we did not conform to JSON API 1.0 (as described by http://jsonapi.org/format/1.0/#crud-updating-relationships)
> Allow sending null data when we are patching a toOne relationship

- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/exceptions/InvalidAttributeException.java
- elide-core/src/main/java/com/yahoo/elide/utils/coerce/converters/ToEnumConverter.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/ResourceIT.java
- elide-integration-tests/src/test/resources/ResourceIT/checkJsonApiPatchWithError.json
Fixed NPE when relationship field is not found.
> Process bad relationship field name

- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
Performance enhancement for EntitiyDictionary.findMethod
> Use Class.getMethod instead of Class.getMethods

- elide-core/src/main/java/com/yahoo/elide/core/EntityBinding.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
Bind getAccessibleObject map at startup.
> Speed up getAccessibleObject

- elide-core/src/main/java/com/yahoo/elide/core/EntityBinding.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
> Improve annotation lookup performance

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
Fixing various things in persistent resource.
https://github.com/yahoo/elide/pull/154 **must go first**. In fact, that is the first commit of this PR at time of writing.
> Persistent resource fix

- elide-core/src/main/java/com/yahoo/elide/security/checks/ExtractedChecks.java
- elide-datastore/elide-datastore-hibernate3/src/test/java/com/yahoo/elide/tests/DataStoreIT.java
- elide-datastore/elide-datastore-hibernate5/pom.xml
- elide-datastore/elide-datastore-hibernate5/src/test/java/com/yahoo/elide/tests/DataStoreIT.java
- elide-datastore/elide-datastore-hibernate5/src/test/java/example/Filtered.java
- elide-datastore/testng.xml
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/DataStoreIT.java
The integration test refactoring skipped all DataStore specific tests.
> Run DataStore specific integration tests

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/models/Relationship.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/models/Resource.java
- elide-core/src/main/java/com/yahoo/elide/security/PermissionExecutor.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/DeferredCheckExpression.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/ImmediateCheckExpression.java
- elide-integration-tests/src/test/groovy/com/yahoo/elide/tests/FilterIT.groovy
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/ResourceIT.java
- elide-integration-tests/src/test/resources/ResourceIT/nestedPatchCreate.req.json
- elide-integration-tests/src/test/resources/ResourceIT/nestedPatchCreate.resp.json
Update to properly defer checks and modify elements within a patch extension request.
> Update check deferment for Patch Extension

- elide-annotations/pom.xml
- elide-annotations/src/main/java/com/yahoo/elide/security/checks/UserCheck.java
- elide-core/src/test/java/com/yahoo/elide/jsonapi/JsonApiTest.java
- elide-integration-tests/pom.xml
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/ResourceIT.java
> More minor cleanup

- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
PR in response to: https://github.com/yahoo/elide/issues/170
> Removed redundant and unnecessary calls to save().

- elide-annotations/pom.xml
- elide-annotations/src/main/java/com/yahoo/elide/security/SecurityMode.java
- elide-core/pom.xml
- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/main/java/com/yahoo/elide/extensions/JsonApiPatch.java
- elide-core/src/main/java/com/yahoo/elide/security/PermissionExecutor.java
- elide-core/src/main/java/com/yahoo/elide/security/executors/ActivePermissionExecutor.java
- elide-core/src/main/java/com/yahoo/elide/security/executors/BypassPermissionExecutor.java
- elide-core/src/test/java/com/yahoo/elide/core/PermissionAnnotationTest.java
- elide-datastore/elide-datastore-hibernate/pom.xml
- elide-datastore/elide-datastore-hibernate3/pom.xml
- elide-datastore/elide-datastore-hibernate3/src/test/java/com/yahoo/elide/tests/DataStoreIT.java
- elide-datastore/elide-datastore-hibernate5/pom.xml
- elide-datastore/elide-datastore-inmemorydb/pom.xml
- elide-datastore/elide-datastore-multiplex/pom.xml
- elide-datastore/pom.xml
- elide-example/elide-hibernate3-mysql-example/pom.xml
- elide-example/elide-persistence-mysql-example/pom.xml
- elide-example/pom.xml
- elide-integration-tests/pom.xml
- elide-integration-tests/src/test/java/com/yahoo/elide/initialization/IntegrationTestApplicationResourceConfig.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/ResourceIT.java
- pom.xml
Added support for configurable PermissionExecutor.
> Added builder interface for Elide.

- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScopedTransaction.java
- elide-datastore/elide-datastore-hibernate3/pom.xml
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HQLTransaction.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateStore.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate3/src/test/java/com/yahoo/elide/datastores/hibernate3/usertypes/JsonType.java
- elide-datastore/elide-datastore-hibernate3/src/test/java/com/yahoo/elide/tests/DataStoreIT.java
- elide-datastore/pom.xml
- elide-integration-tests/src/test/java/example/Child.java
- elide-integration-tests/src/test/java/example/FunWithPermissions.java
- elide-integration-tests/src/test/java/example/Left.java
- elide-integration-tests/src/test/java/example/NoReadEntity.java
- elide-integration-tests/src/test/java/example/NoShareBiDirectional.java
- elide-integration-tests/src/test/java/example/OneToOneNonRoot.java
- elide-integration-tests/src/test/java/example/OneToOneRoot.java
- elide-integration-tests/src/test/java/example/Right.java
- elide-integration-tests/src/test/java/example/Shareable.java
- elide-integration-tests/src/test/java/example/SpecialRead.java
- elide-integration-tests/src/test/java/example/Unshareable.java
Reduces queries by eager loading all **sparse** and **include** beans.
Allows subclasses to determine if/when to enable the join logic.
> Performance enhancement using JOIN

- elide-core/src/main/java/com/yahoo/elide/security/executors/ActivePermissionExecutor.java
- elide-core/src/test/java/com/yahoo/elide/security/PermissionExecutorTest.java
This data unfortunately gets lost along with type-safety from the new and improved expression logic. Expressions do make overall understanding far clearer, however, so it's a worthwhile sacrifice.
> Updated expression logic to validate Inline-Only checks.

- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateStore.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HQLTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateStore.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java
Added builders to solve issue: https://github.com/yahoo/elide/issues/205
> Added builders for Hibernate stores.

- elide-core/src/main/antlr4/com/yahoo/elide/generated/parsers/Expression.g4
- elide-core/src/main/java/com/yahoo/elide/parsers/expression/PermissionExpressionVisitor.java
- elide-core/src/test/java/com/yahoo/elide/parsers/expression/PermissionExpressionVisitorTest.java
Addresses: https://github.com/yahoo/elide/issues/210
> Fixed visitor to extract expression from paren statements.

- elide-core/src/main/java/com/yahoo/elide/core/exceptions/InvalidValueException.java
- elide-core/src/main/java/com/yahoo/elide/utils/coerce/CoerceUtil.java
Addresses @clayreimann's comment on https://github.com/yahoo/elide/issues/207
> Added verbose message for invalid value conversions.

- elide-annotations/src/main/java/com/yahoo/elide/security/ChangeSpec.java
- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityBinding.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityPermissions.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/main/java/com/yahoo/elide/core/exceptions/ForbiddenAccessException.java
- elide-core/src/main/java/com/yahoo/elide/security/executors/ActivePermissionExecutor.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/ExpressionResult.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/PermissionCondition.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/PermissionExpressionBuilder.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/AndExpression.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/AnyFieldExpression.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/DeferredCheckExpression.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/Expression.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/ImmediateCheckExpression.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/NotExpression.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/OrExpression.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/SpecificFieldExpression.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/UserCheckOnlyExpression.java
- elide-core/src/test/java/com/yahoo/elide/core/EntityDictionaryTest.java
- elide-core/src/test/java/com/yahoo/elide/parsers/expression/PermissionExpressionVisitorTest.java
- elide-core/src/test/java/com/yahoo/elide/security/PermissionExecutorTest.java
- elide-core/src/test/java/com/yahoo/elide/security/permissions/PermissionExpressionBuilderTest.java
Share permission will require more work so getting this tiny change out first.
> Enhance Logging for security failures (minus 'share' which will be separate PR)

- CONTRIBUTING.md
- elide-intellij-codestyle.xml
> Contributing document and Code Style

- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/core/DataStoreTransaction.java
- elide-core/src/test/java/com/yahoo/elide/core/LifeCycleTest.java
- elide-datastore/elide-datastore-multiplex/src/main/java/com/yahoo/elide/datastores/multiplex/MultiplexTransaction.java
- elide-datastore/elide-datastore-multiplex/src/test/java/com/yahoo/elide/datastores/multiplex/MultiplexTransactionTest.java
This method will be invoked prior to commit checks, save, flush, and commit.
> Add a preCommit method to DataStoreTransaction

- elide-core/src/main/java/com/yahoo/elide/core/DataStoreTransaction.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityBinding.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/RelationshipType.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-core/src/test/java/com/yahoo/elide/jsonapi/JsonApiTest.java
- elide-core/src/test/java/com/yahoo/elide/jsonapi/document/processors/IncludedProcessorTest.java
- elide-core/src/test/java/com/yahoo/elide/jsonapi/document/processors/SortProcessorTest.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java
- elide-datastore/elide-datastore-multiplex/src/main/java/com/yahoo/elide/datastores/multiplex/MultiplexTransaction.java
- elide-datastore/elide-datastore-multiplex/src/main/java/com/yahoo/elide/datastores/multiplex/MultiplexWriteTransaction.java
- elide-example/dropwizard-elide-example/src/main/java/com/yahoo/elide/example/application/DropwizardElideApplication.java
- elide-example/dropwizard-elide-example/src/main/java/com/yahoo/elide/example/persistence/Author.java
- elide-example/dropwizard-elide-example/src/main/java/com/yahoo/elide/example/persistence/Book.java
As the first step of changes for bridging multiple data stores. Following proposal at https://github.com/yahoo/elide/blob/dd8751e258f9170eac1ddb1b1385c687b392268c/elide-hbase.md
> Delegate getRelation to DataStoreTransaction

- elide-core/src/main/java/com/yahoo/elide/core/EntityBinding.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
Remove duplicate `accessibleObject` instead using `fieldsToValues`.
> Load fields then method bindings

- elide-core/src/main/java/com/yahoo/elide/Elide.java
> Fix for Windows path

- elide-core/src/main/java/com/yahoo/elide/core/exceptions/HttpStatusException.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/CollectionTerminalState.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/ResourceIT.java
> When user tries to create an object without ID return 400 not 403

- elide-core/src/main/java/com/yahoo/elide/utils/coerce/CoerceUtil.java
- elide-core/src/test/java/com/yahoo/elide/utils/coerce/CoerceUtilTest.java
- elide-integration-tests/src/test/java/example/NoCommitEntity.java
- elide-integration-tests/src/test/java/example/NoCreateEntity.java
- elide-integration-tests/src/test/java/example/NoDeleteEntity.java
- elide-integration-tests/src/test/java/example/NoReadEntity.java
- elide-integration-tests/src/test/java/example/NoUpdateEntity.java
> Fix CoerceUtil Bug

- elide-core/src/main/java/com/yahoo/elide/core/filter/InMemoryFilterOperation.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/Operator.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/Predicate.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialect.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/expression/InMemoryFilterVisitor.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/expression/PredicateExtractionVisitor.java
- elide-core/src/main/java/com/yahoo/elide/utils/coerce/CoerceUtil.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/OperatorTest.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/expression/InMemoryFilterVisitorTest.java
- elide-core/src/test/java/com/yahoo/elide/utils/coerce/CoerceUtilTest.java
- elide-core/src/test/java/example/Author.java
- elide-core/testng.xml
- elide-datastore/elide-datastore-inmemorydb/src/main/java/com/yahoo/elide/datastores/inmemory/InMemoryTransaction.java
> In memory filters and visitors

- elide-core/src/main/java/com/yahoo/elide/core/filter/InMemoryFilterOperation.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/Operator.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/Predicate.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/expression/InMemoryFilterVisitor.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/OperatorTest.java
> Clean up elide predicate

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
> Revert "Don't leak data from relationships"

- elide-core/src/main/java/com/yahoo/elide/core/filter/Predicate.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialect.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialectTest.java
- elide-integration-tests/src/test/groovy/com/yahoo/elide/tests/FilterIT.groovy
Implemented option 2 in [this ticket](https://github.com/jirutka/rsql-parser/issues/21).
> Added filter RSQL '=isnull=' support.

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
`checkRelation` had a number of redundant checks.  This PR should clean them up.
> Removed redundant checks

- elide-datastore/elide-datastore-inmemorydb/src/main/java/com/yahoo/elide/datastores/inmemory/InMemoryTransaction.java
- elide-datastore/elide-datastore-multiplex/src/main/java/com/yahoo/elide/datastores/multiplex/MultiplexTransaction.java
Add missing API calls to MultiplexTransaction and InMemoryTransaction
> Implement new API

- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/core/DataStoreTransaction.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/test/java/com/yahoo/elide/core/LifeCycleTest.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate3/src/test/java/com/yahoo/elide/tests/DataStoreIT.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/PersistenceTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/test/java/com/yahoo/elide/tests/DataStoreIT.java
- elide-datastore/elide-datastore-inmemorydb/src/main/java/com/yahoo/elide/datastores/inmemory/InMemoryTransaction.java
- elide-datastore/elide-datastore-inmemorydb/src/test/java/com/yahoo/elide/datastores/inmemory/InMemoryDataStoreTest.java
- elide-datastore/elide-datastore-multiplex/src/main/java/com/yahoo/elide/datastores/multiplex/MultiplexTransaction.java
- elide-datastore/elide-datastore-multiplex/src/main/java/com/yahoo/elide/datastores/multiplex/MultiplexWriteTransaction.java
- elide-datastore/elide-datastore-multiplex/src/test/java/com/yahoo/elide/datastores/multiplex/MultiplexManagerTest.java
- elide-datastore/elide-datastore-multiplex/src/test/java/com/yahoo/elide/datastores/multiplex/TestDataStore.java
Implement new createObject interface in each datastore.
> elide 3.0 createObject

- elide-core/src/main/java/com/yahoo/elide/core/filter/dialect/ParseException.java
> Updated ParseException constructor to be public for subclassing.

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/CollectionTerminalState.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/RecordTerminalState.java
Properly coerce incoming data to attribute type.  Especially important for Enum and Date types.
> Properly coerce attribute

- elide-core/src/main/java/com/yahoo/elide/core/EntityBinding.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/test/java/com/yahoo/elide/core/EntityDictionaryTest.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-core/src/test/java/example/Invoice.java
- elide-core/src/test/java/example/LineItem.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/ResourceIT.java
- elide-integration-tests/src/test/java/example/Invoice.java
- elide-integration-tests/src/test/java/example/LineItem.java
Fixes #300 
EntityDictionary Unit Tests
Added IT test
Finished unit tests
Added javadoc
> Don't set inverse relationships to null on cascading deletes

- elide-core/src/main/java/com/yahoo/elide/parsers/expression/PermissionToFilterExpressionVisitor.java
- elide-core/src/main/java/com/yahoo/elide/resources/JsonApiEndpoint.java
- elide-core/src/main/java/com/yahoo/elide/security/FilterExpressionCheck.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/PermissionExpressionBuilder.java
- elide-core/src/test/java/com/yahoo/elide/parsers/expression/CanPaginateVisitorTest.java
- elide-core/src/test/java/com/yahoo/elide/parsers/expression/PermissionToFilterExpressionVisitorTest.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java
- elide-integration-tests/src/test/java/example/AnotherFilterExpressionCheckObj.java
- elide-integration-tests/src/test/java/example/FilterExpressionCheckObj.java
Update FilterExpressionCheck to match updated specification.  See https://github.com/yahoo/elide-doc/pull/37
> Refactor FilterExpressionCheck with entityClass

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/Operator.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/Predicate.java
- elide-core/src/main/java/com/yahoo/elide/security/FilterExpressionCheck.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/expression/InMemoryFilterVisitorTest.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/filter/HQLFilterOperation.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/core/filter/HQLFilterOperationTest.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/filter/CriterionFilterOperation.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/filter/CriterionFilterOperation.java
Required for FilterExpressionChecks that process predicates with relationships like
`this.author.book`
> Operator field path evaluation

- elide-core/src/main/java/com/yahoo/elide/core/filter/Predicate.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/filter/HQLFilterOperation.java
Replaced `(true)` and `(false)` with `(1=1)` and `(1=0)`
> HQL requires boolean expression

- elide-core/src/main/java/com/yahoo/elide/security/permissions/PermissionExpressionBuilder.java
Fix bug where field permissions were ignored when entity contained FilterExpression
> Check if Field Permission has in memory filter

- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java
> Change how we fetch data with hibernate to work for fields-only beans

- elide-annotations/src/main/java/com/yahoo/elide/annotation/OnCommit.java
- elide-annotations/src/main/java/com/yahoo/elide/annotation/OnCreate.java
- elide-annotations/src/main/java/com/yahoo/elide/annotation/OnDelete.java
- elide-annotations/src/main/java/com/yahoo/elide/annotation/OnUpdate.java
- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/core/DataStoreTransaction.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/test/java/com/yahoo/elide/core/LifeCycleTest.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-core/src/test/java/example/Book.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateStore.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/test/java/example/Filtered.java
- elide-datastore/elide-datastore-inmemorydb/src/main/java/com/yahoo/elide/datastores/inmemory/InMemoryTransaction.java
- elide-datastore/elide-datastore-multiplex/src/main/java/com/yahoo/elide/datastores/multiplex/MultiplexTransaction.java
- elide-datastore/elide-datastore-multiplex/src/main/java/com/yahoo/elide/datastores/multiplex/MultiplexWriteTransaction.java
This PR added functions above #307 . Please ignore duplicated changes since #307 is not merged yet.
> Elide 3.0 get/setRelation functions

- elide-annotations/src/main/java/com/yahoo/elide/security/checks/prefab/AddToCollectionCheck.java
- elide-annotations/src/main/java/com/yahoo/elide/security/checks/prefab/Collections.java
- elide-core/src/test/java/com/yahoo/elide/core/EntityDictionaryTest.java
Added missing static inner class definition.
> static RemoveOnly

- elide-core/src/main/java/com/yahoo/elide/security/executors/ActivePermissionExecutor.java
Found overhead in trace handling that should be skipped for normal processing.
> Isolate trace handling for performance

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-datastore/elide-datastore-multiplex/src/main/java/com/yahoo/elide/datastores/multiplex/MultiplexManager.java
- elide-datastore/elide-datastore-noop/pom.xml
- elide-datastore/elide-datastore-noop/src/main/java/com/yahoo/elide/datastores/noop/NoopDataStore.java
- elide-datastore/elide-datastore-noop/src/main/java/com/yahoo/elide/datastores/noop/NoopTransaction.java
- elide-datastore/elide-datastore-noop/src/test/java/com/yahoo/elide/beans/NoopBean.java
- elide-datastore/elide-datastore-noop/src/test/java/com/yahoo/elide/datastores/noop/NoopDataStoreTest.java
- elide-datastore/elide-datastore-noop/src/test/java/com/yahoo/elide/datastores/noop/NoopTransactionTest.java
- elide-datastore/pom.xml
Adds a noop store which aids in performing actions that occur out-of-bounds or do not require persisting to any sort of datastore (in-memory, on disk, or otherwise).
> Noop store

- elide-core/src/main/java/com/yahoo/elide/security/permissions/PermissionExpressionBuilder.java
PermissionExpressionBuilder included all fields in ANY even when sparse field set exists.
> Restrict ANY permission to sparse fields

- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java
- elide-datastore/elide-datastore-multiplex/src/main/java/com/yahoo/elide/datastores/multiplex/MultiplexTransaction.java
- elide-integration-tests/src/test/java/example/Child.java
Process mutiplexed RequestScopedTransactions
> Handle RequestScopedTransaction transactions

- elide-annotations/src/main/java/com/yahoo/elide/annotation/OnReadPostCommit.java
- elide-annotations/src/main/java/com/yahoo/elide/annotation/OnReadPreCommit.java
- elide-annotations/src/main/java/com/yahoo/elide/annotation/OnReadPreSecurity.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityBinding.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/test/java/com/yahoo/elide/core/LifeCycleTest.java
- elide-core/src/test/java/example/Book.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateTransaction.java
Addresses: https://github.com/yahoo/elide/issues/363
> On read hook

- README.md
Addresses: https://github.com/yahoo/elide/issues/193
> Add tutorial links.

- elide-core/src/main/java/com/yahoo/elide/extensions/JsonApiPatch.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/RecordTerminalState.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/ResourceIT.java
- elide-integration-tests/src/test/resources/ResourceIT/patchExtBadId.json
- elide-integration-tests/src/test/resources/ResourceIT/patchExtBadId.req.json
Addresses: https://github.com/yahoo/elide/issues/373
> Surface ForbiddenAccessException for DELETE.

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/FilterPredicate.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/Operator.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/filter/HQLFilterOperation.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/filter/CriterionFilterOperation.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/filter/CriterionFilterOperation.java
- elide-integration-tests/src/test/groovy/com/yahoo/elide/tests/FilterIT.groovy
- elide-integration-tests/src/test/java/example/Book.java
Added case insensitive operators: `prefixi`, `postfixi`, and `infixi`.
> Case insensitive operators

- elide-core/src/main/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialect.java
- elide-integration-tests/src/test/groovy/com/yahoo/elide/tests/FilterIT.groovy
This PR fix the value coercion problem for nested types in RSQL.
> Fix RSQL value coercion.

- elide-datastore/elide-datastore-multiplex/pom.xml
Adds `<scope>test</scope>` to hibernate5 dependency.
> Hibernate5 to scope tests for multiplex store.

- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/ScrollableIterator.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/ScrollableIterator.java
Should fix issue #407 
Would like a review from @wcekan before merging.
> No longer call unsafe methods in ScrollableIterator

- README.md
- elide-contrib/elide-swagger/src/main/java/com/yahoo/elide/contrib/swagger/SwaggerBuilder.java
- elide-contrib/elide-swagger/src/main/java/com/yahoo/elide/contrib/swagger/property/Data.java
- elide-contrib/elide-swagger/src/main/java/com/yahoo/elide/contrib/swagger/property/Datum.java
- elide-contrib/elide-swagger/src/test/java/com/yahoo/elide/contrib/swagger/SwaggerBuilderTest.java
- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/BaseState.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/CollectionTerminalState.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/RecordTerminalState.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/RelationshipTerminalState.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/ScrollableIterator.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/ScrollableIterator.java
- elide-datastore/testng-assignedIdLong.xml
- elide-integration-tests/src/test/java/com/yahoo/elide/assignedIdLongTests/AssignedIdLongIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/initialization/AssignedIdLongIntegrationTestApplicationResourceConfig.java
- elide-integration-tests/src/test/java/com/yahoo/elide/initialization/AssignedIdLongStandardTestBinder.java
- elide-integration-tests/src/test/resources/AssignedIdLongIT/createAssignedIdLongEntity.req.json
- elide-integration-tests/src/test/resources/AssignedIdLongIT/createAssignedIdLongEntity.resp.json
- elide-integration-tests/src/test/resources/AssignedIdLongIT/updateAssignedIdLong.req.json
- elide-integration-tests/src/test/resources/AssignedIdLongIT/updateAssignedIdLong.resp.json
- elide-integration-tests/src/test/resources/AuditIT/updateAuditEntityLineageDup.json
Merges current master into elide-3.0-wip branch.
> Merge elide3.0

- elide-contrib/dropwizard-elide/src/main/java/com/yahoo/elide/contrib/dropwizard/elide/ElideBundle.java
- elide-contrib/dropwizard-elide/src/main/java/com/yahoo/elide/contrib/dropwizard/elide/ElideConfiguration.java
- elide-core/src/main/java/com/yahoo/elide/resources/DefaultOpaqueUserFunction.java
- elide-core/src/main/java/com/yahoo/elide/resources/JsonApiEndpoint.java
- elide-example/elide-blog-example/src/main/java/com/yahoo/elide/example/ElideResourceConfig.java
- elide-example/elide-hibernate3-mysql-example/src/main/java/com/yahoo/elide/example/hibernate3/ElideResourceConfig.java
- elide-integration-tests/src/test/java/com/yahoo/elide/initialization/AssignedIdLongStandardTestBinder.java
- elide-integration-tests/src/test/java/com/yahoo/elide/initialization/StandardTestBinder.java
This is in preparation for GraphQL support (we'll want to share this between our endpoints)
> Promote OpaqueUserFunction to be a top-level interface

- README-zh.md
- README.md
I can spread Elide into Chinese OSS community once Chinese translation is ready
> Translate top level README to Chinese

- elide-core/src/main/java/com/yahoo/elide/utils/coerce/CoerceUtil.java
- elide-core/src/main/java/com/yahoo/elide/utils/coerce/converters/ToUUIDConverter.java
- elide-core/src/test/java/com/yahoo/elide/utils/coerce/CoerceUtilTest.java
> [Issue 459] Add String to UUID conversion

- elide-core/src/main/java/com/yahoo/elide/Elide.java
PR https://github.com/yahoo/elide/pull/425 lost the proper `isVerbose` setting if an exception is thrown.
This should reinstate the proper flow.
> Collect isVerbose from handler before throwing exception

- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/extensions/JsonApiPatch.java
Catch any ForbiddenAccess exceptions thrown by visitor and properly handle them.
> Properly handle exceptions in handler

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
Found a cast error due to updating the inverse relationship with the wrong type.
> Use inverse relation type when updating.

- changelog.md
- elide-contrib/elide-swagger/src/test/java/com/yahoo/elide/contrib/swagger/SwaggerBuilderTest.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityBinding.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/datastore/inmemory/InMemoryTransaction.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialect.java
- elide-datastore/elide-datastore-inmemorydb/src/test/java/com/yahoo/elide/datastores/inmemory/InMemoryDataStoreTest.java
- elide-datastore/elide-datastore-multiplex/src/test/java/com/yahoo/elide/datastores/multiplex/MultiplexManagerTest.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/ResourceIT.java
Cleanup code style to be more readable.
> Cleanup equals

- elide-core/src/main/java/com/yahoo/elide/graphql/Entity.java
- elide-core/src/main/java/com/yahoo/elide/graphql/PersistentResourceFetcher.java
Change flow from this - 
```
if(id not present) {
attachId();
}
if(fetchObject() == null) {
createObject();
} else {
updateObject();
}
```
to this - 
```
if(id not present) {
createObject();
} else {
if(fetchObject() == null) {
createObject();
} 
}
updateObject();
```
> Fix id with upsert

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
- elide-core/src/test/java/com/yahoo/elide/core/EntityDictionaryTest.java
* Fixes Issue #521
* Make sure bindEntity is idempotent
Make sure bindEntity is idempotent
Inspection rework
> Fixes Issue #521 (#524)

- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/main/java/com/yahoo/elide/graphql/PersistentResourceFetcher.java
- elide-core/src/test/java/com/yahoo/elide/graphql/FetcherFetchTest.java
- elide-core/src/test/java/com/yahoo/elide/graphql/PersistentResourceFetcherTest.java
Support for filtering in GraphQL. Builds off of: https://github.com/yahoo/elide/pull/527
> GraphQL Filtering

- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/RootCollectionFetchQueryBuilderTest.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/RootCollectionPageTotalsQueryBuilderTest.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/SubCollectionFetchQueryBuilderTest.java
Added test to exercise the proxy handling.
> Unit test with bean proxy

- changelog.md
- elide-core/pom.xml
- elide-standalone/README.md
- elide-standalone/pom.xml
- elide-standalone/settings/elide-settings.properties
- elide-standalone/settings/hibernate.cfg.xml
- elide-standalone/src/main/java/com/yahoo/elide/standalone/Main.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideResourceConfig.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/RuntimeSettings.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/datastore/InjectionAwareHibernateStore.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/interfaces/CheckMappingsProvider.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/interfaces/ElideSettingsProvider.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/interfaces/UserExtractionFunctionProvider.java
- pom.xml
MVP of Elide standalone application.
> Add standalone application.

- .travis.yml
- changelog.md
- elide-annotations/src/main/java/com/yahoo/elide/security/checks/prefab/Common.java
- elide-core/src/main/java/com/yahoo/elide/core/Path.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/FilterPredicate.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/Operator.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialect.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/expression/ExpressionScopingVisitor.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/OperatorTest.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialectTest.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/expression/ExpressionScopingVisitorTest.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/expression/InMemoryFilterVisitorTest.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/filter/HQLFilterOperation.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/AbstractHQLQueryBuilder.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/RootCollectionFetchQueryBuilder.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/SubCollectionPageTotalsQueryBuilder.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/core/filter/HQLFilterOperationTest.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/AbstractHQLQueryBuilderTest.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/RootCollectionFetchQueryBuilderTest.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/RootCollectionPageTotalsQueryBuilderTest.java
- elide-integration-tests/src/test/groovy/com/yahoo/elide/tests/FilterIT.groovy
- elide-integration-tests/src/test/java/example/Child.java
RSQL == and =out= will now behave in a case insensitive manner.
Closes #387
> Allow case insensitive comparisons.

- elide-core/src/main/java/com/yahoo/elide/graphql/GraphQLConversionUtils.java
- elide-core/src/test/java/com/yahoo/elide/books/Author.java
- elide-core/src/test/java/com/yahoo/elide/graphql/FetcherFetchTest.java
- elide-core/src/test/java/com/yahoo/elide/graphql/FetcherUpsertTest.java
- elide-core/src/test/resources/graphql/requests/fetch/computedAttributes.graphql
- elide-core/src/test/resources/graphql/requests/upsert/setComputedAttribute.graphql
- elide-core/src/test/resources/graphql/responses/fetch/computedAttributes.json
- elide-core/src/test/resources/graphql/responses/upsert/setComputedAttribute.json
Additional tests for GraphQL around computed attributes.
Requires: https://github.com/yahoo/elide/pull/549
> Test computed attributes in GraphQL

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/core/EntityPermissions.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/test/java/com/yahoo/elide/core/LifeCycleTest.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
This reverts commit 483c27a10ec39dc6d925112996bd4b94cce9fb44, reversing
changes made to 438058cfc2a2e4ec71150e13ddcdadd46a3de960.
> Revert "Merge pull request #564 from yahoo/HandleForbiddenInclude"

- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/test/java/com/yahoo/elide/core/LifeCycleTest.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLEndpoint.java
- elide-graphql/src/test/groovy/com/yahoo/elide/graphql/GraphQLEndointTest.groovy
- elide-graphql/src/test/java/graphqlEndpointTestModels/Author.java
- elide-graphql/src/test/java/graphqlEndpointTestModels/Book.java
- elide-graphql/src/test/java/graphqlEndpointTestModels/DisallowShare.java
- elide-graphql/src/test/java/graphqlEndpointTestModels/security/CommitChecks.java
- elide-graphql/src/test/java/graphqlEndpointTestModels/security/UserChecks.java
- elide-integration-tests/src/test/java/example/Unshareable.java
> Add GraphQL initial endpoint test.

- .travis.yml
- changelog.md
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/exceptions/InternalServerErrorException.java
> Fix jersey dependency 2

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLEndpoint.java
Elide 4 version of: https://github.com/yahoo/elide/pull/586
> Log exceptions elide4

- changelog.md
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/Environment.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLEndpoint.java
- elide-integration-tests/src/test/groovy/com/yahoo/elide/tests/GraphQLIT.groovy
This PR adds support for GraphQL query batching and additional tests.
Addresses: https://github.com/yahoo/elide/issues/603
> Add support for GraphQL query batching

- changelog.md
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLEndpoint.java
Fixed the `Transaction not closed` error on aborted response.
> Handle Transaction close correctly on aborted response.

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- Log runtime exception as error
> Log runtime exception as error

- changelog.md
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java
Fixes attempt to use entity name like `example.Author_$$_jvst1d1_42`
> Resolve hibernate proxy class

- README-zh.md
The "Tutorials" section doesn't have corresponding websites for the same contents. I'll translate each of them into Chinese tutorials later.
> Update README Chinese translation

- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/AbstractHibernateStore.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateEntityManagerStore.java
Fix #677 Nullpointer when using HibernateEntityManagerStore
> Fix #677 Nullpointer when using HibernateEntityManagerStore

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/core/EntityBinding.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/test/java/com/yahoo/elide/core/LifeCycleTest.java
- elide-core/src/test/java/example/Publisher.java
> Issue730 & Issue729

- changelog.md
- pom.xml
> Revert "Upgrade puppy crawl tools"

- changelog.md
- elide-example/elide-blog-example-resteasy/pom.xml
- elide-example/elide-blog-example/pom.xml
- elide-example/elide-hibernate3-mysql-example/pom.xml
- elide-standalone/pom.xml
- pom.xml
> Bump mysql-connector-java to 8.0 to support current MySQL version

- .travis.yml
- elide-core/README.md
- elide-graphql/README.md
- pom.xml
Apparently, versioneye died a long time ago. https://blog.versioneye.com/2017/10/19/versioneye-sunset-process/
> Remove versioneye

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
> Cache all calls to getEntityBinding

- elide-standalone/pom.xml
- pom.xml
> Upgraded to latest version of Jetty

- changelog.md
Add change log for https://github.com/yahoo/elide/pull/809
> Add change log for PR#809

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialect.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialectTest.java
Resolves https://github.com/yahoo/elide/issues/800
> Support RSQL INFIX, POSTFIX, and PREFIX filters on number types.

- elide-contrib/elide-swagger/pom.xml
- elide-datastore/elide-datastore-hibernate3/pom.xml
- elide-datastore/elide-datastore-hibernate5/pom.xml
- elide-datastore/elide-datastore-jpa/pom.xml
- elide-datastore/elide-datastore-multiplex/pom.xml
- elide-example/elide-blog-example/pom.xml
- elide-graphql/pom.xml
- elide-integration-tests/pom.xml
- elide-standalone/pom.xml
- pom.xml
> Jersey.version

- changelog.md
- elide-datastore/elide-datastore-hibernate3/pom.xml
- elide-datastore/elide-datastore-hibernate5/pom.xml
- elide-example/elide-blog-example-resteasy/pom.xml
- elide-example/elide-blog-example/pom.xml
- elide-example/elide-hibernate3-mysql-example/pom.xml
- elide-example/pom.xml
- elide-standalone/pom.xml
- pom.xml
Runs vulnerability checks during build
Catch vulnerability problems sooner 
Building 
> run vulnerability check

- pom.xml
> Fix maven release build

- pom.xml
> Fixing jackson databind security issues

- changelog.md
- pom.xml
> Version.jackson 2.10.0.pr1

- elide-integration-tests/src/test/java/com/yahoo/elide/tests/AccessIT.java
- Update access integration test to use new framework and Junit 5
> Elide-Testing Refactor access integration test

- elide-core/src/main/java/com/yahoo/elide/core/DataStoreTransaction.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResourceSet.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/EntityProjectionMaker.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/document/processors/IncludedProcessor.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/models/ResourceIdentifier.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/CollectionTerminalState.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/RecordState.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/StartState.java
- elide-core/src/main/java/com/yahoo/elide/request/Attribute.java
- elide-core/src/main/java/com/yahoo/elide/request/EntityProjection.java
- elide-core/src/main/java/com/yahoo/elide/request/Relationship.java
- elide-core/src/test/java/com/yahoo/elide/core/LifeCycleTest.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-core/src/test/java/com/yahoo/elide/core/TestRequestScope.java
- elide-core/src/test/java/com/yahoo/elide/core/UpdateOnCreateTest.java
- elide-core/src/test/java/com/yahoo/elide/jsonapi/EntityProjectionMakerTest.java
- elide-core/src/test/java/com/yahoo/elide/jsonapi/JsonApiTest.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/ResourceIT.java
New design that fixes issues with GraphQL aliases.  This PR just unblocks work.
> Entity projection with aliases

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/engine/SQLEntityHydrator.java
Fixes checkstyle error in build.
> Fixed build

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLQueryEngine.java
Manager transaction manually to avoid autocommit issue.
> Manager transacton manually

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/AggregationDataStoreHelper.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLQueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/schema/SQLSchema.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/AggregationDataStoreTestHarness.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/example/Country.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/example/Player.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/example/PlayerStats.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/example/PlayerStatsView.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/example/SubCountry.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/example/VideoGame.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/filter/visitor/SplitFilterExpressionVisitorTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLQueryEngineTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SubselectTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/schema/SchemaTest.java
- elide-datastore/elide-datastore-aggregation/src/test/resources/META-INF/persistence.xml
- elide-datastore/elide-datastore-aggregation/src/test/resources/create_tables.sql
- elide-datastore/elide-datastore-aggregation/src/test/resources/player_stats.csv
Resolve https://github.com/yahoo/elide/issues/1026
- Update `SQLQueryEngine.extractJoin()` method to check `@Subselect` annotation
- Add test cases, should support all functionalities same as table join
- Update test table names
> ISSUE-1026 Add support for @Subselect

- README.md
Adds awesome badges for Java & GraphQL to readme.
> Added awesome badges for Java & GraphQL

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/AggregationDataStoreTransaction.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/EntityProjectionTranslator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/QueryValidator.java
Refactoring AggregationDatastoreHelper class
> Refactored AggregationDataStoreHelper class

- elide-annotations/src/main/java/com/yahoo/elide/annotation/Exclude.java
- elide-annotations/src/main/java/com/yahoo/elide/annotation/Include.java
> remove @Inherited

- elide-core/pom.xml
- elide-spring/elide-spring-boot-starter/pom.xml
- pom.xml
> Fix dependencies to pass checks

- elide-datastore/elide-datastore-hibernate3/pom.xml
- elide-datastore/elide-datastore-hibernate5/pom.xml
- elide-datastore/elide-datastore-hibernate5/src/test/java/com/yahoo/elide/datastores/hibernate5/HibernateEntityManagerDataStoreHarness.java
- elide-datastore/elide-datastore-jpa/pom.xml
The Entity Manager data store tests were inadvertently dropped in #897 
This returns those tests.
Perform Hibernate Entity Manager testing in addition to native tests.
Build tests
> Hibernate Entity Manager DataStore Harness

- pom.xml
> Revert "Bump version.jackson from 2.10.1 to 2.10.2"

- elide-core/src/main/java/com/yahoo/elide/core/CheckInstantiator.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/models/Relationship.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/RelationshipTerminalState.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-datastore/elide-datastore-search/src/main/java/com/yahoo/elide/datastores/search/SearchDataTransaction.java
Respond to null pointer alerts:
https://lgtm.com/projects/g/yahoo/elide/alerts?mode=list
Stability
Unit tests and product tests
> null access suggestions

- elide-core/src/test/java/com/yahoo/elide/core/LifeCycleTest.java
- elide-core/src/test/resources/logback.xml
During tests send INFO log to Console, TRACE to trace.log
Reduce travis console log during build
Unit testing
> Send INFO to Console, TRACE to trace.log

- checkstyle-style.xml
- pom.xml
Update checkstyle version
Resolves gitHub Issue `checkstyle/checkstyle#7468`
Build
> bump checkstyle to 8.29

- checkstyle-style.xml
- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityBinding.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialect.java
- elide-core/src/main/java/com/yahoo/elide/extensions/JsonApiPatch.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/models/Relationship.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/models/Resource.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/serialization/DataSerializer.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/serialization/SingletonSerializer.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/CollectionTerminalState.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/RelationshipTerminalState.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-core/src/test/java/com/yahoo/elide/core/utils/ClassScannerTest.java
- elide-core/src/test/java/com/yahoo/elide/jsonapi/JsonApiTest.java
- elide-datastore/elide-datastore-inmemorydb/src/test/java/com/yahoo/elide/datastores/inmemory/HashMapDataStoreTest.java
- elide-datastore/elide-datastore-multiplex/src/test/java/com/yahoo/elide/datastores/multiplex/MultiplexManagerTest.java
- elide-datastore/elide-datastore-noop/src/test/java/com/yahoo/elide/datastores/noop/NoopTransactionTest.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/ModelBuilder.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/PersistentResourceFetcher.java
- elide-integration-tests/src/test/java/com/yahoo/elide/initialization/AbstractApiResourceInitializer.java
- elide-integration-tests/src/test/java/com/yahoo/elide/initialization/IntegrationTest.java
- Consolidate on Apache Common Utils.isEmpty
Stability
Unit tests
> Use isEmpty utilitity

- checkstyle-style.xml
- pom.xml
bump checkstyle to 8.29 (#1181)
Stability
Build
> bump checkstyle to 8.29 (#1181)

- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/test/java/com/yahoo/elide/core/EntityDictionaryTest.java
- elide-spring/elide-spring-boot-autoconfigure/pom.xml
- suppressions.xml
> Added setId to EntityDictionary

- elide-spring/elide-spring-boot-autoconfigure/pom.xml
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/controllers/SwaggerController.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/com/yahoo/elide/spring/tests/ControllerTest.java
> Fixes Issue #1211

- elide-core/src/main/java/com/yahoo/elide/core/filter/expression/InMemoryExecutionVerifier.java
Small performance enhancement
Performance
Unit tests
> shortcut the InMemoryExecutionVerifier tests

- elide-core/src/main/java/com/yahoo/elide/extensions/JsonApiPatch.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/ResourceIT.java
- elide-integration-tests/src/test/resources/ResourceIT/invalidPatchMissingId.req.json
> Better errors for missing IDs in Patch Extension Request.

- elide-core/src/main/java/com/yahoo/elide/extensions/JsonApiPatch.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/ResourceIT.java
- elide-integration-tests/src/test/resources/ResourceIT/invalidPatchMissingId.req.json
Merge #1278 into Elide-5.x
Test coverage
Unit testing
> Better errors for missing IDs in Patch Extension Request. (#1278)

- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/core/HttpStatus.java
- elide-core/src/main/java/com/yahoo/elide/core/exceptions/TimeoutException.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/QueryRunner.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/controllers/GraphqlController.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/controllers/JsonApiController.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/controllers/SwaggerController.java
Migrates Spring controllers to use async for request timeouts.
> Migrated spring controllers to use async

- elide-datastore/elide-datastore-jpa/src/main/java/com/yahoo/elide/datastores/jpa/JpaDataStore.java
JPA Store only provides a mechanism to make a read/write transaction.   This PR adds a constructor to also create a separate read only transaction for API reads.
Read only transactions have a significant performance boost over read/write.
> Adding read only transaction support to JPA store

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/annotation/Meta.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/enums/FunctionArgumentType.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Column.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/FunctionArgument.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Metric.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/MetricFunction.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLMetric.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metric/SQLMetricFunction.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metric/functions/SqlAvg.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metric/functions/SqlMax.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metric/functions/SqlMin.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metric/functions/SqlSum.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/example/PlayerStats.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/example/PlayerStatsWithView.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/AggregationDataStoreIntegrationTest.java
i) Remove LongName
ii) Remove subType from FunctionArgument
iii) Add expression and functionArgumentType to FunctionArgument
Enhancements request for aggregation store. 
Existing Tests pass
> Aggregation Store - Function Argument Enhancements and LongName removal

- suppressions.xml
> Fixing Invalid CVE Build Error (The wrong package is being flagged)

- elide-core/src/main/java/com/yahoo/elide/core/TransactionRegistry.java
Resolves #1292 (if appropriate)
> TANDS-19093-transactionRegistry-interface

- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
Resolves #1292 (if appropriate)
> CARBON-161 add requestId to RequestScope

- elide-contrib/elide-swagger/src/main/java/com/yahoo/elide/contrib/swagger/SwaggerBuilder.java
- elide-contrib/elide-swagger/src/test/java/com/yahoo/elide/contrib/swagger/SwaggerBuilderTest.java
- elide-contrib/elide-swagger/src/test/java/com/yahoo/elide/contrib/swagger/SwaggerResourceConfig.java
- elide-example/elide-blog-example/src/main/java/com/yahoo/elide/example/CommonElideSettings.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java
- elide-standalone/src/test/java/com/yahoo/elide/standalone/ElideStandaloneTest.java
> Disabling Legacy Filter Dialect in Swagger Documentation

- elide-example/elide-hibernate3-mysql-example/pom.xml
> Bumping Hibernate Validator Version

- elide-contrib/elide-dynamic-config-helpers/pom.xml
Update: Remove slf4j-simple dependency
Breaks spring boot applications
At application level
n/a
> Update: Remove slf4j-simple dependency

- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java
- elide-datastore/elide-datastore-jpa/src/main/java/com/yahoo/elide/datastores/jpa/transaction/AbstractJpaTransaction.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/PaginateIT.java
> Only issue page total query if data load returns records

- elide-datastore/elide-datastore-aggregation/pom.xml
- elide-datastore/elide-datastore-search/src/test/resources/META-INF/persistence.xml
- elide-standalone/pom.xml
- elide-standalone/src/test/java/example/ElideStandaloneDisableAggStoreTest.java
- elide-standalone/src/test/java/example/ElideStandaloneMetadataStoreMissingTest.java
- elide-standalone/src/test/java/example/ElideStandaloneTest.java
- pom.xml
> Revert "H2 5.x"

- elide-core/src/test/java/com/yahoo/elide/audit/TestAuditLogger.java
Fix build due to random test ordering.
Starts TestAuditLogger off clean.
Unit testing and local building.
> Clear any context from TestAuditLogger

- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
Potential NPE
Code quality
Unit testing
> Fix dictionary NPE

- elide-core/src/main/java/com/yahoo/elide/core/datastore/inmemory/HashMapDataStore.java
- elide-core/src/main/java/com/yahoo/elide/core/datastore/inmemory/InMemoryDataStore.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/FilterPredicate.java
- elide-core/src/main/java/com/yahoo/elide/parsers/JsonApiParser.java
- elide-core/src/test/java/com/yahoo/elide/core/datastore/inmemory/InMemoryStoreTransactionTest.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/expression/ExpressionScopingVisitorTest.java
- elide-core/src/test/java/com/yahoo/elide/parsers/JsonApiParserTest.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate3/src/test/java/com/yahoo/elide/tests/DataStoreIT.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/test/java/com/yahoo/elide/tests/DataStoreIT.java
- elide-datastore/elide-datastore-jpa/src/main/java/com/yahoo/elide/datastores/jpa/transaction/AbstractJpaTransaction.java
- elide-datastore/elide-datastore-search/src/test/java/com/yahoo/elide/datastores/search/DataStoreLoadTest.java
- elide-example/elide-blog-example/src/main/java/com/yahoo/elide/example/CommonElideSettings.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/UserTypeIT.java
- elide-spring/elide-spring-boot-autoconfigure/pom.xml
- elide-spring/elide-spring-boot-starter/pom.xml
- elide-standalone/pom.xml
General cleanup.
* normalizePath regex improvement
* Remove repeated conditional test
* use entrySet
* diamonds for new HashMap
* Unnecessary duplication in swagger pom
Code quality
Unit testing
> Path matcher

- elide-core/src/main/java/com/yahoo/elide/core/datastore/inmemory/HashMapDataStore.java
- elide-core/src/main/java/com/yahoo/elide/core/datastore/inmemory/InMemoryDataStore.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/FilterPredicate.java
- elide-core/src/main/java/com/yahoo/elide/parsers/JsonApiParser.java
- elide-core/src/test/java/com/yahoo/elide/core/datastore/inmemory/InMemoryStoreTransactionTest.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/expression/ExpressionScopingVisitorTest.java
- elide-core/src/test/java/com/yahoo/elide/parsers/JsonApiParserTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/QueryEngineTest.java
- elide-datastore/elide-datastore-hibernate3/src/test/java/com/yahoo/elide/tests/DataStoreIT.java
- elide-datastore/elide-datastore-hibernate5/src/test/java/com/yahoo/elide/tests/DataStoreIT.java
- elide-datastore/elide-datastore-search/src/test/java/com/yahoo/elide/datastores/search/DataStoreLoadTest.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/UserTypeIT.java
- elide-spring/elide-spring-boot-autoconfigure/pom.xml
- elide-spring/elide-spring-boot-starter/pom.xml
- elide-standalone/pom.xml
See #1482 
General cleanup.
* normalizePath regex improvement
* Remove repeated conditional test
* use entrySet
* diamonds for new HashMap
* Unnecessary duplication in swagger pom
* ImmutableList for tests
Code quality
Unit testing
> Path matcher 5.x

- elide-async/src/main/java/com/yahoo/elide/async/models/AsyncBase.java
- elide-async/src/main/java/com/yahoo/elide/async/models/AsyncQuery.java
- elide-async/src/main/java/com/yahoo/elide/async/models/QueryStatus.java
- elide-async/src/main/java/com/yahoo/elide/async/service/AsyncCleanerService.java
- elide-async/src/main/java/com/yahoo/elide/async/service/AsyncQueryCancelThread.java
- elide-async/src/main/java/com/yahoo/elide/async/service/AsyncQueryCleanerThread.java
- elide-async/src/main/java/com/yahoo/elide/async/service/AsyncQueryDAO.java
- elide-async/src/main/java/com/yahoo/elide/async/service/DateUtil.java
- elide-async/src/main/java/com/yahoo/elide/async/service/DefaultAsyncQueryDAO.java
- elide-async/src/test/java/com/yahoo/elide/async/service/AsyncCleanerServiceTest.java
- elide-async/src/test/java/com/yahoo/elide/async/service/AsyncQueryCancelThreadTest.java
- elide-async/src/test/java/com/yahoo/elide/async/service/AsyncQueryCleanerThreadTest.java
- elide-async/src/test/java/com/yahoo/elide/async/service/DefaultAsyncQueryDAOTest.java
- elide-core/src/main/java/com/yahoo/elide/core/TransactionRegistry.java
- elide-integration-tests/src/test/java/com/yahoo/elide/async/integration/tests/framework/AsyncIntegrationTestApplicationResourceConfig.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/AsyncProperties.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAsyncConfiguration.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideResourceConfig.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideStandaloneSettings.java
- elide-standalone/src/test/java/example/ElideStandaloneDisableAggStoreTest.java
- elide-standalone/src/test/java/example/ElideStandaloneMetadataStoreMissingTest.java
- elide-standalone/src/test/java/example/ElideStandaloneTest.java
Cancel long running or cancelled async queries 
Tested in the Example Application
> Cancel long running or cancelled async queries

- elide-annotations/src/main/java/com/yahoo/elide/security/RequestScope.java
- elide-async/src/main/java/com/yahoo/elide/async/hooks/ExecuteQueryHook.java
- elide-async/src/main/java/com/yahoo/elide/async/models/AsyncQuery.java
- elide-async/src/main/java/com/yahoo/elide/async/service/AsyncExecutorService.java
- elide-async/src/main/java/com/yahoo/elide/async/service/AsyncQueryThread.java
- elide-async/src/main/java/com/yahoo/elide/async/service/DefaultAsyncQueryDAO.java
- elide-async/src/test/java/com/yahoo/elide/async/hooks/ExecuteQueryHookTest.java
- elide-async/src/test/java/com/yahoo/elide/async/service/AsyncExecutorServiceTest.java
- elide-async/src/test/java/com/yahoo/elide/async/service/DefaultAsyncQueryDAOTest.java
- elide-contrib/elide-dynamic-config-helpers/pom.xml
- elide-integration-tests/src/test/java/com/yahoo/elide/async/integration/tests/framework/AsyncIntegrationTestApplicationResourceConfig.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/AsyncProperties.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAsyncConfiguration.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideResourceConfig.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideStandaloneAsyncSettings.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideStandaloneSettings.java
- elide-standalone/src/test/java/example/ElideStandaloneDisableAggStoreTest.java
- elide-standalone/src/test/java/example/ElideStandaloneMetadataStoreMissingTest.java
- elide-standalone/src/test/java/example/ElideStandaloneTest.java
Co-authored-by: chandrakaran
Resolves  #1272
Refactoring of existing classes and prep work for using ResultStorageEngine
Refer #1272
Existing Test cases pass and new test cases.
> Data export - Refactoring and Prep for using ResultStorageEngine

- elide-async/src/test/java/com/yahoo/elide/async/hooks/ExecuteQueryHookTest.java
> Reverting Accidental commit to elide-5.x

- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/MetaDataStoreIntegrationTest.java
> Fixing metadata store test

- elide-contrib/elide-dynamic-config-helpers/src/main/java/com/yahoo/elide/contrib/dynamicconfighelpers/model/Measure.java
- elide-contrib/elide-dynamic-config-helpers/src/main/resources/elideTableSchema.json
- elide-contrib/elide-dynamic-config-helpers/src/main/resources/templates/table.hbs
- elide-contrib/elide-dynamic-config-helpers/src/test/java/com/yahoo/elide/contrib/dynamicconfighelpers/DynamicConfigSchemaValidatorTest.java
- elide-contrib/elide-dynamic-config-helpers/src/test/java/com/yahoo/elide/contrib/dynamicconfighelpers/parser/handlebars/HandlebarsHydratorTest.java
- elide-contrib/elide-dynamic-config-helpers/src/test/resources/validator/invalid_schema/invalid_query_plan_classname.hjson
- elide-contrib/elide-dynamic-config-helpers/src/test/resources/validator/valid/models/tables/player_stats_extends.hjson
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Metric.java
Adds HJSON configuration for metric query plans.
> HJSON metric config for query plans

- elide-contrib/elide-dynamic-config-helpers/pom.xml
> Update snapshot version in pom.xml

- elide-contrib/elide-dynamic-config-helpers/src/main/java/com/yahoo/elide/contrib/dynamicconfighelpers/DynamicConfigHelpers.java
- elide-contrib/elide-dynamic-config-helpers/src/main/java/com/yahoo/elide/contrib/dynamicconfighelpers/DynamicConfigSchemaValidator.java
- elide-contrib/elide-dynamic-config-helpers/src/test/java/com/yahoo/elide/contrib/dynamicconfighelpers/DynamicConfigSchemaValidatorTest.java
- elide-contrib/elide-dynamic-config-helpers/src/test/java/com/yahoo/elide/contrib/dynamicconfighelpers/validator/DynamicConfigValidatorTest.java
HJSON schema errors (either parsing or schema validation) are not clear.  This PR surfaces better errors.
> Added better HJSON parsing exception errors

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/QueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Table.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/Queryable.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLQueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLTable.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/annotation/dimensionformula/DimensionFormulaTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/annotation/metricformula/MetricFormulaTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/MetaDataStoreIntegrationTest.java
Remove dbConnectionName form Table class
Add ConnectionDetails to SQLTable class
Existing Tests pass.
> Refactor dbconnection

- elide-model-config/src/main/java/com/yahoo/elide/contrib/dynamicconfighelpers/validator/DynamicConfigValidator.java
HJSON files should only be referenced from the classpath if the path is available.  The file system should be treated as a fallback.  
This will enhance the security of configuration loading.
> Always Prefer Secure Configuration Over Less Secure

- README.md
> Updating Elide 5 Readme 

- elide-model-config/src/main/java/com/yahoo/elide/contrib/dynamicconfighelpers/DynamicConfigHelpers.java
- elide-model-config/src/test/java/com/yahoo/elide/contrib/dynamicconfighelpers/validator/DynamicConfigValidatorTest.java
Change HJSON to Hjson in the code
Existing test case pass
> HJSON to Hjson

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Table.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/MetaDataStoreIntegrationTest.java
Remove Id field from dimensions for fact models
> Remove Id field from dimensions for fact models

- elide-standalone/README.md
Fixes broken link in README.md for Elide standalone
> Fixed broken link

- elide-model-config/src/main/java/com/yahoo/elide/contrib/dynamicconfighelpers/DraftV4LibraryWithElideFormatAttr.java
- elide-model-config/src/main/java/com/yahoo/elide/contrib/dynamicconfighelpers/DynamicConfigHelpers.java
- elide-model-config/src/main/java/com/yahoo/elide/contrib/dynamicconfighelpers/DynamicConfigSchemaValidator.java
- elide-model-config/src/main/java/com/yahoo/elide/contrib/dynamicconfighelpers/MessageBundleWithElideMessages.java
- elide-model-config/src/main/java/com/yahoo/elide/contrib/dynamicconfighelpers/jsonformats/ElideCardinalityFormatAttr.java
- elide-model-config/src/main/java/com/yahoo/elide/contrib/dynamicconfighelpers/jsonformats/ElideFieldNameFormatAttr.java
- elide-model-config/src/main/java/com/yahoo/elide/contrib/dynamicconfighelpers/jsonformats/ElideFieldTypeFormatAttr.java
- elide-model-config/src/main/java/com/yahoo/elide/contrib/dynamicconfighelpers/jsonformats/ElideGrainTypeFormatAttr.java
- elide-model-config/src/main/java/com/yahoo/elide/contrib/dynamicconfighelpers/jsonformats/ElideJoinTypeFormatAttr.java
- elide-model-config/src/main/java/com/yahoo/elide/contrib/dynamicconfighelpers/jsonformats/ElideNameFormatAttr.java
- elide-model-config/src/main/java/com/yahoo/elide/contrib/dynamicconfighelpers/jsonformats/ElideTimeFieldTypeFormatAttr.java
- elide-model-config/src/main/java/com/yahoo/elide/contrib/dynamicconfighelpers/model/Dimension.java
- elide-model-config/src/main/java/com/yahoo/elide/contrib/dynamicconfighelpers/model/Measure.java
- elide-model-config/src/main/java/com/yahoo/elide/contrib/dynamicconfighelpers/model/Table.java
- elide-model-config/src/main/java/com/yahoo/elide/contrib/dynamicconfighelpers/validator/DynamicConfigValidator.java
- elide-model-config/src/main/resources/elideTableSchema.json
- elide-model-config/src/test/java/com/yahoo/elide/contrib/dynamicconfighelpers/DynamicConfigSchemaValidatorTest.java
- elide-model-config/src/test/java/com/yahoo/elide/contrib/dynamicconfighelpers/validator/DynamicConfigValidatorTest.java
- elide-model-config/src/test/resources/validator/bad_dim_name/models/tables/table1.hjson
- elide-model-config/src/test/resources/validator/invalid_schema/table_schema_with_multiple_errors.hjson
Display user friendly messages for Json Schema validation failures
Additional tests included.
> Display user friendly messages for Json Schema validation failures

- elide-standalone/README.md
Update Standalone examples to reflect separate analytic settings.
> Update Standalone examples to reflect separate analytic settings.

- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/DraftV4LibraryWithElideFormatAttr.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/MessageBundleWithElideMessages.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/jsonformats/ElideJDBCUrlFormatAttr.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/jsonformats/JavaClassNameFormatAttr.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/jsonformats/JavaClassNameWithExtFormatAttr.java
- elide-model-config/src/main/resources/elideDBConfigSchema.json
- elide-model-config/src/main/resources/elideSecuritySchema.json
- elide-model-config/src/main/resources/elideTableSchema.json
- elide-model-config/src/main/resources/elideVariableSchema.json
- elide-model-config/src/test/java/com/yahoo/elide/modelconfig/DynamicConfigSchemaValidatorTest.java
- elide-model-config/src/test/resources/validator/invalid_schema/db_invalid.hjson
- elide-model-config/src/test/resources/validator/invalid_schema/variables_invalid.hjson
Add custom formats for DB schema.
> Add custom formats for DB schema

- README.md
> Updated readme to qualify that docs refer to elide 5

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/main/java/com/yahoo/elide/core/datastore/inmemory/HashMapStoreTransaction.java
- elide-core/src/main/java/com/yahoo/elide/core/datastore/inmemory/InMemoryStoreTransaction.java
- elide-core/src/main/java/com/yahoo/elide/core/dictionary/EntityDictionary.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/Operator.java
- elide-core/src/main/java/com/yahoo/elide/core/utils/ClassScanner.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/EntityProjectionMaker.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/QueryValidator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/core/Slf4jQueryLogger.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/PersistentResourceFetcher.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/ModelBuilderTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/controllers/SwaggerController.java
Minor code cleanup
* prefer method reference to lambda
* use `orElseGet` when calling a function
* `.filter(...).findAny().isPresent()` should be `anyMatch`
Code quality
Unit testing
> Minor cleanup

- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/validator/DynamicConfigValidator.java
- elide-model-config/src/test/java/com/yahoo/elide/modelconfig/validator/DynamicConfigValidatorTest.java
- elide-model-config/src/test/resources/validator/bad_cyclic_inheritance/models/tables/tableA.hjson
- elide-model-config/src/test/resources/validator/bad_cyclic_inheritance/models/tables/tableB.hjson
- elide-model-config/src/test/resources/validator/missing_inheritance/models/tables/tableA.hjson
> Added validation logic to check for inheritance cycles

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/AggregationDataStore.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/MetaDataStore.java
Reduced aggregation data store class scans on startup.
> Reduce class scans

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/dialects/AbstractSqlDialect.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/dialects/SQLDialect.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/dialects/impl/H2Dialect.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/dialects/impl/MySQLDialect.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLReferenceTable.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/example/VideoGame.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/framework/SQLUnitTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/H2ExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/HiveExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/MySQLExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/PostgresExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/PrestoDBExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/resources/continent.csv
- elide-datastore/elide-datastore-aggregation/src/test/resources/country.csv
- elide-datastore/elide-datastore-aggregation/src/test/resources/player.csv
- elide-datastore/elide-datastore-aggregation/src/test/resources/player_stats.csv
- elide-datastore/elide-datastore-aggregation/src/test/resources/video_games.csv
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/validator/DynamicConfigValidator.java
- elide-model-config/src/main/resources/elideTableSchema.json
Join Type support in aggregation store.
Additional tests included.
> Join Type support in aggregation store.

- elide-spring/elide-spring-boot-autoconfigure/pom.xml
- elide-spring/pom.xml
> Upgrade spring.boot version

- pom.xml
> Updating jetty version for security issue

- README.md
> Update Navi link in README.md

- elide-core/src/main/java/com/yahoo/elide/Elide.java
- suppressions.xml
Resolves #1740
Convert ConstraintViolationException into CustomErrorException
see issue
Manually :(
> Closes #1740 More meaningful handling of constraint violations

- README.md
> SD Build Status Badge

- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/ElideSettings.java
- elide-core/src/main/java/com/yahoo/elide/ElideSettingsBuilder.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/EntityProjectionMaker.java
- elide-core/src/test/java/com/yahoo/elide/core/lifecycle/LifeCycleTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/AggregationDataStoreIntegrationTest.java
- suppressions.xml
Resolves https://github.com/yahoo/elide/issues/1697
Validate Query Parameters for GET requests.
New tests added.
> Issue#1697 Validate Query Parameters for GET requests

- elide-async/src/main/java/com/yahoo/elide/async/hooks/AsyncQueryHook.java
- elide-async/src/main/java/com/yahoo/elide/async/models/TableExport.java
- elide-async/src/main/java/com/yahoo/elide/async/models/TableExportResult.java
- elide-async/src/main/java/com/yahoo/elide/async/service/storageengine/FileResultStorageEngine.java
- elide-async/src/main/java/com/yahoo/elide/async/service/storageengine/ResultStorageEngine.java
- elide-async/src/main/java/com/yahoo/elide/async/service/thread/AsyncQueryThread.java
- elide-async/src/test/java/com/yahoo/elide/async/service/AsyncExecutorServiceTest.java
- elide-async/src/test/java/com/yahoo/elide/async/service/AsyncQueryThreadTest.java
- elide-async/src/test/java/com/yahoo/elide/async/service/storageengine/FileResultStorageEngineTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/ControllerTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/DisableAggStoreControllerTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/DisableMetaDataStoreControllerTest.java
- elide-standalone/src/test/java/example/ElideStandaloneDisableAggStoreTest.java
- elide-standalone/src/test/java/example/ElideStandaloneDisableMetaDataStoreTest.java
- elide-standalone/src/test/java/example/ElideStandaloneTest.java
Add Table Export Models.
Preparing for Table Export Implementation.
Existing Test pass. 
> Initial Table Export Model

- elide-spring/elide-spring-boot-autoconfigure/pom.xml
- elide-spring/pom.xml
- pom.xml
- suppressions.xml
> Bumped packages to fix CVE errors in Elide 4

- elide-async/src/main/java/com/yahoo/elide/async/service/dao/AsyncAPIDAO.java
- elide-async/src/main/java/com/yahoo/elide/async/service/dao/DefaultAsyncAPIDAO.java
- elide-async/src/main/java/com/yahoo/elide/async/service/thread/AsyncAPICancelThread.java
- elide-async/src/main/java/com/yahoo/elide/async/service/thread/AsyncAPICleanerThread.java
- elide-async/src/test/java/com/yahoo/elide/async/service/dao/DefaultAsyncAPIDAOTest.java
- elide-async/src/test/java/com/yahoo/elide/async/service/thread/AsyncAPICancelThreadTest.java
- elide-async/src/test/java/com/yahoo/elide/async/service/thread/AsyncAPICleanerThreadTest.java
Resolves #1757
Cast Exception Message in Hibernate Integration Tests
Cast Exception Message in Integration Tests
Existing Test Pass. No Exception message in the logs.
> Resolve Hibernate 3 and Hibernate 5 Exceptions for LoadObjects

- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideConfigProperties.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/JsonApiControllerProperties.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/controllers/GraphqlController.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/ControllerTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/IntegrationTestSetup.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/resources/application.yaml
This makes turning on JSON-API links push button simple.
> Added a new setting to Spring to enable/disable JSON-API links

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLQueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/AggregationDataStoreIntegrationTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/H2ExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/HiveExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/MySQLExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/PostgresExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/PrestoDBExplainQueryTest.java
Resolves https://github.com/yahoo/elide/issues/1750
Fix SQL query generation for record count
> Issue#1750 Fix SQL query generation for record count

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResourceSet.java
- elide-core/src/main/java/com/yahoo/elide/core/ResourceLineage.java
- elide-core/src/main/java/com/yahoo/elide/core/audit/LogMessageImpl.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/links/DefaultJSONApiLinks.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/parser/state/CollectionTerminalState.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistenceResourceTestSetup.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceNoopUpdateTest.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-core/src/test/java/com/yahoo/elide/core/audit/LogMessageImplTest.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/visitors/VerifyFieldAccessFilterExpressionVisitorTest.java
- elide-core/src/test/java/com/yahoo/elide/core/lifecycle/LifeCycleTest.java
- elide-core/src/test/java/com/yahoo/elide/core/security/PermissionAnnotationTest.java
- elide-core/src/test/java/com/yahoo/elide/core/security/PermissionExecutorTest.java
- elide-core/src/test/java/com/yahoo/elide/core/security/permissions/PermissionExpressionBuilderTest.java
- elide-core/src/test/java/com/yahoo/elide/jsonapi/JsonApiTest.java
- elide-core/src/test/java/com/yahoo/elide/jsonapi/document/processors/IncludedProcessorTest.java
- elide-datastore/elide-datastore-noop/src/main/java/com/yahoo/elide/datastores/noop/NoopTransaction.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/PersistentResourceFetcher.java
JSON-API links have two bugs per spectrum chat:
https://spectrum.chat/elide/general/how-to-set-baseurlendpoint-for-links-in-json-api~d7e39f5f-55ac-49fe-adf8-a0153f688741?m=MTYxMDU4NTQyNzc5Mw==
Modified existing unit tests.
> Elide 5: Fixed bugs in JSON-API links

- elide-core/src/main/java/com/yahoo/elide/audit/LogMessage.java
- elide-core/src/main/java/com/yahoo/elide/core/DefaultJSONApiLinks.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResourceSet.java
- elide-core/src/main/java/com/yahoo/elide/core/ResourceLineage.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/CollectionTerminalState.java
- elide-core/src/test/java/com/yahoo/elide/audit/LogMessageTest.java
- elide-core/src/test/java/com/yahoo/elide/core/LifeCycleTest.java
- elide-core/src/test/java/com/yahoo/elide/core/PermissionAnnotationTest.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistenceResourceTestSetup.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceNoopUpdateTest.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-core/src/test/java/com/yahoo/elide/core/UpdateOnCreateTest.java
- elide-core/src/test/java/com/yahoo/elide/core/VerifyFieldAccessFilterExpressionVisitorTest.java
- elide-core/src/test/java/com/yahoo/elide/jsonapi/JsonApiTest.java
- elide-core/src/test/java/com/yahoo/elide/jsonapi/document/processors/IncludedProcessorTest.java
- elide-core/src/test/java/com/yahoo/elide/security/PermissionExecutorTest.java
- elide-core/src/test/java/com/yahoo/elide/security/permissions/PermissionExpressionBuilderTest.java
- elide-datastore/elide-datastore-noop/src/main/java/com/yahoo/elide/datastores/noop/NoopTransaction.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/PersistentResourceFetcher.java
> Fixed issues with JSON-API Links in Elide 4

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLQueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/dialects/AbstractSqlDialect.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/dialects/SQLDialect.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/dialects/SQLDialectFactory.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/dialects/impl/DruidDialect.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/dialects/impl/HiveDialect.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/framework/SQLUnitTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/DruidExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/H2ExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/HiveExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/MySQLExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/PostgresExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/PrestoDBExplainQueryTest.java
Create Druid dialect in aggregation datastore. 
unit test
> add druid dialect with new pagination query structure

- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/extensions/PatchRequestScope.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
https://spectrum.chat/elide/general/query-parameters-in-json-patch-extension-requests~42dd8af5-3986-47ca-a77a-dff68e8ad702
> Passing query parameters and headers to patch extension request scope

- elide-spring/elide-spring-boot-starter/README.md
- elide-spring/elide-spring-boot-starter/pom.xml
Mirroring Elide 4 change (#1805)
> Remove jetty from starter

- elide-core/src/main/java/com/yahoo/elide/core/filter/predicates/FilterPredicate.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/QueryEngineTest.java
Fix for FieldType in FilterPredicate
> Fix for FieldType in FilterPredicate

- CONTRIBUTING.md
> updating contrib guidelines for hackathon

- elide-async/src/main/java/com/yahoo/elide/async/service/AsyncExecutorService.java
- elide-async/src/test/java/com/yahoo/elide/async/service/AsyncExecutorServiceTest.java
- elide-integration-tests/src/test/java/com/yahoo/elide/async/integration/tests/framework/AsyncIntegrationTestApplicationResourceConfig.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAsyncConfiguration.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/AsyncTest.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/ElideStandalone.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideResourceConfig.java
- elide-standalone/src/test/java/example/ElideStandaloneExportTest.java
Resolves https://github.com/yahoo/elide/issues/1798
Remove Singleton Pattern for Async Service Classes
> Issue#1798 Remove Singleton Pattern for Async Service Classes

- elide-core/src/main/java/com/yahoo/elide/core/dictionary/EntityDictionary.java
- elide-core/src/test/java/com/yahoo/elide/core/dictionary/EntityDictionaryTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAsyncConfiguration.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/AsyncTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/ControllerTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/DisableAggStoreControllerTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/DisableMetaDataStoreControllerTest.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideResourceConfig.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideStandaloneSettings.java
- elide-standalone/src/test/java/example/ElideStandaloneDisableAggStoreTest.java
- elide-standalone/src/test/java/example/ElideStandaloneDisableMetaDataStoreTest.java
- elide-standalone/src/test/java/example/ElideStandaloneExportTest.java
- elide-standalone/src/test/java/example/ElideStandaloneTest.java
Resolves #1832
Exclude models based on certain conditions.
Refer #1832
Existing and New test cases pass
> Exclude Models based on Conditions

- elide-async/src/main/java/com/yahoo/elide/async/models/TableExportResult.java
LOB Annotation for `message` in TableExportResult.
> LOB for message in TableExportResult

- elide-spring/pom.xml
- pom.xml
Sync version updates with 5x
Code quality
Unit tests
> bump versions

- README.md
> updated README with elide intro video

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/timegrains/Time.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/example/PlayerStats.java
Resolves #1902
Fix Build warnings with Lombok.
Resolve build warnings for Hacktogether
Existing Tests pass. Build warnings are gone.
> elide-datastore-aggregation: Fix build warnings

- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/DynamicConfigHelpers.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/DynamicConfigSchemaValidator.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/Dimension.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/Measure.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/Table.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/validator/DynamicConfigValidator.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/verify/DynamicConfigVerifier.java
Resolves https://github.com/yahoo/elide/issues/1893
Fix Javadoc warnings for elide-model-config
Existing Tests Pass.
> Fix elide-model-config javadoc warnings

- elide-test/src/main/java/com/yahoo/elide/test/graphql/GraphQLDSL.java
- elide-test/src/main/java/com/yahoo/elide/test/graphql/elements/Argument.java
- elide-test/src/main/java/com/yahoo/elide/test/graphql/elements/Arguments.java
- elide-test/src/main/java/com/yahoo/elide/test/graphql/elements/VariableDefinitions.java
- elide-test/src/main/java/com/yahoo/elide/test/jsonapi/elements/PatchOperation.java
- elide-test/src/test/java/com/yahoo/elide/test/graphql/GraphQLDSLTest.java
Resolves #1886
Modify javadoc to remove warnings.
Follow best practices and reduce tech debt.
Running code inspections through my IDE.
> Fix javadoc to remove warnings

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/QueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/QueryValidator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/annotation/ColumnMeta.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/annotation/DimensionFormula.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/annotation/MetricFormula.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/annotation/TableMeta.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/core/JoinPath.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/core/QueryLogger.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/core/QueryResponse.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/core/Slf4jQueryLogger.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/MetaDataStore.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Column.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/ColumnProjection.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/Optimizer.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/Queryable.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/NamedParamPreparedStatement.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/annotation/FromSubquery.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/annotation/FromTable.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/annotation/VersionQuery.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/dialects/SQLDialect.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/DynamicSQLReferenceTable.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLReferenceTable.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLReferenceVisitor.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLColumnProjection.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/QueryEngineTest.java
Resolves #1901 
elide-datastore-aggregation - fix javadoc build warning
> elide-datastore-aggregation - fix javadoc build warning

- elide-graphql/src/main/java/com/yahoo/elide/graphql/parser/GraphQLEntityProjectionMaker.java
Remove dead code from GraphQLEntityProjectionMaker.java
Existing test cases pass.
> Remove dead code from GraphQLEntityProjectionMaker.java

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/AggregationDataStoreTransaction.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/EntityProjectionTranslator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/Query.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/EntityProjectionTranslatorTest.java
Populate $$user and $$request context
> Populate $$user and $$request context

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/QueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/annotation/TableMeta.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/dynamic/TableType.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Table.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/Optimizer.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/QueryVisitor.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLQueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/AggregateBeforeJoinOptimizer.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/dynamic/TableTypeTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/example/PlayerStats.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/AggregateBeforeJoinOptimizerTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SkipOptimizerTest.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/Table.java
- elide-model-config/src/main/resources/elideTableSchema.json
- elide-model-config/src/test/java/com/yahoo/elide/modelconfig/parser/handlebars/HandlebarsHydratorTest.java
- elide-model-config/src/test/resources/validator/valid/models/tables/player_stats.hjson
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideStandaloneSettings.java
Adds hints to turn on/off experimental optimization at the Table level.
> Add Table Level Query Hints

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/QueryValidator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/Query.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/QueryPlan.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/Queryable.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLTable.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/AggregateBeforeJoinOptimizer.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/QueryTranslator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLColumnProjection.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLMetricProjection.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLTimeDimensionProjection.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/example/GameRevenue.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/example/PlayerStats.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/example/PlayerStatsWithRequiredFilter.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/example/TimeGrainDefinitions.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/framework/SQLUnitTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/DruidExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/H2ExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/HiveExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/MySQLExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/PostgresExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/PrestoDBExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/AggregateBeforeJoinOptimizerTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SkipOptimizerTest.java
- elide-datastore/elide-datastore-aggregation/src/test/resources/prepare_tables.sql
- pom.xml
Adds tests and fixes some bugs with simple optimizer expansions.
> Phase 8 of Aggregation Store Optimizer: Adding more tests

- elide-core/src/main/java/com/yahoo/elide/core/filter/Operator.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/parser/state/RelationshipTerminalState.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistenceResourceTestSetup.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLTable.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/AbstractHQLQueryBuilder.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/SubCollectionFetchQueryBuilder.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/PaginateIT.java
Use dedicated function interfaces where possible.
Code quality.
Unit tests.
> refactor Functional Interfaces

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/dynamic/TableType.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/EntityHydratorTest.java
Rename and refactor test.
Use multiple return instead of hand-crafted Answer object.
Code quality.
Unit test.
> refactor test

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/expression/ExpressionParser.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/expression/JoinReference.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/expression/LogicalReference.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/expression/PhysicalReference.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/expression/Reference.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/expression/ReferenceVisitor.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/expression/ExpressionParserTest.java
Adding parser for handlebar expressions in Aggregation store semantic layer.
> Expression reference ast and parser

- elide-core/src/main/java/com/yahoo/elide/core/utils/TypeHelper.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/annotation/MetricFormula.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/FormulaValidator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Column.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Metric.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/Queryable.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/expression/ExpressionParser.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLReferenceTable.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLColumnProjection.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLMetricProjection.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLTimeDimensionProjection.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/custom/DailyAverageScorePerPeriod.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/example/PlayerStats.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/expression/ExpressionParserTest.java
Formula Validation using ExpressionParser.
> Formula Validation using ExpressionParser

- elide-core/src/main/java/com/yahoo/elide/core/utils/TypeHelper.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/expression/ExpressionParser.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/filter/CaseAwareJPQLGenerator.java
Reuse existing StringUtils.isEmpty that we use elsewhere.
Code quality.
Unit testing.
> reuse isEmpty

- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/JPQLTransaction.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/Query.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/ScrollableIteratorBase.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/SubCollectionPageTotalsQueryBuilder.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/TestQueryWrapper.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/ScrollableIterator.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/porting/QueryWrapper.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/ScrollableIterator.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/porting/QueryWrapper.java
- elide-datastore/elide-datastore-jpa/src/main/java/com/yahoo/elide/datastores/jpa/ScrollableIterator.java
- elide-datastore/elide-datastore-jpa/src/main/java/com/yahoo/elide/datastores/jpa/porting/QueryWrapper.java
- elide-datastore/elide-datastore-jpa/src/main/java/com/yahoo/elide/datastores/jpa/transaction/AbstractJpaTransaction.java
- elide-integration-tests/src/test/java/example/BaseId.java
Consolidate Hibernate and JPA transaction logic into parent class.  
Moves common code to one location to reduce code duplication.
Code quality. 
Unit testing.  Local testing.
> Hibernate jpa

- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/Config.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/DynamicConfigHelpers.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/DynamicConfigSchemaValidator.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/ElideNamespaceConfig.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/Join.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/NamespaceConfig.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/Table.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/validator/DynamicConfigValidator.java
- elide-model-config/src/main/resources/elideNamespaceConfigSchema.json
- elide-model-config/src/main/resources/elideTableSchema.json
- elide-model-config/src/test/java/com/yahoo/elide/modelconfig/parser/handlebars/HandlebarsHydratorTest.java
- elide-model-config/src/test/resources/validator/valid/models/namespaces/player.hjson
- elide-model-config/src/test/resources/validator/valid/models/tables/player_stats.hjson
https://github.com/yahoo/elide/issues/2010
https://github.com/yahoo/elide/issues/2010
Existing test cases pass, new test files added.
> Table Namespace Model Config

- pom.xml
> Revert "Disable Dependency Check"

- elide-core/src/main/java/com/yahoo/elide/core/Path.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/FilterPredicateTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/annotation/metricformula/MetricFormulaTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/cache/QueryKeyExtractorTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/core/JoinPathTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/core/SqlReferenceVisitorTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/filter/visitor/MatchesTemplateVisitorTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/filter/visitor/SplitFilterExpressionVisitorTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/framework/SQLUnitTest.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/core/filter/FilterTranslatorTest.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/AbstractHQLQueryBuilderTest.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/RootCollectionFetchQueryBuilderTest.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/SubCollectionFetchQueryBuilderTest.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/SubCollectionPageTotalsQueryBuilderTest.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/AbstractHibernateStore.java
- elide-datastore/elide-datastore-inmemorydb/src/test/java/com/yahoo/elide/datastores/inmemory/HashMapDataStoreTest.java
- elide-datastore/elide-datastore-jpa/src/main/java/com/yahoo/elide/datastores/jpa/JpaDataStore.java
- elide-datastore/elide-datastore-jpa/src/test/java/com/yahoo/elide/datastores/jpa/JpaDataStoreTest.java
- elide-datastore/elide-datastore-multiplex/src/test/java/com/yahoo/elide/datastores/multiplex/MultiplexManagerTest.java
- elide-datastore/elide-datastore-multiplex/src/test/java/com/yahoo/elide/datastores/multiplex/bridgeable/BridgeableRedisStore.java
- elide-datastore/elide-datastore-noop/src/test/java/com/yahoo/elide/datastores/noop/NoopDataStoreTest.java
- elide-datastore/elide-datastore-search/src/main/java/com/yahoo/elide/datastores/search/FilterExpressionToLuceneQuery.java
- elide-datastore/elide-datastore-search/src/test/java/com/yahoo/elide/datastores/search/DataStoreLoadTest.java
- elide-datastore/elide-datastore-search/src/test/java/com/yahoo/elide/datastores/search/DataStoreSupportsFilteringTest.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLConversionUtils.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/GraphQLConversionUtilsTest.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/ModelBuilderTest.java
- elide-swagger/src/main/java/com/yahoo/elide/swagger/JsonApiModelResolver.java
Replace deprecated TypeHelper.getClassType
Code quality
Unit tests
> ClassType.of

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/ColumnContext.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/Context.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/LogicalRefContext.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/TemplateProjection.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/expression/JoinExpressionExtractor.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/QueryTranslator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLColumnProjection.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/metadata/ColumnContextTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/metadata/LogicalRefContextTest.java
> Use ColumnProjection within context

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/dictionary/EntityDictionary.java
- elide-core/src/main/java/com/yahoo/elide/core/request/EntityProjection.java
- elide-core/src/main/java/com/yahoo/elide/core/request/Pagination.java
- elide-core/src/main/java/com/yahoo/elide/core/security/checks/prefab/Collections.java
- elide-core/src/main/java/com/yahoo/elide/core/security/executors/MultiplexPermissionExecutor.java
- elide-core/src/main/java/com/yahoo/elide/core/security/permissions/PermissionExpressionBuilder.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/links/DefaultJSONApiLinks.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/links/JSONApiLinks.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/parser/state/CollectionTerminalState.java
- elide-core/src/main/java/com/yahoo/elide/utils/HeaderUtils.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/QueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLQueryEngine.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLConversionUtils.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/PersistentResourceFetcher.java
- elide-integration-tests/src/test/java/example/User.java
- elide-test/src/main/java/com/yahoo/elide/test/graphql/GraphQLDSL.java
Refactor using Optional flow.
Code quality.
Unit testing.
> Optional flow

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/annotation/Temporal.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/annotation/TimeGrainDefinition.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/dynamic/TableType.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/ColumnContext.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/TimeDimensionGrain.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLTimeDimensionProjection.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/example/TimeGrainDefinitions.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/MetaDataStoreIntegrationTest.java
- elide-datastore/elide-datastore-aggregation/src/test/resources/configs/models/tables/SalesView.hjson
- elide-spring/elide-spring-boot-autoconfigure/src/test/resources/configs/models/tables/playerStats.hjson
Remove usage of {{}} for time demensions
> Remove usage of {{}} for time demensions

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/AggregationDataStoreTransaction.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/DefaultQueryValidator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/EntityProjectionTranslator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/QueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/QueryValidator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/enums/ValueType.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Argument.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Column.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Table.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/Query.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/EntityHydrator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLQueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/DefaultQueryValidatorTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/example/PlayerStatsView.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/framework/AggregationDataStoreTestHarness.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/framework/SQLUnitTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/MetaDataStoreIntegrationTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/metadata/enums/ValueTypeTest.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/QueryRunner.java
- elide-integration-tests/src/test/java/com/yahoo/elide/initialization/GraphQLIntegrationTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideStandaloneSettings.java
Two changes:
1. Primary work - logic to validate the values of parameterized metric and dimension values.
2. A small change to mirror JSON-API JSR303 error handling in GraphQL.
> Injection Protection for parameterized metrics/dimensions

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/QueryValidator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/ColumnContext.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/ColumnSubContext.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/TableContext.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/TableSubContext.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLQueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/expression/JoinExpressionExtractor.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/QueryTranslator.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/DefaultQueryValidatorTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/example/PlayerStatsView.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/framework/SQLUnitTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/DruidExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/H2ExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/HiveExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/MySQLExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/PostgresExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/PrestoDBExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/QueryEngineTest.java
Resolve arguments in FromSubquery
> Resolve arguments in FromSubquery

- elide-core/src/main/java/com/yahoo/elide/core/security/executors/ActivePermissionExecutor.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/AggregationDataStoreTransaction.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/DefaultQueryValidator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/dynamic/TableType.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/AggregationDataStoreIntegrationTest.java
Also prohibits filter by ID for aggregation models.
> Aggregation Store: Verify write requests are denied

- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/Named.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/validator/DynamicConfigValidator.java
- elide-model-config/src/test/java/com/yahoo/elide/modelconfig/parser/handlebars/HandlebarsHydratorTest.java
- elide-model-config/src/test/resources/validator/bad_table_join_type/models/tables/table1.hjson
- elide-model-config/src/test/resources/validator/bad_table_sql/models/tables/table1.hjson
- elide-model-config/src/test/resources/validator/invalid_schema/invalid_dimension_data_source.hjson
- elide-model-config/src/test/resources/validator/invalid_schema/invalid_query_plan_classname.hjson
- elide-model-config/src/test/resources/validator/invalid_schema/invalid_table_filter.hjson
- elide-model-config/src/test/resources/validator/mismatch_dbconfig/models/tables/table1.hjson
- elide-model-config/src/test/resources/validator/missing_security/models/tables/table2.hjson
- elide-model-config/src/test/resources/validator/missing_variable/models/tables/table2.hjson
- elide-model-config/src/test/resources/validator/valid/models/tables/player_stats.hjson
- elide-model-config/src/test/resources/validator/valid/models/tables/player_stats_extends.hjson
Code cleanup for elide-model-config
> Code cleanup for elide-model-config

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/EntityHydrator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/QueryTranslator.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/AggregationDataStoreIntegrationTest.java
> Fix bug querying a dynamic analytic model by ID in GraphQL

- elide-core/src/main/java/com/yahoo/elide/core/dictionary/EntityBinding.java
- elide-integration-tests/src/test/java/example/embeddedid/Building.java
> Support for EmbeddedId

- elide-model-config/pom.xml
> Fixing CVE-2021-22118

- README.md
> Small edits to readme to reflect Elide 5.

- elide-swagger/src/main/java/com/yahoo/elide/swagger/JsonApiModelResolver.java
- elide-swagger/src/test/java/com/yahoo/elide/swagger/JsonApiModelResolverTest.java
- elide-swagger/src/test/java/com/yahoo/elide/swagger/SwaggerBuilderTest.java
- elide-swagger/src/test/java/example/models/Book.java
Resolves #2203
@Brutus5000 
How about this?
> Resolves #2203

- elide-core/src/main/java/com/yahoo/elide/core/type/ClassType.java
Resolves #2220
See issue.
Reduce memory allocations and cpu spent on garbage collection
Covered by Elide Unit tests.
> Resolves #2220

- elide-core/src/main/java/com/yahoo/elide/core/dictionary/EntityDictionary.java
> Resolves #2215

- README.md
> Switch to discord

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/utils/TypeHelper.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistenceResourceTestSetup.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-core/src/test/java/com/yahoo/elide/core/datastore/inmemory/InMemoryStoreTransactionTest.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialectTest.java
- elide-core/src/test/java/com/yahoo/elide/core/utils/ClassScannerTest.java
- elide-core/src/test/java/example/Company.java
- elide-core/src/test/java/example/Parent.java
- elide-datastore/elide-datastore-hibernate3/src/test/java/com/yahoo/elide/datastores/hibernate3/HibernateDataStoreHarness.java
- elide-datastore/elide-datastore-hibernate3/src/test/java/example/AddressFragment.java
- elide-datastore/elide-datastore-hibernate5/src/test/java/com/yahoo/elide/datastores/hibernate5/HibernateDataStoreHarness.java
- elide-datastore/elide-datastore-hibernate5/src/test/java/com/yahoo/elide/datastores/hibernate5/HibernateEntityManagerDataStoreHarness.java
- elide-datastore/elide-datastore-hibernate5/src/test/java/example/AddressFragment.java
- elide-datastore/elide-datastore-jpa/src/test/java/com/yahoo/elide/datastores/jpa/JpaDataStoreHarness.java
- elide-datastore/elide-datastore-jpa/src/test/java/example/AddressFragment.java
- elide-integration-tests/src/test/java/com/yahoo/elide/initialization/InMemoryDataStoreHarness.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/ResourceIT.java
- elide-integration-tests/src/test/java/example/Address.java
- elide-integration-tests/src/test/java/example/Company.java
> Issue 2277

- elide-datastore/elide-datastore-jms/src/main/java/com/yahoo/elide/datastores/jms/websocket/SubscriptionWebSocketConfigurator.java
- elide-datastore/elide-datastore-jms/src/main/java/com/yahoo/elide/datastores/jms/websocket/SubscriptionWebSocketTestClient.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/subscriptions/websocket/RequestHandler.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/subscriptions/websocket/SessionHandler.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/subscriptions/websocket/SubscriptionWebSocket.java
- elide-spring/elide-spring-boot-autoconfigure/pom.xml
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideSubscriptionConfiguration.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/SubscriptionProperties.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/resources/application.yaml
- elide-standalone/pom.xml
- elide-standalone/src/main/java/com/yahoo/elide/standalone/ElideStandalone.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideResourceConfig.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideStandaloneSettings.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideStandaloneSubscriptionSettings.java
- elide-standalone/src/test/java/example/ElideStandaloneSubscriptionTest.java
- elide-standalone/src/test/java/example/ElideStandaloneTest.java
- elide-standalone/src/test/java/example/ElideStandaloneTestSettings.java
- elide-standalone/src/test/java/example/models/Post.java
> Phase 9: Elide standalone support for graphql subscriptions

- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
Adding a few additional tests around relationship updates.
> Added a few additional tests around updating relationships

- elide-async/src/main/java/com/yahoo/elide/async/operation/TableExportOperation.java
Resolves #2400 in Elide 5
Combines the export method in TableExportOperation with Call Method to make sure tx.flush is called in the end of the processing.
See #2400 
test cases pass after enabling scrollable iterator
> [Elide-5] Resolve ResultSet Closed Error for Paginated TableExports 

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceNoopUpdateTest.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/ResourceIT.java
- elide-integration-tests/src/test/java/example/CreateButNoUpdate.java
> Elide 5 issue147

- elide-core/src/main/java/com/yahoo/elide/jsonapi/extensions/JsonApiPatch.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/ResourceIT.java
- elide-integration-tests/src/test/resources/ResourceIT/invalidPatchMissingPath.req.json
Resolves #137
New IT test - patch extension request with missing path.
> Fixing #137

- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/AggregationDataStoreIntegrationTest.java
> Fixes #2438

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/EntityHydrator.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/AggregationDataStoreIntegrationTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/EntityHydratorTest.java
- elide-datastore/elide-datastore-aggregation/src/test/resources/configs/models/tables/SalesView.hjson
- elide-datastore/elide-datastore-aggregation/src/test/resources/prepare_SalesDB_tables.sql
- elide-integration-tests/src/test/java/com/yahoo/elide/initialization/GraphQLIntegrationTest.java
- elide-test/src/main/java/com/yahoo/elide/test/graphql/elements/Field.java
> Resolves #2447

- elide-async/pom.xml
- pom.xml
Update jersey
Code quality
Unit testing
> jersey to 2.35

- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideSubscriptionScanningConfiguration.java
> Disabling subscription scanning through application yaml in Spring.

- elide-async/pom.xml
- elide-datastore/elide-datastore-aggregation/pom.xml
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/cache/RedisCache.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/QueryResult.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/cache/RedisCacheTest.java
- pom.xml
Redis Cache based Cache implementation for Aggregation Store
Connect to Redis for caching
New Test Cases
> Redis Cache for Aggregation Store

- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/controllers/JsonApiController.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/Update200StatusTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/Update200StatusTestSetup.java
> Resolves #2784

- elide-datastore/elide-datastore-jpql/src/main/java/com/yahoo/elide/datastores/jpql/query/SubCollectionFetchQueryBuilder.java
- elide-datastore/elide-datastore-jpql/src/test/java/com/yahoo/elide/datastores/hibernate/hql/SubCollectionFetchQueryBuilderTest.java
Resolves #2858 
Applies distinct to queries with to many relationships in the `SubCollectionFetchQueryBuilder`.
Adds test cases to `SubCollectionFetchQueryBuilderTest`.
> fix: apply distinct for to many filter in SubCollectionFetchQueryBuilder

- elide-core/src/main/java/com/yahoo/elide/core/utils/coerce/converters/Serde.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/controllers/JsonApiController.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/ControllerTest.java
> Fixes #2789

- elide-core/src/main/java/com/yahoo/elide/jsonapi/models/Relationship.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
> Resolving #558

- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/controllers/JsonApiController.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/ControllerTest.java
Resolves #2789 on elide-6.x branch
> Fixes #2789 for Elide 6

- elide-async/src/main/java/com/yahoo/elide/async/service/AsyncExecutorService.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLEndpoint.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/QueryRunner.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/QueryRunners.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/PersistentResourceFetcherTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java
Resolves #2912
Adds Spring Boot bean for a DataFetcherExceptionHandler to customize error handling.
> Fixes #2912

- elide-graphql/src/main/resources/META-INF/native-image/com.yahoo.elide/elide-graphql/reflect-config.json
> Adding missing classes to reflect-config.json for graphql

- translations/zh/README.md
Resolves https://github.com/yahoo/elide/issues/1941
Update [top-README Mandarin translation](https://github.com/yahoo/elide/blob/master/translations/zh/README.md). 
Our team is using Elide and we absolutely love it. By keeping Chinese translation up-to-date, not only does it make Elide better, but it also helps our team's onboarding and information sharing
https://github.com/paion-data/elide/blob/translate-readme/translations/zh/README.md
> Translate readme into Chinese

- elide-core/src/main/java/com/yahoo/elide/jsonapi/JsonApi.java
Resolves #3101
See #3101
Not yet
> Closes #3101 JsonApi.patch NullPointerException when missing headers

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/audit/LogMessage.java
- elide-core/src/main/java/com/yahoo/elide/core/dictionary/EntityBinding.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/expression/FilterPredicatePushdownExtractor.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/expression/InMemoryExecutionVerifier.java
- elide-core/src/main/java/com/yahoo/elide/core/security/permissions/PermissionExpressionBuilder.java
- elide-core/src/main/java/com/yahoo/elide/core/type/AccessibleObject.java
- elide-core/src/main/java/com/yahoo/elide/core/utils/TypeHelper.java
- elide-core/src/main/java/com/yahoo/elide/core/utils/coerce/CoerceUtil.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/parser/JsonApiParser.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/dialect/MultipleFilterDialectTest.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialectTest.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialectWithFIQLCompliantStrategyTest.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/expression/ExpressionScopingVisitorTest.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/expression/FilterPredicateExtractionVisitorTest.java
- elide-core/src/test/java/example/ComputedBean.java
- elide-core/src/test/java/example/models/packageinfo/excluded/ExcludedSubPackage.java
- elide-core/src/test/java/example/models/packageinfo/included/ExcludedBySuperClass.java
- elide-core/src/test/java/example/models/packageinfo/included/IncludedSubPackage.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/Queryable.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/annotation/FromSubquery.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/NoCacheAggregationDataStoreIntegrationTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/QueryEngineTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/example/tables/OrderDetailsMaker.java
- elide-integration-tests/src/test/java/example/Child4Parent5Check.java
- elide-integration-tests/src/test/java/example/CreateButNoRead.java
- elide-integration-tests/src/test/java/example/CreateButNoReadChild.java
- elide-integration-tests/src/test/java/example/User.java
Closes #1885, closes #1889, closes #1891 
> Fix javadoc warnings

- elide-integration-tests/src/test/java/com/yahoo/elide/async/integration/tests/AsyncDelayStoreTransaction.java
- elide-integration-tests/src/test/java/com/yahoo/elide/core/utils/JsonParser.java
- elide-integration-tests/src/test/java/com/yahoo/elide/fieldLevelTest/FieldLevelParentClassIdIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/inheritance/InheritanceIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/initialization/GraphQLIntegrationTest.java
- elide-integration-tests/src/test/java/com/yahoo/elide/initialization/IntegrationTest.java
- elide-integration-tests/src/test/java/com/yahoo/elide/initialization/VerboseErrorResponsesTestBinder.java
- elide-integration-tests/src/test/java/com/yahoo/elide/targetEntity/TargetEntityIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/GraphQLIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/PaginateIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/ResourceIT.java
- elide-integration-tests/src/test/java/example/AnotherFilterExpressionCheckObj.java
- elide-integration-tests/src/test/java/example/Child.java
- elide-integration-tests/src/test/java/example/Editor.java
- elide-integration-tests/src/test/java/example/FieldLevelChildEntity.java
- elide-integration-tests/src/test/java/example/FieldLevelParentSuperclass.java
- elide-integration-tests/src/test/java/example/FilterExpressionCheckObj.java
- elide-integration-tests/src/test/java/example/Filtered.java
- elide-integration-tests/src/test/java/example/Generate.java
- elide-integration-tests/src/test/java/example/embeddedid/Address.java
- elide-integration-tests/src/test/java/example/models/triggers/Invoice.java
- elide-integration-tests/src/test/java/example/models/versioned/BookV2.java
> Fix elide-integration-tests build warnings

- README.md
Removed broken links and point to v7 docs.
> Update readme to remove broken links and point to v7 docs

- pom.xml
> Bumping redis server

- pom.xml
> Revert "Bumping redis server"

- screwdriver.yaml
> Changing build image to incldue open ssl

- pom.xml
> Revert "Revert "Bumping redis server""

- screwdriver.yaml
> Fixing missing openssl3 library

- screwdriver.yaml
> Reverting screwdriver changes.

- pom.xml
- screwdriver/scripts/publish.sh
> Fixing publish step

- screwdriver/scripts/publish.sh
Fix openssl decrypt in publish step.
> Updating openssl decrypt in publish.sh
