- .gitignore
- elide-core/pom.xml
- elide-integration-tests/pom.xml
- pom.xml
- Fix build warnings
- Project encoding
- Duplicate dependencies (commons-collections4, jackson-datatype-hibernate3)
- Removed unused properties
- Grouped dependency scopes
- Cleaned up extraneous comments
> PomCleanup

- elide-dbmanager/elide-dbmanager-inmemorydb/pom.xml
Database managers should include the appropriate data binders for jackson. In the case of in-memory DB, nothing special is required. However, for other DB managers such as hibernate, there are special data binders.
> Added jackson databinder to in memory db.

- README.md
We should wait until our bintray has been integrated to jcenter before merging this in (so that it is mirrored on maven central). However, I have confirmed these artifacts work by pointing to our bintray repo.
> Added instructions on adding elide to pom.xml.

- elide-dbmanager/elide-dbmanager-hibernate3/src/test/java/com/yahoo/elide/dbmanagers/hibernate3/HibernateManagerTest.java
- Fixed the test directory location for Hibernate 3 database manager (move src/main/test to src/test)
- Add license & newline
> Fix test dir for hibernate3

- .travis.yml
- travis/settings.xml
This reverts the changes to use DPL to deploy to bintray. Cutting a release still requires running `mvn -B release:prepare` locally to kick off the build process.
> Revert DPL provider till bintray fixes headless user permissions

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
Found a somewhat obvious bug in how I implemented the SharePermission check.  This is now fixed.
> Fixed security hole in shareable permission check

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/ResourceLineage.java
- elide-integration-tests/src/test/groovy/com/yahoo/elide/tests/ShareableIT.groovy
Fixes the problem when adding a child containing a relationship to the parent without a SharePermission.
> test for add unshared child with parent relationship

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
Removing a relationship from a collection should require only UpdatePermission on removed entity.
> Check UpdatePermission on remove relationship

- elide-core/src/main/java/com/yahoo/elide/audit/Logger.java
- elide-core/src/main/java/com/yahoo/elide/audit/Slf4jLogger.java
- elide-core/src/test/java/com/yahoo/elide/audit/LogMessageTest.java
- elide-core/src/test/java/com/yahoo/elide/audit/TestLogger.java
Changed abstract Logger global message collection to ThreadLocal.  
Added tests to validate thread safety.
> Test thread safety of Slf4jLogger

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-core/src/test/java/example/Left.java
- elide-core/src/test/java/example/Right.java
- elide-integration-tests/src/test/java/example/Left.java
We now do a field level check when we are removing objects from inverse relationships,
rather than requiring the user to have the ability to modify the related object wholesale.
> Allow removal of objects from relationships without general update permission

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-core/src/test/java/example/FunWithPermissions.java
Move `isDeny` filter check ahead of the `getValue` to avoid unneccessiarily  hydrating a lazy collection
> Avoid accessing lazy relationship collection if entity is denied.

- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/models/Relationship.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/serialization/DataDeserializer.java
Allow caller to provide the JSON API Mapper.
Use convertValue instead of deserialize-reserialize of the JsonNode.
> Faster Serializer/Deserializer for JSON API

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/document/processors/IncludedProcessor.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/CollectionTerminalState.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/RecordState.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/StartState.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/ExpressionResult.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/ImmediateCheckExpression.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/OrExpression.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
This PR allows for retrieving values **without** checking read permissions *as long as* that value is never returned to the user.
> Removed required read checks for updates.

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/main/java/com/yahoo/elide/security/PermissionExecutor.java
auth failure logging was lost in 2.0 conversion
> Reintroduce the requestScope.logAuthFailure

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/ResourceIT.java
- elide-integration-tests/src/test/java/example/CreateButNoUpdate.java
- elide-integration-tests/src/test/resources/ResourceIT/createButNoUpdate.bad.req.json
- elide-integration-tests/src/test/resources/ResourceIT/createButNoUpdate.req.json
- elide-integration-tests/src/test/resources/ResourceIT/createButNoUpdate.resp.json
- elide-integration-tests/src/test/resources/ResourceIT/createButNoUpdate.update.req.json
For any sort of creation request, update checks _must_ be deferred.
> Defer update on create

- README.md
- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/Predicate.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/filter/CriteriaExplorer.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/filter/CriterionFilterOperation.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/filter/CriteriaExplorer.java
- elide-integration-tests/src/test/groovy/com/yahoo/elide/tests/FilterIT.groovy
- elide-integration-tests/src/test/java/example/Book.java
- elide-integration-tests/src/test/java/example/Chapter.java
This allows filtering. To filter collections, traverse a path relative to the parent. For instance,
`/parent?include=[children]&filter[parent.children.id]=4`
will give all parents that have child id 4.
`/parent?include[children]&filter[child.id]=4`
will provide all parents and include a child with id 4.
This allows us to continue to honor existing behavior while providing greater flexibility in filtering at the collection level.
> Relationship filtering

- elide-core/src/main/java/com/yahoo/elide/core/EntityPermissions.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/AndExpression.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/Expression.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/OrExpression.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-core/src/test/java/nocreate/NoCreateEntity.java
- elide-core/src/test/java/nocreate/package-info.java
The ExpressionBuilder was asking only the class for annotations instead of using EntityDictionary lookup.
> Corrected annotation lookup in ExpressionBuilder

- elide-contrib/dropwizard-elide/src/main/java/com/yahoo/elide/contrib/dropwizard/elide/ElideBundle.java
- elide-contrib/dropwizard-elide/src/main/java/com/yahoo/elide/contrib/dropwizard/elide/ElideConfiguration.java
- elide-contrib/dropwizard-elide/src/test/java/com/yahoo/elide/contrib/dropwizard/elide/ElideBundleTest.java
Extend the dropwizard-bundle with more hooks to override `EntityDictionary`, `JsonApiMapper` and `PermissionExecutor`
> More hooks in the Dropwizard Bundle

- elide-core/src/main/java/com/yahoo/elide/core/CheckInstantiator.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityPermissions.java
Received 10x speed increase for a test query.  
Remaining overhead is in `com.yahoo.elide.security.executors.ActivePermissionExecutor.checkPermission`
> Cache result of check.forName for improved performance

- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate3/src/test/java/com/yahoo/elide/tests/DataStoreIT.java
Disabled any JOIN by default due to cross-product expansion of many queries.
> Use Criteria.DISTINCT_ROOT_ENTITY and disable join by default

- elide-core/src/main/java/com/yahoo/elide/core/EntityPermissions.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/PermissionExpressionBuilder.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/ImmediateCheckExpression.java
Now caches UserCheck results once for user instead of per resource.
Reduced EntityPermissions maps.
> Improve CheckExpression performance

- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/extensions/PatchRequestScope.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/RecordState.java
- elide-core/src/main/java/com/yahoo/elide/security/executors/VerbosePermissionExecutor.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/AnyFieldExpression.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/ImmediateCheckExpression.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/NotExpression.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/OrExpression.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/SpecificFieldExpression.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/ResourceIT.java
- elide-integration-tests/src/test/java/example/CreateButNoRead.java
- elide-integration-tests/src/test/java/example/CreateButNoReadChild.java
- elide-integration-tests/src/test/resources/ResourceIT/testPatchDeferredOnCreate.json
- elide-integration-tests/src/test/resources/ResourceIT/testPatchDeferredOnCreate.req.json
@DeathByTape Added a test to reproduce the post-processing read collection on create problem.
> Avoid read on create

- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/RecordTerminalState.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/ResourceIT.java
Elide Patch was returning a body of `null` for HTTP 204 responses.
> HTTP 204 must not return a body.

- elide-annotations/src/main/java/com/yahoo/elide/annotation/ComputedRelationship.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityBinding.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
Have a `@ComputedRelationship` annotation that resembles the `@ComputedAttribute` except that the results of annotated field/method will show up in `relationships` section instead of `attributes` in JSON response.
> ComputedRelationship Annotation

- elide-core/src/main/java/com/yahoo/elide/core/DataStoreTransaction.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java
Reverting https://github.com/yahoo/elide/pull/250/commits/d2fb23ee4f4db3d2b3aa78723e9d0a353d9fa7a5
We don't want to totally deprecate `filterCollection` in elide-2.0 per discussion with @aklish
> Revert total deprecating of filterCollection

- elide-core/src/main/java/com/yahoo/elide/core/DataStoreTransaction.java
- elide-datastore/elide-datastore-multiplex/src/main/java/com/yahoo/elide/datastores/multiplex/MultiplexTransaction.java
- elide-datastore/elide-datastore-multiplex/src/main/java/com/yahoo/elide/datastores/multiplex/MultiplexWriteTransaction.java
When pagination was called the filter was lost in Multiplex transactions.
> Default loadObjectsWithSortingAndPagination calls correct loadObjects

- elide-annotations/src/main/java/com/yahoo/elide/annotation/Paginate.java
- elide-core/src/main/java/com/yahoo/elide/core/DataStoreTransaction.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/pagination/Pagination.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/models/KeyValMap.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/models/Meta.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/CollectionTerminalState.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java
- elide-integration-tests/src/test/groovy/com/yahoo/elide/tests/PaginateIT.groovy
- elide-integration-tests/src/test/java/example/EntityWithPaginateCountableFalse.java
- elide-integration-tests/src/test/java/example/EntityWithPaginateDefaultLimit.java
- elide-integration-tests/src/test/java/example/EntityWithPaginateMaxLimit.java
- elide-integration-tests/src/test/java/example/EntityWithoutPaginate.java
For enhancement proposal https://github.com/yahoo/elide/issues/264.
The page meta data will be returned in the JSON-API response if the page size/limit/number/offset query parameters have been specified.
If the query parameter "page[totals]=true" is also specified, the page totals will be determined and included in the returned page meta data.
> Add support for page totals and JSON-API page meta data

- elide-core/src/main/java/com/yahoo/elide/core/DataStoreTransaction.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/Predicate.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/expression/AndFilterExpression.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/expression/NotFilterExpression.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/expression/OrFilterExpression.java
- elide-core/src/main/java/com/yahoo/elide/parsers/expression/FilterExpressionCheckEvaluationVisitor.java
- elide-core/src/main/java/com/yahoo/elide/parsers/expression/PermissionToFilterExpressionVisitor.java
- elide-core/src/main/java/com/yahoo/elide/security/FilterExpressionCheck.java
- elide-core/src/main/java/com/yahoo/elide/security/PermissionExecutor.java
- elide-core/src/main/java/com/yahoo/elide/security/executors/ActivePermissionExecutor.java
- elide-core/src/main/java/com/yahoo/elide/security/executors/BypassPermissionExecutor.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/PermissionExpressionBuilder.java
- elide-core/src/test/java/com/yahoo/elide/core/LifeCycleTest.java
- elide-core/src/test/java/com/yahoo/elide/parsers/expression/PermissionToFilterExpressionVisitorTest.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/ResourceIT.java
- elide-integration-tests/src/test/java/example/AnotherFilterExpressionCheckObj.java
- elide-integration-tests/src/test/java/example/FilterExpressionCheckObj.java
- elide-integration-tests/src/test/resources/ResourceIT/createAnotherFilterExpressionCheckObj.json
- elide-integration-tests/src/test/resources/ResourceIT/createFilterExpressionCheckObj.1.json
- elide-integration-tests/src/test/resources/ResourceIT/createFilterExpressionCheckObj.2.json
- elide-integration-tests/src/test/resources/ResourceIT/createFilterExpressionCheckObj.3.json
This PR allows merging permission restriction(especially ReadPermission)  to `FilterExpression` which transfer the workload of checking permission from elide layer to datastore layer. 
Finished: implemented the corresponding check interface and AST visitor. 
integrating the check in datastore query building process.
> Adding FilterExpressionCheck support. 

- elide-core/src/main/java/com/yahoo/elide/parsers/expression/PermissionToFilterExpressionVisitor.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/PermissionExpressionBuilder.java
- elide-core/src/test/java/com/yahoo/elide/parsers/expression/PermissionToFilterExpressionVisitorTest.java
- elide-integration-tests/src/test/java/example/FilterExpressionCheckObj.java
Support FilterExpressionCheck "OR" with UserCheck.  If UserCheck evaluate to true, ignore FilterExpression, otherwise push FilterExpression to datastore.
> Fix problems when FilterExpressionCheck OR UserCheck

- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/filter/CriterionFilterOperation.java
I'm using elide with hibernate datastore as backend for my ember-cli application and I stuck with one problem related to ember-data. By default ember-data uses dasherized resource names (like `my-very-own-resource`) and those names work well with elide by using `@Include(rootLevel = true, type = "my-very-own-resource")` annotation to resource class.
Unfortunately when I try to filter using basic syntax I have a problem with dasherized resource names. Filters like `/storage-items?filter[storage-items.manufacturer.id]=1` generate invalid SQL queries which contain table aliases like `storage-it1` and so on.
This pull request replaces dash sign in generated table aliases to underscore to make aliases valid database identifiers.
> Allow to use dasherized resource names in filter expressions

- elide-core/src/main/java/com/yahoo/elide/jsonapi/JsonApiMapper.java
This should make it more obvious on how to add custom (de)serializers to elide. Rather than requiring `jsonApiMapper.getMapper().registerModule(...)` or similar, you can now pass in your own pre-constructed `ObjectMapper` for Elide to use.
> Added additional constructor for json api mapper.

- elide-datastore/pom.xml
Not sure if it's just me, but I got this error from jcabi on my laptop when building elide:
`The socket file path is too long (> 103): /Users/xiaoyaoqian/projects/elide/elide-datastore/elide-datastore-hibernate5/target/mysql-data/mysql.sock`
So I made this change to avoid it. Thought it might be helpful for others.
> Avoid jcabi Mysql complaining too long socket path

- elide-core/src/main/java/com/yahoo/elide/resources/JsonApiEndpoint.java
- elide-example/elide-blog-example-resteasy/README.md
- elide-example/elide-blog-example-resteasy/pom.xml
- elide-example/elide-blog-example-resteasy/src/main/java/com/yahoo/elide/example/persistence/ElideResourceConfig.java
- elide-example/elide-blog-example-resteasy/src/main/java/com/yahoo/elide/example/persistence/Main.java
- elide-example/elide-blog-example-resteasy/src/main/java/com/yahoo/elide/example/persistence/models/Comment.java
- elide-example/elide-blog-example-resteasy/src/main/java/com/yahoo/elide/example/persistence/models/Post.java
- elide-example/elide-blog-example-resteasy/src/main/java/com/yahoo/elide/example/persistence/models/Role.java
- elide-example/elide-blog-example-resteasy/src/main/java/com/yahoo/elide/example/persistence/models/User.java
- elide-example/elide-blog-example-resteasy/src/main/resources/META-INF/persistence.xml
- elide-example/elide-blog-example-resteasy/src/main/resources/log4j2.xml
- elide-example/elide-blog-example-resteasy/src/main/scripts/load_blog.sh
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/ResourceIT.java
Should fix issue described in https://github.com/yahoo/elide/issues/321 and allow HTTP DELETE requests without body and content-type header when using JsonApiEndpoint in JAX-RS environment
> JsonApiEndpoint: Allow delete resource requests without body and content-type header

- elide-core/src/main/java/com/yahoo/elide/utils/coerce/CoerceUtil.java
- elide-core/src/main/java/com/yahoo/elide/utils/coerce/converters/EpochToDateConverter.java
- elide-core/src/test/java/com/yahoo/elide/utils/coerce/CoerceUtilTest.java
Fixes bug #328 by the simpliest available way
> Fix date coercion for non-long numeric types

- elide-core/src/main/java/com/yahoo/elide/parsers/expression/PermissionToFilterExpressionVisitor.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HQLTransaction.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HQLTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java
- elide-datastore/elide-datastore-multiplex/src/main/java/com/yahoo/elide/datastores/multiplex/MultiplexWriteTransaction.java
Will process OR and AND shortcuts when building the filterexpression so 
`where id = 1 and (false)` evaluates to `false` which immediately fails
> Short circuit OR and AND filter expressions

- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java
To allow subclasses of `HibernateTransaction` to override the `buildCriterionFilterOperation`
> Expose buildCriterionFilterOperation to make overridable

- .travis.yml
- elide-integration-tests/src/test/resources/hibernate.cfg.xml
Turn on maven `--quiet` mode.  Logs currently exceed the 4MB allowed.
> Reduce build output

- elide-datastore/elide-datastore-inmemorydb/src/main/java/com/yahoo/elide/datastores/inmemory/InMemoryTransaction.java
- elide-datastore/elide-datastore-inmemorydb/src/test/java/com/yahoo/elide/datastores/inmemory/InMemoryDataStoreTest.java
- elide-datastore/elide-datastore-inmemorydb/src/test/java/com/yahoo/elide/example/beans/FirstBean.java
- elide-datastore/elide-datastore-multiplex/src/test/java/com/yahoo/elide/datastores/multiplex/MultiplexManagerTest.java
- elide-datastore/elide-datastore-multiplex/src/test/java/com/yahoo/elide/example/beans/FirstBean.java
This change makes it possible to first add an entry without a generated id,
and then later to generate one. Before this, an NPE would be thrown
at the second step. It also somewhat decreases the risk of ID collision
when combining generated and user-specified IDs.
> fix NPE in InMemoryDataStore

- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
Deprecated a number of old RequestScope constructors and fixed the Elide 2.0 instantiations.  This had been effectively disabling FilterExpression use in Elide 2.
There may still be a problem in Elide 2 where `any` will instead processes as `all` when FilterExpressions are used but not enabled.  So be sure to enable filter expressions.  This problem will go away entirely in Elide 3.
> Enable filter expressions in Elide 2 RequestScope

- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/extensions/PatchRequestScope.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java
Expands on https://github.com/yahoo/elide/pull/354
Handles RequestScopedTransaction in 3.0 and with filter expressions in 2.0
> Enable filter expression handling in 3.0 patch extension

- elide-core/src/main/java/com/yahoo/elide/core/filter/Predicate.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/filter/HQLFilterOperation.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/core/filter/HQLFilterOperationTest.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HQLTransaction.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HQLTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java
Found a problem where multiple Predicates for the same field attempted to use the same parameter name, causing a name collision.
Added Predicate.getParameterName to generate a unique name based on the predicate properties.
> Unique HQL parameter names

- elide-datastore/elide-datastore-multiplex/src/main/java/com/yahoo/elide/datastores/multiplex/MultiplexTransaction.java
- elide-datastore/elide-datastore-multiplex/src/main/java/com/yahoo/elide/datastores/multiplex/MultiplexWriteTransaction.java
Multiplex Transaction was leaving orphaned child transactions on close.  Moved the clear to the correct location after `close`.
> Multiplex close

- elide-contrib/elide-swagger/pom.xml
- elide-contrib/elide-swagger/src/main/java/com/yahoo/elide/contrib/swagger/JsonApiModelResolver.java
- elide-contrib/elide-swagger/src/main/java/com/yahoo/elide/contrib/swagger/SwaggerBuilder.java
- elide-contrib/elide-swagger/src/main/java/com/yahoo/elide/contrib/swagger/resources/DocEndpoint.java
- elide-contrib/elide-swagger/src/test/java/com/yahoo/elide/contrib/swagger/SwaggerBuilderTest.java
- elide-contrib/elide-swagger/src/test/java/com/yahoo/elide/contrib/swagger/SwaggerIT.java
- elide-contrib/elide-swagger/src/test/java/com/yahoo/elide/contrib/swagger/SwaggerResourceConfig.java
- elide-contrib/elide-swagger/src/test/java/com/yahoo/elide/contrib/swagger/models/Publisher.java
A number of fixes:
- The model resolver now correctly handles Elide entities that were attributes.
- Aggressively prune redundant paths.
- Allow options to generate docs for subgraphs of the entity model.
- Allow options to limit the filtering operators for each GET 
- The JAXRS resource now supports serving multiple swagger documents.
> Update swagger code to support large and complex entity graphs.

- elide-core/src/main/java/com/yahoo/elide/core/DataStoreTransaction.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityBinding.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/InMemoryFilterOperation.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/Operator.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/Predicate.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/expression/InMemoryFilterVisitor.java
- elide-core/src/main/java/com/yahoo/elide/security/FilterExpressionCheck.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/OperatorTest.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/expression/InMemoryFilterVisitorTest.java
- elide-core/src/test/java/example/ComputedBean.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java
- elide-datastore/elide-datastore-inmemorydb/src/main/java/com/yahoo/elide/datastores/inmemory/InMemoryTransaction.java
- elide-datastore/elide-datastore-noop/pom.xml
- elide-datastore/elide-datastore-noop/src/main/java/com/yahoo/elide/datastores/noop/NoopTransaction.java
- elide-datastore/elide-datastore-noop/src/test/java/com/yahoo/elide/beans/NoopBean.java
- elide-datastore/elide-datastore-noop/src/test/java/com/yahoo/elide/datastores/noop/NoopTransactionTest.java
This PR offers support for performing object-level reads in the noop store. Moreover, it enables `@ComputedAttribute`'s and `@ComputedRelationship`'s to accept a `RequestScope` as a parameter.
> Support object-level reads through Noop Store and RequestScope params for Computed Fields

- elide-example/elide-blog-example/pom.xml
- elide-example/elide-hibernate3-mysql-example/pom.xml
- elide-example/elide-persistence-mysql-example/pom.xml
Jersey container is now pulling version 2.26-b02 as RELEASE, and it is causing "java.lang.ClassNotFoundException: javax.ws.rs.client.RxInvokerProvider" with that version. We should pin to last good version.
- Pin jersey container to version 2.25.1 for example projects.
> Pin jersey container version for example projects

- elide-core/src/main/java/com/yahoo/elide/Elide.java
The methods for handling request were all pretty similar so I consolidated the logic so we're less prone to forget to change one of them.
> Commonize the request handling in Elide

- changelog.md
- elide-core/pom.xml
- elide-core/src/main/java/com/yahoo/elide/core/DataStoreTransaction.java
- elide-core/src/main/java/com/yahoo/elide/core/datastore/inmemory/InMemoryDataStore.java
- elide-core/src/main/java/com/yahoo/elide/core/datastore/inmemory/InMemoryTransaction.java
- elide-core/src/main/java/com/yahoo/elide/core/datastore/inmemory/Operation.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/Operator.java
- elide-datastore/elide-datastore-inmemorydb/pom.xml
- elide-datastore/elide-datastore-inmemorydb/src/main/java/com/yahoo/elide/datastores/inmemory/InMemoryDataStore.java
- elide-datastore/elide-datastore-inmemorydb/src/main/java/com/yahoo/elide/datastores/inmemory/InMemoryTransaction.java
Tests have not been moved at this time.
Also, I'm pretty sure that our *reference implementation* is much more bare-bones than we had intended. For instance, we don't support rolling back transactions since we give the real backing object out to the `PersistentResource` and don't track the modifications that occur to it.
> Move the in-memory store to elide-core

- elide-core/src/main/antlr4/com/yahoo/elide/generated/parsers/Core.g4
- elide-core/src/main/antlr4/com/yahoo/elide/generated/parsers/Expression.g4
- elide-core/src/main/java/com/yahoo/elide/core/EntityBinding.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/datastore/inmemory/InMemoryTransaction.java
- elide-core/src/main/java/com/yahoo/elide/core/exceptions/ForbiddenAccessException.java
- elide-core/src/main/java/com/yahoo/elide/core/exceptions/HttpStatusException.java
- elide-core/src/main/java/com/yahoo/elide/core/exceptions/InternalServerErrorException.java
- elide-core/src/main/java/com/yahoo/elide/core/exceptions/InvalidValueException.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/FilterPredicate.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/dialect/DefaultFilterDialect.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/dialect/MultipleFilterDialect.java
- elide-core/src/test/java/com/yahoo/elide/audit/LogMessageTest.java
- elide-core/src/test/java/com/yahoo/elide/core/LifeCycleTest.java
- elide-core/src/test/java/com/yahoo/elide/parsers/expression/PermissionToFilterExpressionVisitorTest.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/filter/HQLFilterOperation.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/filter/CriterionFilterOperation.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/filter/CriterionFilterOperation.java
- elide-datastore/elide-datastore-hibernate5/src/test/java/com/yahoo/elide/tests/DataStoreIT.java
- elide-datastore/elide-datastore-multiplex/src/test/java/com/yahoo/elide/datastores/multiplex/MultiplexManagerTest.java
- elide-datastore/elide-datastore-multiplex/src/test/java/com/yahoo/elide/datastores/multiplex/bridgeable/BridgeableRedisStore.java
Avoid `Class.getSimpleName()` in FilterExpression by loading the correct alias when needed. 
Made a few runtime improvements, and some other code cleanup as well.
> Improved Filter performance

- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/core/exceptions/InternalServerErrorException.java
While attempting to handle a custom exception that currently generates 500, I found it was not possible by over-riding `buildErrorResponse`.
Even an "unknown" exception should be converted into a 500 so the application can handle it correctly.
> Allow application to process the uncaught exceptions.

- elide-annotations/src/main/java/com/yahoo/elide/security/checks/prefab/Common.java
We are adding a new generic check which denies any mutation that sets a field value to anything other than null. 
We were facing an issue where we couldn't remove a child entity from a relationship with a parent, when the field in the child was marked as UpdateOnlyOnCreate. We needed some permission which prevents the sharing of the child entity with a different parent but at the same time allows the removal of the child from the relationship with the parent.
We couldn't solve the above case by placing a @SharePermission check. In the case where we make a POST request on the child entity, setting the relationship to a different parent, the share permissions were not coming into effect. So we needed to add a new permission which can be used on the child side of the relationship to allow …
> Adding prefabricated check

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/test/java/com/yahoo/elide/core/LifeCycleTest.java
- elide-core/src/test/java/example/Book.java
This fixes a bug in the lifecycle hooks. In short, when queuing an update hook, the general update hooks (i.e. `@OnUpdate*`) without a field does not get executed.
> Queue empty field hooks even when field is modified.

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/core/ObjectEntityCache.java
A patch extension that changes the hashCode or equals of the target object will be unable to find the previously stored new object in the `ObjectEntityCache`.
> Use IdentityHashMap

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/main/java/com/yahoo/elide/security/executors/ActivePermissionExecutor.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/ResourceIT.java
- elide-integration-tests/src/test/java/example/Child.java
- elide-integration-tests/src/test/java/example/TestCheckMappings.java
- elide-integration-tests/src/test/resources/ResourceIT/elideBypassSecurity.json
Not all FilterExpressionChecks are able to run in memory for newly created objects during a Patch Extension create.  This is an attempt to avoid the failure in filter for these newly created objects.
> Patch extension read permission

- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/AnyFieldExpression.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/CheckExpression.java
- elide-core/src/test/java/com/yahoo/elide/security/permissions/PermissionExpressionBuilderTest.java
The PR makes changes to the format of the debug string related to the permission evaluation that is returned in elide response. This helps in parsing the string in ralisplitter security testing framework easily.
> Changes to the permission evaluation

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
Fixed `Unknown Entity null` when passed an incorrect field name.
> Handle invalid relationship field name

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/security/executors/ActivePermissionExecutor.java
Found uncaught compile error where parameters were accidentally swapped.
This could cause extra unnecessary execution of commit checks when the results were already cached.  I am not sure why we have no compiler error.
> Fix parameter order

- elide-core/src/main/java/com/yahoo/elide/graphql/DeferredId.java
- elide-core/src/main/java/com/yahoo/elide/graphql/ModelBuilder.java
- elide-core/src/main/java/com/yahoo/elide/graphql/PersistentResourceFetcher.java
- elide-core/src/test/java/com/yahoo/elide/graphql/FetcherUpsertTest.java
This PR contains the code for lazy loading of the `id` field from `PersistentResource` by delayed jackson serialization. 
IIRC, we're now left with the following TODOs -   
- Pagination/filtering/sorting for `FETCH`.
- Passing filter expression to `getRelation()` to reduce number of sql queries while fetching a relationship.
- The actual `/graphql` endpoint. 
- A lot of IT/unit tests.
> Add deferred ID

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/main/java/com/yahoo/elide/graphql/PersistentResourceFetcher.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/document/processors/IncludedProcessor.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/CollectionTerminalState.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/RecordState.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/StartState.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-core/src/test/java/com/yahoo/elide/graphql/FetcherUpsertTest.java
This PR opens up loadRecords and getRelation allowing the passing of filters, sorting, and pagination params.
Another PR is needed to refactor RequestScope (this is not needed for functionality but for code organization).
> Refactor persistent resource for graphQL

- changelog.md
- elide-example/elide-blog-example/pom.xml
Latest jersey requires we now include `jersey-hk2`. See: https://github.com/jersey/jersey/issues/3584
> Add newly required dependency for example blog.

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/core/filter/FilterPredicate.java
- elide-core/src/main/java/com/yahoo/elide/core/pagination/Pagination.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/AbstractHQLQueryBuilder.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/RootCollectionFetchQueryBuilder.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/RootCollectionPageTotalsQueryBuilder.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/SubCollectionPageTotalsQueryBuilder.java
We found a problem when the HQL Builder was used with a Hibernate proxy bean.  The `bean.getClass()` should be passed through the dictionary lookup Entity class.
Also fixed a couple string concats with StringBuilder for improved performance.
> Properly handle proxy beans in HQL Builder

- changelog.md
- elide-annotations/src/main/java/com/yahoo/elide/annotation/MappedInterface.java
- elide-annotations/src/main/java/com/yahoo/elide/annotation/ToMany.java
- elide-annotations/src/main/java/com/yahoo/elide/annotation/ToOne.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityBinding.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/RecordState.java
- elide-core/src/test/java/com/yahoo/elide/core/EntityDictionaryTest.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/AnyPolymorphismIT.java
- elide-integration-tests/src/test/java/example/Device.java
- elide-integration-tests/src/test/java/example/Property.java
- elide-integration-tests/src/test/java/example/Smartphone.java
- elide-integration-tests/src/test/java/example/Tractor.java
- elide-integration-tests/src/test/resources/AnyPolymorphismIT/AddSmartphoneProperty.json
- elide-integration-tests/src/test/resources/AnyPolymorphismIT/AddTractorProperty.json
The main use case here is allowing for hibernate's `@Any` annotation.
This allows for polymorphic relationship to unrelated models.
Elide gave me two challenges.
1.) Needed annotations outside of JPA so Elide recognized them as relationships
2.) Needed the EntityDictionary to allow Interfaces (+2 squashed commits)
Squashed commits:
> Allow for arbitrary relationships that aren't transitive.

- elide-annotations/src/main/java/com/yahoo/elide/annotation/CreatePermission.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/security/executors/ActivePermissionExecutor.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistenceResourceTestSetup.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-core/src/test/java/com/yahoo/elide/core/UpdateOnCreateTest.java
- elide-core/src/test/java/example/TestCheckMappings.java
- elide-core/src/test/java/example/UpdateAndCreate.java
- elide-core/src/test/java/example/UserIdChecks.java
- elide-integration-tests/src/test/java/example/CreateButNoUpdate.java
This PR is an update to a previous PR https://github.com/yahoo/elide/pull/544
It was closed as I tried to rename the branch
The changes include the following:
1. Changed PersistenceResource and ActivePermissionExecutor to support the change
2. Added tests in for the same, with some refactoring as we couldn't add more tests to PersistenceResourceTests
> Allowing CreatePermissions to be specified on attributes and relations

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/core/EntityPermissions.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/test/java/com/yahoo/elide/core/LifeCycleTest.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
Uncaught exception caused Include to fail when not allowed.
By returning empty set, all the other allowed fields are returned instead of having to guess which are visible.
> Handle Forbidden for Include

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/core/EntityPermissions.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/document/processors/IncludedProcessor.java
- elide-core/src/test/java/com/yahoo/elide/core/LifeCycleTest.java
- elide-core/src/test/java/com/yahoo/elide/jsonapi/document/processors/IncludedProcessorTest.java
Limits the ForbiddenAccess handling to IncludeProcessor instead of returning empty set from getRelationship.
> Handle forbidden include

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/Elide.java
This adds additional logging around our exception handling. `debug` for "expected" exceptions and `error` for response codes which are more likely to be server-related issues.
> Add additional logging around caught exceptions.

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/test/java/com/yahoo/elide/core/LifeCycleTest.java
- elide-core/src/test/java/example/Book.java
- elide-core/src/test/java/example/TestCheckMappings.java
Restored lifecycle hook for create pre-security to occur after fields are populated.
Expanded test as well.
> Delay OnCreatePreSecurity until fields are populated.

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
This is required so we don't have collision errors when trying to traverse through newly created objects that belong to the same collection within a single transaction.
Example:
```
Create: /apps/1/players/abc
Create: /apps/1/players/def
Add: /apps/1/players/def/skills
```
In this example we are creating 2 new players in a game and adding skills to player `def`. Without this change, there is no way to guarantee we won't collide and try to add these skills to `abc`.
This seems to be a regression in Elide 4. I have the corresponding test addition to Elide 3 here: https://github.com/yahoo/elide/pull/597
> Filter getRelation call to single entity in-memory.

- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
Added this test in Elide 4. Confirmed that it is a regression and not an issue in Elide 3.
> Add test for single relation filtering.

- changelog.md
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLEndpoint.java
Currently we don't really have support for operation names-- this may ultimately become a feature in the future. However, clients such as apollo send this with a `null` value by default. We should treat a null value properly in our system.
> Ignore null operation names.

- changelog.md
- elide-core/pom.xml
- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/core/exceptions/InvalidConstraintException.java
This PR tweaks how we perform exception handling. Namely, we log generic `Exception`s but no longer swallow them. This allows the caller to make decisions on how to handle Exceptions which we do not support.
Moreover, I added support for handling the `ConstraintViolationException` thrown for JSR303 failures.
> Fix exception handling.

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
This PR fixes an issue where it's possible that a `null` `FilterExpression` is constructed. Namely, if no filter is passed in by the user and a permission filter exists, we end up creating the following filter expression:
```java
new AndFilterExpression(null, permissionFilter);
```
When this goes to evaluate, we try to operate on the `null` value causing an NPE. Rather than making the permission execution state machine null-safe, I have opted to make the change here. Namely, because security is a rather important component to our project, I would rather have hard crashes from developer mistakes rather than silent failures or-- worse-- invalid successes.
> Fix null filter expression issue.

- changelog.md
- elide-standalone/pom.xml
- elide-standalone/src/main/java/com/yahoo/elide/standalone/ElideStandalone.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideStandaloneSettings.java
This allows developers to enable GraphQL without any friction. If they don't want GraphQL included in their project, there is only one step:
_In their ElideStandaloneSettings_
```java
boolean enableGraphQL() {
return false;
}
```
That being said, this approach still will include the Elide graphql code. If they don't want any trace of GraphQL in their project, it's easy to exclude in their dependency management by simply excluding the `com.yahoo.elide:elide-graphql` transitive dependency that is brought in by `elide-standalone`.
> Update elide standalone to support GraphQL.

- changelog.md
- elide-datastore/elide-datastore-hibernate3/pom.xml
- elide-datastore/elide-datastore-hibernate3/src/test/java/example/Person.java
- elide-datastore/elide-datastore-hibernate5/pom.xml
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateStore.java
- elide-datastore/elide-datastore-hibernate5/src/test/java/example/Person.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/datastore/InjectionAwareHibernateStore.java
This is a proposed fix for https://github.com/yahoo/elide/issues/611. In short, with tools like envers hibernate can legitimately store non-entity types in its class metadata. As a result, we do not want to bind these objects in Elide. This allows us to first check if the class we're trying to bind is an entity. If it's not, we simply ignore the class otherwise we proceed as usual.
This is the fix for Elide 3.
> Ignore non-entity types in hibernate class metadata (elide 3.x)

- changelog.md
- elide-datastore/elide-datastore-hibernate3/pom.xml
- elide-datastore/elide-datastore-hibernate3/src/test/java/example/Person.java
- elide-datastore/elide-datastore-hibernate5/pom.xml
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/AbstractHibernateStore.java
- elide-datastore/elide-datastore-hibernate5/src/test/java/example/Person.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/datastore/InjectionAwareHibernateStore.java
This is a proposed fix for https://github.com/yahoo/elide/issues/611. In short, with tools like envers hibernate can legitimately store non-entity types in its class metadata. As a result, we do not want to bind these objects in Elide. This allows us to first check if the class we're trying to bind is an entity. If it's not, we simply ignore the class otherwise we proceed as usual.
> Ignore non-entity types in hibernate class metadata.

- changelog.md
- elide-annotations/pom.xml
- elide-contrib/elide-swagger/pom.xml
- elide-contrib/pom.xml
- elide-core/pom.xml
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/test/java/com/yahoo/elide/core/LifeCycleTest.java
- elide-datastore/elide-datastore-hibernate/pom.xml
- elide-datastore/elide-datastore-hibernate3/pom.xml
- elide-datastore/elide-datastore-hibernate5/pom.xml
- elide-datastore/elide-datastore-inmemorydb/pom.xml
- elide-datastore/elide-datastore-multiplex/pom.xml
- elide-datastore/elide-datastore-noop/pom.xml
- elide-datastore/pom.xml
- elide-example/elide-blog-example-resteasy/pom.xml
- elide-example/elide-blog-example/pom.xml
- elide-example/elide-hibernate3-mysql-example/pom.xml
- elide-example/pom.xml
- elide-graphql/pom.xml
- elide-integration-tests/pom.xml
- elide-standalone/pom.xml
- pom.xml
This changes when pre-security hooks run for commit-time checks. In general:
`OnCreatePreSecurity` actually runs before the security check is run but _after_ the values on the object are set. Since create checks are all deferred to commit-time to look at the final state of the object, this allows the `PreSecurity` hooks to be useful for creates. If we don't do this, the object is totally empty at time of `PreSecurity`.
> Updated when pre-security hooks run for create.

- changelog.md
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateSessionFactoryStore.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java
Hibernate 5.2 changes HibernateException to now extend PersistenceException:
https://github.com/hibernate/hibernate-orm/wiki/Migration-Guide---5.2
Fixes #640
> Remapped catch blocks for HibernateException to PersistenceException

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/core/exceptions/InvalidAttributeException.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-core/src/test/java/example/Author.java
- elide-core/src/test/java/example/Left.java
- elide-core/src/test/java/example/Right.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/Session.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/AbstractHQLQueryBuilder.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/RootCollectionFetchQueryBuilder.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/SubCollectionFetchQueryBuilder.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/AbstractHQLQueryBuilderTest.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/RootCollectionFetchQueryBuilderTest.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/RootCollectionPageTotalsQueryBuilderTest.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/SubCollectionFetchQueryBuilderTest.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/TestSessionWrapper.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/porting/SessionWrapper.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/porting/SessionWrapper.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/AnyPolymorphismIT.java
- elide-integration-tests/src/test/java/example/Left.java
- elide-integration-tests/src/test/java/example/Right.java
- elide-integration-tests/src/test/java/example/SpecialRead.java
Hibernate will lazily fetch to-one relationships leading to N+1 problem during hydration.  This PR should help mitigate.
> Add fetch joins for to-one relationships to improve HQL performance

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/ElideSettings.java
- elide-core/src/main/java/com/yahoo/elide/ElideSettingsBuilder.java
- elide-core/src/main/java/com/yahoo/elide/core/ErrorObjects.java
- elide-core/src/main/java/com/yahoo/elide/core/exceptions/CustomErrorException.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLEndpoint.java
- elide-integration-tests/src/test/java/com/yahoo/elide/errorObjectsTests/ErrorObjectsIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/initialization/ErrorObjectsIntegrationTestApplicationResourceConfig.java
- elide-integration-tests/src/test/java/com/yahoo/elide/initialization/ErrorObjectsTestBinder.java
- Add `CustomErrorException` extend the `HttpStatusException`
- Add `ErrorObjects` to help build error objects
For example, people build a `ErrorObjects` and provides it to the `CustomErrorException` (or its subclass) and throw it in the lifecycle trigger funtions. Then the error in the response is what they want.
Is this a valid use case ?
> Add support for custom error objects

- changelog.md
- elide-standalone/src/main/java/com/yahoo/elide/standalone/ElideStandalone.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideStandaloneSettings.java
This PR adds support to manipulate the Jetty `ServletContextHandler` directly through a new `ElideStandaloneSettings` feature.
> Add hook for servlet context handler.

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/utils/coerce/CoerceUtil.java
- elide-core/src/test/java/com/yahoo/elide/utils/coerce/CoerceUtilTest.java
Addresses issues with: https://github.com/yahoo/elide/issues/689
In summary, `BeanUtilsBean#getInstance` [returns a pseudo-singleton](https://commons.apache.org/proper/commons-beanutils/apidocs/org/apache/commons/beanutils/BeanUtilsBean.html#getInstance--). Namely, it's based on the `Thread.currentThread().getContextClassLoader()`.
This PR sets up CoerceUtil for each new classloader as necessary.
> Add support for multiple classloaders for CoerceUtil.

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/core/filter/dialect/CaseSensitivityStrategy.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialect.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialectTest.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialectWithColumnCollationStrategyTest.java
Following our discussion in #696 I implemented an additional configuration to the RSQLDialect.
I am not totally sure whether this is the correct place for a "global configuration", but this would suit the requirements in our project without changing the default Elide behavior.
Any feedback is welcome.
> Fix #696 Introduce CaseSensitivityStrategy for string comparison

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/utils/coerce/CoerceUtil.java
Updates the multiple classloader implementation to hold a `WeakReference<ClassLoader>` instead of a direct reference to `ClassLoader`.
@wcekan does this look better?
> Hold weak references to class loaders.

- checkstyle-style.xml
- elide-annotations/src/main/java/com/yahoo/elide/annotation/Audits.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/models/ResourceIdentifier.java
- elide-core/src/main/java/com/yahoo/elide/parsers/GetVisitor.java
- elide-core/src/main/java/com/yahoo/elide/parsers/expression/FilterExpressionCheckEvaluationVisitor.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/NotExpression.java
Configured CheckStyle `CustomImportOrder` to handle the unusual Elide import order.
See [elide-intellij-codestyle.xml](https://github.com/yahoo/elide/blob/master/elide-intellij-codestyle.xml)
> Enforce Elide import order with checkstyle.

- changelog.md
- elide-contrib/pom.xml
- elide-datastore/elide-datastore-hibernate5/pom.xml
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/test/java/com/yahoo/elide/datastores/hibernate5/HibernateDataStoreSupplier.java
- elide-datastore/pom.xml
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/ResourceIT.java
- pom.xml
It seems Hibernate 5 tests were not running due to test version incompatibility.
```
-------------------------------------------------------
T E S T S
-------------------------------------------------------
Results :
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
```
Spun this instead of addressing in PR #738
> Update surefire and failsafe versions

- changelog.md
- elide-contrib/elide-swagger/pom.xml
- elide-contrib/pom.xml
- elide-core/src/test/java/com/yahoo/elide/core/LifeCycleTest.java
- elide-datastore/elide-datastore-hibernate3/pom.xml
- elide-datastore/elide-datastore-hibernate3/src/test/java/com/yahoo/elide/datastores/hibernate3/HibernateDataStoreSupplier.java
- elide-datastore/elide-datastore-hibernate5/pom.xml
- elide-datastore/elide-datastore-hibernate5/src/test/java/com/yahoo/elide/datastores/hibernate5/HibernateDataStoreSupplier.java
- elide-datastore/elide-datastore-hibernate5/src/test/java/com/yahoo/elide/datastores/hibernate5/HibernateEntityManagerDataStoreSupplier.java
- elide-datastore/elide-datastore-multiplex/pom.xml
- elide-datastore/elide-datastore-multiplex/src/test/java/com/yahoo/elide/datastores/multiplex/bridgeable/BridgeableStoreSupplier.java
- elide-datastore/pom.xml
- elide-example/elide-blog-example-resteasy/pom.xml
- elide-example/elide-blog-example/pom.xml
- elide-example/elide-hibernate3-mysql-example/pom.xml
- elide-integration-tests/pom.xml
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/ResourceIT.java
- elide-integration-tests/src/test/java/example/Book.java
- elide-integration-tests/src/test/resources/hibernate.cfg.xml
- pom.xml
Replacing a deprecated `jcabi-mysql-maven-plugin` with H2 for database testing.
> Replace jcabi-mysql-maven-plugin with H2 for testing

- checkstyle-style.xml
- elide-contrib/elide-test-helpers/README.md
- elide-contrib/elide-test-helpers/pom.xml
- elide-contrib/elide-test-helpers/src/main/java/com/yahoo/elide/contrib/testhelpers/jsonapi/JsonApiDSL.java
- elide-contrib/elide-test-helpers/src/main/java/com/yahoo/elide/contrib/testhelpers/jsonapi/elements/Attribute.java
- elide-contrib/elide-test-helpers/src/main/java/com/yahoo/elide/contrib/testhelpers/jsonapi/elements/Attributes.java
- elide-contrib/elide-test-helpers/src/main/java/com/yahoo/elide/contrib/testhelpers/jsonapi/elements/Data.java
- elide-contrib/elide-test-helpers/src/main/java/com/yahoo/elide/contrib/testhelpers/jsonapi/elements/Id.java
- elide-contrib/elide-test-helpers/src/main/java/com/yahoo/elide/contrib/testhelpers/jsonapi/elements/Relation.java
- elide-contrib/elide-test-helpers/src/main/java/com/yahoo/elide/contrib/testhelpers/jsonapi/elements/Relationships.java
- elide-contrib/elide-test-helpers/src/main/java/com/yahoo/elide/contrib/testhelpers/jsonapi/elements/Resource.java
- elide-contrib/elide-test-helpers/src/main/java/com/yahoo/elide/contrib/testhelpers/jsonapi/elements/ResourceLinkage.java
- elide-contrib/elide-test-helpers/src/main/java/com/yahoo/elide/contrib/testhelpers/jsonapi/elements/Type.java
- elide-contrib/elide-test-helpers/src/test/java/com/yahoo/elide/contrib/testhelpers/jsonapi/JsonApiDSLTest.java
- elide-contrib/pom.xml
- Creates new elide-test-helpers module
- Add README
- Adds DSL for creating json:api documents
- Allows wild card import for JsonApiDSL class
> Add elide-test-helpers

- elide-core/src/test/java/com/yahoo/elide/core/LifeCycleTest.java
A bad copy/paste left a potential bug in the LifeCycleTest.  Fortunately, the code was working correctly.
> Fix typo in LifeCycleTest

- changelog.md
- elide-core/pom.xml
- elide-core/src/main/java/com/yahoo/elide/core/EntityBinding.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/main/java/com/yahoo/elide/core/sort/Sorting.java
- elide-core/src/main/java/com/yahoo/elide/security/FilterExpressionCheck.java
- elide-core/src/test/java/com/yahoo/elide/core/EntityDictionaryTest.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/AbstractHibernateTestService.java
- elide-datastore/elide-datastore-hibernate3/src/test/java/com/yahoo/elide/datastores/hibernate3/HibernateDataStoreSupplier.java
- elide-datastore/elide-datastore-hibernate5/src/test/java/com/yahoo/elide/datastores/hibernate5/HibernateDataStoreSupplier.java
- elide-example-models/README.md
- elide-example-models/pom.xml
- elide-example-models/src/main/java/com/yahoo/elide/models/BaseId.java
- elide-example-models/src/main/java/com/yahoo/elide/models/generics/Employee.java
- elide-example-models/src/main/java/com/yahoo/elide/models/generics/Manager.java
- elide-example-models/src/main/java/com/yahoo/elide/models/generics/Overlord.java
- elide-example-models/src/main/java/com/yahoo/elide/models/generics/Peon.java
- elide-example-models/src/main/java/com/yahoo/elide/models/generics/Person.java
- elide-example-models/src/main/java/com/yahoo/elide/models/generics/package-info.java
- elide-integration-tests/pom.xml
- elide-integration-tests/src/test/java/com/yahoo/elide/inheritance/InheritanceIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/initialization/AbstractIntegrationTestInitializer.java
- pom.xml
Fixes #733.
There is a restructure here to move to a common artifact for both unit & integration test models (elide-example-models).
There will be another PR that adds a new DSL for Rest Assured Testing for JSON-API.  Once that is added, this PR will add integration tests based on the new DSL.
> Fixed generic field handling

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/resources/JsonApiEndpoint.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLEndpoint.java
This PR sets the request's [SecurityContext](https://javaee.github.io/javaee-spec/javadocs/javax/ws/rs/core/SecurityContext.html) as the DefaultOpaqueUser in the case a `elideUserExtractionFunction` is not provided.
This could simplify Elide configuration since the [SecurityContext](https://javaee.github.io/javaee-spec/javadocs/javax/ws/rs/core/SecurityContext.html) or the [Principal](https://docs.oracle.com/javase/8/docs/api/java/security/Principal.html) inside the [SecurityContext](https://javaee.github.io/javaee-spec/javadocs/javax/ws/rs/core/SecurityContext.html) is what developers would naturally want to use when writing their permission checks.
> Use SecurityContext as default User object

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/jsonapi/models/Resource.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
Avoid throwing a NPE when POST or PATCH contains
```json
"relationships": {
"right": {
"data": {
"type": "right",
"id": null
}
}
}
```
> Throw exception when attempting to convert id=null resource

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/core/EntityBinding.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/test/java/com/yahoo/elide/core/EntityBindingTest.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-core/src/test/java/example/Job.java
If you have a JPA model where one entity has an ID which is dictated by the value in another entity (mapped via the JPA `@MapsId` annotation) then ELIDE needs to not force a creating POST request to contain an ID.
e.g.[https://www.concretepage.com/hibernate/example-mapsid-hibernate](https://www.concretepage.com/hibernate/example-mapsid-hibernate)
This PR adds support for the `@MapsId` annotation in entities. Without this you are unable to create such a dependent entity using ELIDE (unless you provide a dummy ID which gets discarded, and which is an incorrect use of JSON:API)
> Add support for JPA @MapsId annotation

- changelog.md
- elide-contrib/elide-test-helpers/pom.xml
- elide-core/src/main/java/com/yahoo/elide/core/DataStoreTransaction.java
- elide-datastore/elide-datastore-hibernate3/pom.xml
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate5/pom.xml
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java
- elide-datastore/elide-datastore-jpa/pom.xml
- elide-datastore/elide-datastore-multiplex/pom.xml
- elide-integration-tests/src/test/groovy/com/yahoo/elide/tests/GenerateIT.groovy
- elide-integration-tests/src/test/java/example/Generate.java
Flush is required before serialization to properly populate `@Generated` fields.
> Flush once for patch extension

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/core/datastore/inmemory/InMemoryStoreTransaction.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java
The change to force a flush before commit does not work for some of our Hibernate 3 beans.
This change makes the flush mechanism configurable while defaulting to the prior functionality.
> Restore hibernate flush mode

- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/main/java/com/yahoo/elide/core/datastore/inmemory/InMemoryStoreTransaction.java
- elide-core/src/main/java/com/yahoo/elide/extensions/PatchRequestScope.java
- elide-core/src/test/java/com/yahoo/elide/audit/LogMessageTest.java
- elide-core/src/test/java/com/yahoo/elide/core/LifeCycleTest.java
- elide-core/src/test/java/com/yahoo/elide/core/PermissionAnnotationTest.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistenceResourceTestSetup.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-core/src/test/java/com/yahoo/elide/core/RequestScopeTest.java
- elide-core/src/test/java/com/yahoo/elide/core/UpdateOnCreateTest.java
- elide-core/src/test/java/com/yahoo/elide/core/datastore/inmemory/InMemoryStoreTransactionTest.java
- elide-core/src/test/java/com/yahoo/elide/jsonapi/JsonApiTest.java
- elide-core/src/test/java/com/yahoo/elide/jsonapi/document/processors/IncludedProcessorTest.java
- elide-core/src/test/java/com/yahoo/elide/parsers/expression/PermissionToFilterExpressionVisitorTest.java
- elide-core/src/test/java/com/yahoo/elide/security/PermissionExecutorTest.java
- elide-core/src/test/java/com/yahoo/elide/security/permissions/PermissionExpressionBuilderTest.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLRequestScope.java
This was an old hack that is no longer needed and should simplify things.
> Removed all references to RequestScope.isMutatingMultipleEntities

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/core/datastore/inmemory/InMemoryStoreTransaction.java
- elide-datastore/elide-datastore-hibernate3/src/main/java/com/yahoo/elide/datastores/hibernate3/HibernateTransaction.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java
- elide-datastore/elide-datastore-jpa/src/main/java/com/yahoo/elide/datastores/jpa/transaction/AbstractJpaTransaction.java
When fetching a collection, if there are no filters, sorting, or client specified pagination, the ORM backed data stores will *now* return the proxy object rather than construct a JPQL query.  This allows the ORM the opportunity to generate SQL to avoid the N+1 problem.
Note: JPQL can only avoid the N+1 problem by prefetching toOne relationships through joins.  Other ORM provided solutions are not supported in JPQL.  Prefetching toMany relationships through joins is not tenable for large collections.
> Allow ORM to generate SQL when possible (to avoid N+1)

- changelog.md
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLConversionUtils.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/ModelBuilderTest.java
- elide-graphql/src/test/java/example/Book.java
Resolves https://github.com/yahoo/elide/issues/812
This change adds support for BigDecimal in the GraphQL API by mapping it to the GraphQLBigDecimal class.
This change allows models with BigDecimal fields to be properly converted to GraphQLBigDecimal, when using the GraphQL API. Currently, BigDecimal gets converted to an Object type instead of a Scalar.
- Added BigDecimal field `weightLbs` to the Book model in `elide-graphql/src/test/java/example/Book.java`.
- Added assertion to ModelBuilderTest to assert that `weightLbs` on the Book model gets converted to a GraphQLBigDecimal class.
> Add graphql support for BigDecimal

- changelog.md
- elide-standalone/pom.xml
- elide-standalone/src/main/java/com/yahoo/elide/standalone/Util.java
Elide Standalone should have sane defaults for:
- Hibernate batch fetching
- A JDBC connection pool
Out of the box, Elide standalone does not leverage any basic features that improve performance.  Given that Elide standalone is an opinionated instance, it should enable these best practices.
Manually tested with Elide Standalone.  Verified the connection pool settings took effect.
N/A
> Add default jpa query batching

- .github/PULL_REQUEST_TEMPLATE.md
VZM is moving away from using the CLA checker. We can remove the CLA checker if we add the license clause to the PR template
This also will allow `dependabot-preview` to make PRs
n/a
n/a
> Add license info to pr template

- elide-core/src/main/java/com/yahoo/elide/core/EntityBinding.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialect.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialectTest.java
Resolves https://github.com/yahoo/elide/issues/801
Update RSQL filter to use real id field when the entity is using customized id field.
Previous, filtering on **id** field would fail if the id field for an entity is using a customized id field name. As **id** is a reserved field name only for id field, when filtering on **id**, the filter should be applied to the bound id field.
Use Job.class and StringId.class for testing customized id field, reference: https://github.com/yahoo/elide/pull/809
> #801 RSQL filter on customized id field

- .travis.yml
- changelog.md
Travis Builds are failing with Oracle JDK8.  This PR changes to use Open JDK.
Switch to Open JDK (get away from Oracle).
This PR build.
> Switch to open jdk

- elide-contrib/elide-swagger/pom.xml
- elide-example/elide-blog-example/pom.xml
- elide-example/elide-hibernate3-mysql-example/pom.xml
For some reason, github security alerts don't handle sub-modules that have version dependencies (where the version is defined in a parent pom).
So we stop getting bogus alerts.
The build passes.
> Fix pom.xml so github stops complaining about bogus security alerts

- elide-contrib/elide-test-helpers/src/main/java/com/yahoo/elide/contrib/testhelpers/jsonapi/JsonApiDSL.java
- elide-contrib/elide-test-helpers/src/test/java/com/yahoo/elide/contrib/testhelpers/jsonapi/JsonApiDSLTest.java
💥 DO NOT MERGE THIS PR UNTIL https://github.com/yahoo/elide/pull/903 is merged
Resolves a test issue.
In a [to-one relationship test](https://github.com/yahoo/elide/blob/RefactorResourceIT/elide-contrib/elide-test-helpers/src/test/java/com/yahoo/elide/contrib/testhelpers/jsonapi/JsonApiDSLTest.java#L50), I found the relationship returns [an array](https://github.com/yahoo/elide/blob/RefactorResourceIT/elide-contrib/elide-test-helpers/src/test/java/com/yahoo/elide/contrib/testhelpers/jsonapi/JsonApiDSLTest.java#L53)  of resource identifier objects. This is because [relation()](https://github.com/yahoo/elide/blob/RefactorResourceIT/elide-contrib/elide-test-helpers/src/test/java/com/yahoo/elide/contrib/testhelpers/jsonapi/JsonApiDSLTest.java#L63) creates to-many relationship by default.
I …
> To-one Relation Test

- changelog.md
- elide-contrib/elide-swagger/src/main/java/com/yahoo/elide/contrib/swagger/JsonApiModelResolver.java
- elide-contrib/elide-swagger/src/test/java/com/yahoo/elide/contrib/swagger/JsonApiModelResolverTest.java
- elide-contrib/elide-swagger/src/test/java/com/yahoo/elide/contrib/swagger/SwaggerBuilderTest.java
- elide-contrib/elide-swagger/src/test/java/com/yahoo/elide/contrib/swagger/models/Book.java
- elide-contrib/elide-swagger/src/test/java/com/yahoo/elide/contrib/swagger/models/Publisher.java
Resolves #900
`JsonApiModelResolver` additionally to processing permission annotations, processes `@ApiModelProperty` to transfer the following attributes to the resulting generated swagger document:
* `description` - sets contents of `value` annotation attribute, if present, to the `description` property attribute in swagger document, and concatenates permissions on next lines for backward compatibility
* `example` - sets value of `example` annotation attribute, if present, to the `example` property attribute in swagger document
* `readOnly` - sets value of `readOnly` annotation attribute, if present, to the `read-only` property attribute in swagger document
* `required` - sets value of `required` annotation attribute, if present, to the `required` property attribute in swagger document …
> Implements #900 - elide-swagger to support @ApiModelProperty annotation

- elide-core/src/main/java/com/yahoo/elide/jsonapi/models/JsonApiDocument.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/models/Meta.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/serialization/MetaDeserializer.java
- elide-core/src/test/java/com/yahoo/elide/jsonapi/JsonApiTest.java
Resolves #913 
Adds a custom deserializer for `Meta`.
This fixes the `meta` deserialization problem documented in #913 
Added tests `readSingleWithMeta()` and `readListWithMeta()` to `JsonApiTest.java` to verify that the `meta` object is being properly deserialized.
> Fix deserialization for optional top-level meta object (#913)

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/engine/AbstractEntityHydrator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/engine/StitchList.java
- Make private fields protected so that children classes can have different constructor
- Change results from `List<Object>` to `List<Map<String, Object>>`
> Refactor EntityHydrator

- elide-contrib/elide-test-helpers/src/main/java/com/yahoo/elide/contrib/testhelpers/jsonapi/JsonApiDSL.java
- elide-contrib/elide-test-helpers/src/main/java/com/yahoo/elide/contrib/testhelpers/jsonapi/elements/PatchOperation.java
- elide-contrib/elide-test-helpers/src/main/java/com/yahoo/elide/contrib/testhelpers/jsonapi/elements/PatchOperationType.java
- elide-contrib/elide-test-helpers/src/main/java/com/yahoo/elide/contrib/testhelpers/jsonapi/elements/PatchSet.java
- elide-contrib/elide-test-helpers/src/test/java/com/yahoo/elide/contrib/testhelpers/jsonapi/JsonApiDSLTest.java
Adds patch extension format to json api dsl
This will assist in refactoring the IT tests
Unit tests have been added
> Add patch extension to DSL

- elide-core/pom.xml
Reverses JPA dependency change from (#894)
Resolved downstream build conflict with hibernate-jpa-2.0-api.
Local build.
> Restore provided on jpa

- pom.xml
- suppressions.xml
Fix build failure due to vulnerability check on Jackson Databind
To get build working
N/A
> Suppress databind vulnerability warnings until December

- elide-annotations/src/main/java/com/yahoo/elide/security/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/security/executors/ActivePermissionExecutor.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/PersistentResourceFetcher.java
- pom.xml
GraphQL during an UPDATE or UPSERT of a nested entity will attempt to add the nested entity to its parent relationship.  This is unnecessary for UPDATE (and also UPSERT where the object already exists).  
Normally, this would be harmless, but SharePermission barfs.  
Explained above.
All existing GraphQL tests pass.
Manually tested the fix in another project.   Note - SharePermission is being removed in Elide 5.0 - so this bug would never have manifested.
> Fix GraphQL Nested UPDATE bug.

- elide-graphql/src/main/java/com/yahoo/elide/graphql/PersistentResourceFetcher.java
Fixes missing child relationships in GraphQL upsert of a new object. See #974  
4.5.3 release broke in our local testing of another project.
All existing GraphQL tests pass.
Manually tested this fix our project which was broken by 4.5.3 release.
> Nested update

- pom.xml
Solve the misalignment between jackson-core and jackson-databind
> Update jackson-databind to use version property

- checkstyle-style.xml
- elide-core/pom.xml
- elide-core/src/main/java/com/yahoo/elide/core/EntityPermissions.java
- elide-core/src/main/java/com/yahoo/elide/parsers/JsonApiParser.java
- elide-graphql/pom.xml
- pom.xml
[CVE-2019-10086](https://nvd.nist.gov/vuln/detail/CVE-2019-10086) Upgrade to Apache Commons Beanutils 1.9.4
ANTLR4 Use CharStreams.
Lombok should always be scoped `provided`.
Remove vulnerability.
Replace deprecated code.
Local testing.  Unit testing.
> Update Apache Commons Beanutils and ANTLR4 CharStreams

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/AggregationDataStoreTransaction.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/engine/SQLEntityHydrator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/engine/SQLQueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/AggregationDataStoreIntegrationTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/engine/SQLQueryEngineTest.java
Changed SQLQueyEngine so that EntityManager is created separately for each new query instead of being created once when the Engine was initialized.
> Moved entityManager creation to happen separately for each query

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/AggregationDataStore.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/AggregationDataStoreTransaction.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/QueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/engine/SQLEntityHydrator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/engine/SQLQueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/engine/annotation/JoinTo.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/engine/schema/SQLDimension.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/engine/schema/SQLSchema.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/engine/schema/SQLTimeDimension.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/schema/Schema.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/AggregationDataStoreIntegrationTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/engine/SQLQueryEngineTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/example/PlayerStats.java
This PR is for the new AggregationDataStore.
The SQLQueryEngine will support a new annotation (JoinTo) that allows attribute columns to be populated by joins that traverse a snowflake schema.
class Publisher {
@JoinTo(“book.category”)
Category bookCategory
}
class Publisher {
@JoinTo(“book.category.name”)
String categoryName
}
Initially, The SQLQueryEngine will only support the simple case of building a left join across a to-one relationship where the left table has the foreign key reference to the right table.
Without this annotation, joins can only be supported in the `@FromSQL` annotation - which requires all joins to be present regardless of whether a given field is needed in the client's request.
Furthermore, the existing SQLQueryEngine did not provide a mechanism to group by …
> Add JoinTo annotation

- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLConversionUtils.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/ModelBuilder.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/ModelBuilderTest.java
- elide-graphql/src/test/resources/graphql/responses/fetch/fetchWithFragment.json
Resolves #1007
Removes __ from generated type names in GraphQL schema.
__ is reserved in GraphQL.  Graphiql barfs on this.
Build passes.  Manually ran graphiql.
> Fixes #1007 - Remove reserved '__' from graphQL schema type names.

- elide-core/src/main/java/com/yahoo/elide/core/ArgumentType.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityBinding.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLConversionUtils.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/ModelBuilder.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/ModelBuilderTest.java
Resolves #890 
Added `addArgumentsToAttribute` to `EntityDictionary` that accepts Map object as argument for an attribute in an Entity. `getAttributeArguments` method retrieves this object.
This method is used by EntityProjectionMaker to populate the argument set for the attribute. 
ModelBuilder uses getAttributeArguments method to expose the argument in the schema.
Unit testing or `ModelBuilder` class checks whether the GraphQL schema contains arguments to the attribute that was added by explicitly calling `addArgumentsToAttributes` method.
> Hydrate GraphQL Schema with parameterized attributes

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistenceResourceTestSetup.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceNoopUpdateTest.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/PersistentResourceFetcher.java
We have been calling addRelation to parent entity for updates to child
entities in graphql. This checks the share permission for the child
entity and may fail in some cases.
This PR avoids checking the share permission in case when the entity is
already a part of the relation with the parent.
The unit tests are in the file below.
elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceNoopUpdateTest.java
> Avoid checking share permission for redundant add

- elide-core/src/main/java/com/yahoo/elide/security/FilterExpressionCheck.java
- elide-example/elide-blog-example/pom.xml
Elide 4.5.5 release had two issues:
1. There was a compilation change required in FilterExpressionCheck that break SEMVER.
2. elide-blog-example had pom issues that prevented artifacts syncing with maven central.
See above.
Build passes.
> Fix elide4.5.5

- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideStandaloneSettings.java
Changed the function name from `enableIS06081Dates` to `enableISO8601Dates`
> function name fixed to enableISO8601Dates

- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideStandaloneSettings.java
- elide-standalone/src/test/java/com/yahoo/elide/standalone/ElideStandaloneTest.java
Change the elide standalone settings interface to be able to provide an audit logger.
Right now elide standalone has no way of configuring the audit logger, this exposes it as part of the interface so it can be customized.
Updated existing test.
> Expose audit logger in standalone

- elide-core/src/main/java/com/yahoo/elide/audit/LogMessage.java
- elide-core/src/test/java/com/yahoo/elide/audit/LogMessageTest.java
Expose opaque user through audits so it can be logged through log statements.
Right now there is no way to get to opaque user information through audit logging interface.  It might be fine if we inject user information through slf4j mdc but if we want to implement our own logger and want to use the log statements through elide to generate the final messages, we need to expose the opaque user.
Test was added.
> Expose opaque user in audits

- elide-spring/elide-spring-boot-starter/pom.xml
- elide-standalone/pom.xml
- pom.xml
OWASP security scan started failing for Jetty and Guava.
Builds are failing.
Build passes.
> Upgraded dependencies to pass OWASP security scan

- elide-standalone/README.md
Main Elide _Getting Started_ docs are going to change to describe spring boot setup.  This PR migrates the current getting starting docs to this README since they reference Elide standalone.
> Migrate legacy getting started to elide standalone readme

- elide-spring/elide-spring-boot-starter/README.md
Small update to starter readme to make the starter more linkable.
To add Elide Spring Boot Starter to Spring Boot project links.
> Added license and link to central docs

- elide-graphql/src/main/java/com/yahoo/elide/graphql/QueryRunner.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/com/yahoo/elide/spring/models/ArtifactGroup.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/com/yahoo/elide/spring/tests/ControllerTest.java
GraphQL doesn't log the verbose error messages on ForbiddenAccessException like its cousin JSON-API.
Logging should be the same across both.
Manually tested in the logs.  I also added a test to ensure the API doesn't change on errors for GraphQL going forward.
> Fixing GraphQL Logging on ForbiddenAccessExceptions to match JSON-API

- elide-datastore/elide-datastore-jpa/src/main/java/com/yahoo/elide/datastores/jpa/JpaDataStore.java
- elide-datastore/elide-datastore-jpa/src/test/java/com/yahoo/elide/datastores/jpa/JpaDataStoreTest.java
There is a common use case where we want to restrict the entities a JPA store manages.
This can be done at the persistence unit level (by configuring the EntityManager in persistence.xml or other means).  It can also be done by subclassing the store and manually binding the entities you want the store to manage.
This PR simplifies this by allowing the constructor to take a list of entities to manually bind.
Simplifies a common scenario where we want multiple JpaDataStores - some with specific logic for a given entity and a general one that manages everything else.
Unit Tests
> Added manual override in JpaDataStore to explicitly bind entities

- elide-core/src/main/java/com/yahoo/elide/utils/ClassScanner.java
- elide-core/src/test/java/com/yahoo/elide/core/utils/ClassScannerTest.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/MetaDataStore.java
Improves performance by reducing the amount of class scanning that is required to build the MetadataStore's metadata.
> Improving class scanning performance for MetadataStore

- elide-spring/elide-spring-boot-autoconfigure/src/test/java/com/yahoo/elide/spring/tests/ControllerTest.java
This change removes redundant code from the spring boot tests.
This change is technically not required. I stumbled across it, when trying do reproduce technical problems with the official spring tests.
I don't like repeated code if I can avoid it. Furthermore, I would always suggest to make a suite of tests run in the same "environment" or in this case the same set of default data.
Maven tests have been run.
> Spring tests: Move repeated @Sql annotations to class level

- elide-spring/elide-spring-boot-autoconfigure/pom.xml
Spring Web depends on a version of Tomcat with a OWASP security warning.
Upgrading tomcat to fix the build.
Build runs.
> Fixing OWASP security warning for Tomcat dependency in Spring Web

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/QueryValidator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLQueryConstructor.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLQueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/QueryValidatorTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/AggregationDataStoreIntegrationTest.java
Query without any metric would be constructed as `SELECT DISTINCT ...` with out `GROUP BY` clauses.
- Allow query without metric
- Construct `SELECT DISTINCT` query
- Update query sorting validation
- Remove query metric validation
- To address the druid dimension use case.
Unit test and Integration test are updated.
> Support no metric query

- elide-core/pom.xml
- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
- elide-core/src/main/java/com/yahoo/elide/core/LifecycleHookInvoker.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/datastore/inmemory/HashMapStoreTransaction.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-core/src/test/java/com/yahoo/elide/security/PermissionExecutorTest.java
- pom.xml
Fixed the incorrect compile elide-core dependency on example models.  This should be test scope.
```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ elide-core ---
[INFO] com.yahoo.elide:elide-core:jar:4.5.13-SNAPSHOT
[INFO] +- com.yahoo.elide:elide-annotations:jar:4.5.13-SNAPSHOT:compile
[INFO] +- com.yahoo.elide:elide-example-models:jar:4.5.13-SNAPSHOT:test
```
Also cleaned up PersistentResource type checks.
End product had dependency on example beans.
Unit testing
> Update test dependency on example models

- pom.xml
Bump dependency-check-maven to latest version 5.3.0
> Bump dependency-check-maven from 5.2.4 to 5.3.0

- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/core/DataStoreTransaction.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/models/JsonApiDocument.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/RelationshipTerminalState.java
- elide-core/src/test/java/com/yahoo/elide/jsonapi/JsonApiTest.java
Pulled out only the code changes from #1162 for easier review.
- JsonApiDocument hashCode and equals were inconsistent.
- Correctly process empty ConstraintViolations
- Remove unnecessary initializations in code
Stability
Unit testing
> JsonApiDocument hashCode and equals were inconsistent

- elide-contrib/elide-swagger/src/main/java/com/yahoo/elide/contrib/swagger/JsonApiOperation.java
- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/resources/JsonApiEndpoint.java
- elide-core/src/test/java/com/yahoo/elide/core/LifeCycleTest.java
- elide-datastore/elide-datastore-multiplex/src/test/java/com/yahoo/elide/datastores/multiplex/BridgeableStoreTest.java
- elide-datastore/elide-datastore-search/src/test/java/com/yahoo/elide/datastores/search/SearchDataStoreITTest.java
- elide-integration-tests/src/test/java/com/yahoo/elide/assignedIdLongTests/AssignedIdLongIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/auditTests/AuditIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/errorEncodingTests/EncodedErrorObjectsIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/errorEncodingTests/EncodedErrorResponsesIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/errorEncodingTests/VerboseEncodedErrorResponsesIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/errorObjectsTests/ErrorObjectsIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/fieldLevelTest/FieldLevelParentClassIdIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/inheritance/InheritanceIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/AnyPolymorphismIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/BookAuthorIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/FilterIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/GenerateIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/MapEnumIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/PaginateIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/ResourceIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/ShareableIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/SortingIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/UserTypeIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/triggers/LifeCycleHookIT.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/controllers/JsonApiController.java
- elide-standalone/src/test/java/com/yahoo/elide/standalone/ElideStandaloneTest.java
Move string constants for JSONAPI content types to one location.
Stability
Build, unit tests
> Consolidate JSON API Content Type constant

- elide-core/pom.xml
- elide-graphql/pom.xml
- elide-integration-tests/pom.xml
- pom.xml
Remove Groovy as Dependency
Dependabot wants to upgrade it.
Build passes locally.
> Removed Groovy as Dependency

- .gitignore
- elide-contrib/elide-swagger/src/main/java/com/yahoo/elide/contrib/swagger/JsonApiModelResolver.java
- elide-contrib/elide-swagger/src/test/java/com/yahoo/elide/contrib/swagger/JsonApiModelResolverTest.java
- elide-contrib/elide-swagger/src/test/java/com/yahoo/elide/contrib/swagger/models/Book.java
Resolves #1095 
Elide will honor ApiModelProperty annotations for relationships - overriding the default behavior.
Elide was ignoring the ApiModelProperty annotations for relationships
Added new test cases.
N/A
> Honor ApiModelProperty annotations for relationships

- elide-core/src/main/java/com/yahoo/elide/core/filter/FilterPredicate.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/IsEmptyPredicate.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/NotEmptyPredicate.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/Operator.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/dialect/DefaultFilterDialect.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialect.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/OperatorTest.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/dialect/DefaultFilterDialectTest.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialectTest.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/expression/InMemoryFilterExecutorTest.java
- elide-core/src/test/java/example/Author.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/filter/FilterTranslator.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/core/filter/FilterTranslatorTest.java
- elide-datastore/elide-datastore-hibernate3/pom.xml
- elide-datastore/elide-datastore-hibernate5/pom.xml
- elide-datastore/elide-datastore-jpa/pom.xml
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/FilterIT.java
- elide-integration-tests/src/test/java/example/Book.java
- elide-integration-tests/src/test/resources/FilterIT/book_author_publisher_patch1.json
- elide-integration-tests/src/test/resources/FilterIT/book_author_publisher_patch3.json
- elide-integration-tests/src/test/resources/FilterIT/book_author_publisher_patch4.json
Resolves #1160 
Added IsEmpty Filter operation with syntax `=isempty=`. 
isempty filter operation are useful in most cases and the community needed support for this operation. 
Added New Test Cases
> Added IsEmpty operation for filter predicate

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/QueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/MetaDataStore.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Column.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLColumn.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLDimension.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLTimeDimension.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/framework/SQLUnitTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/AggregationDataStoreIntegrationTest.java
Resolves #1005 
- Add `sourceColumn` field into `Column` model.
- `QueryEngine` would call `MetaDataStore` to resolve source columns.
Metadata integration test is updated.
> sourceColumn

- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/AggregationDataStoreIntegrationTest.java
- elide-datastore/elide-datastore-aggregation/src/test/resources/graphql/responses/testGraphQLSchema.json
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLConversionUtils.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLNameUtils.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/ModelBuilder.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/parser/GraphQLEntityProjectionMaker.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/ModelBuilderTest.java
- elide-graphql/src/test/resources/graphql/requests/fetch/fragmentCorrect.graphql
- elide-graphql/src/test/resources/graphql/requests/fetch/fragmentInline.graphql
- elide-graphql/src/test/resources/graphql/requests/fetch/fragmentLoop.graphql
- elide-graphql/src/test/resources/graphql/requests/fetch/fragmentUnknown.graphql
- elide-graphql/src/test/resources/graphql/responses/fetch/fragmentCorrect.json
Change the way types are named in the GraphQL schema to help with client generation tools and to be more human readable.
These changes are based on the Relay specification:
https://relay.dev/docs/en/graphql-server-specification.html
|                      | Type Name (Initially)                                               | Type Name (Now)                        |
|----------------------|---------------------------------------------------------------------|----------------------------------------|
| Node                 | \_node\_\_\<entityName\>                                                 | \<EntityName\>                           |
| Edge                 | \_edges\_\_\<entityName\>                                                | \<EntityName\>Edge                       |
| …
> Change the way types are named in the GraphQL schema

- elide-core/src/main/java/com/yahoo/elide/core/EnforceJoinFilterExpressionVisitor.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityBinding.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResourceSet.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/main/java/com/yahoo/elide/core/VerifyFieldAccessFilterExpressionVisitor.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-core/src/test/java/com/yahoo/elide/core/VerifyFieldAccessFilterExpressionVisitorTest.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/FilterIT.java
- elide-integration-tests/src/test/java/example/Author.java
- elide-integration-tests/src/test/resources/FilterIT/book_author_publisher_patch1.json
- elide-integration-tests/src/test/resources/SortingIT/addAuthorBookPublisher1.json
Enforce ReadPermission for filter joins.
Clean up duplicated filter expression builder in RequestScope.getLoadFilterExpression
Restricts filter join access to fields that pass ReadPermission.
Build tests.  Added additional Integration test.  
Tested locally with end product.
> Enforce ReadPermission for filter joins

- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/core/exceptions/UnableToAddSerdeException.java
- elide-core/src/main/java/com/yahoo/elide/utils/ClassScanner.java
- elide-core/src/test/java/com/yahoo/elide/ElideCustomSerdeRegistrationTest.java
- elide-core/src/test/java/com/yahoo/elide/core/EntityDictionaryTest.java
- elide-core/src/test/java/com/yahoo/elide/core/utils/ClassScannerTest.java
Improved performance of `ClassScanner` by limiting the collected data to that required.
Allow Elide subclass to disable or enhance `registerCustomSerde` by making the private method protected.
Initial Elide startup was taking many minutes in registerCustomSerde, which affected our product integration tests.
Tested locally with our product build.
> Improve performance of initial class scans

- elide-core/src/main/java/com/yahoo/elide/Elide.java
Allow override of registerCustomSerdeScan.
Improved performance at startup.
Local testing limited to scan of a single package.
```java
@Override
protected Set<Class<?>> registerCustomSerdeScan() {
return ClassScanner.getAnnotatedClasses(
OffsetDateTimeSerde.class.getPackage(),
ElideTypeConverter.class);
```
> Allow replacement of custom serde scan

- elide-core/src/main/java/com/yahoo/elide/core/VerifyFieldAccessFilterExpressionVisitor.java
- elide-core/src/test/java/com/yahoo/elide/core/VerifyFieldAccessFilterExpressionVisitorTest.java
Updated VerifyFieldAccessFilterExpressionVisitor to call PersistentResorce get relationship to cross datastore transition.
Will properly use proper transaction to request the relationship results.
Build testing.  Locally testing with our product.
> call PersistentResource get relationship

- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/AbstractHQLQueryBuilder.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/SubCollectionFetchQueryBuilder.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/AbstractHQLQueryBuilderTest.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/RootCollectionFetchQueryBuilderTest.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/SubCollectionFetchQueryBuilderTest.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/SortingIT.java
toOne relationships were only join fetched if they were OneToOne and not the owning side of the relationship.  This fix relaxes the constraint so all toOne joins are join fetched.
Solves N+1 problem.
Verified all existing tests pass.
Verified N+1 problem for ManyToOne and OneToOne (not mapped) is removed (manually be inspecting logs).
> Fixed N+1 problems for all toOne relationships

- elide-core/src/main/java/com/yahoo/elide/core/EntityBinding.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
- elide-core/src/main/java/com/yahoo/elide/security/FilterExpressionCheck.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/ExpressionResultCache.java
- elide-core/src/test/java/com/yahoo/elide/core/EntityDictionaryTest.java
Profiling showed a hotspot for `entityClass.getMethod(method)` in the FilterExpressionCheck.
Cleanup some `get/if null put` logic with more readable `computeIfAbsent`
Reduces overhead for `FilterExpressionPath` lookup.
Local testing with profiler.
> Optimize field annotation lookup

- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/controllers/JsonApiController.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/com/yahoo/elide/spring/tests/ControllerTest.java
The spring Elide controller does not accept the JSON-API patch content type extension. 
Elide with spring does not support JSON-API patch extension.
Added a new controller test.
> Fixing Spring JSON-API controller to allow JSON-API PATCH content type

- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/AbstractHQLQueryBuilder.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/RootCollectionFetchQueryBuilder.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/RootCollectionFetchQueryBuilderTest.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/SortingIT.java
Resolves #1244
When creating query, check if pagination and ToMany relationship is present, if so add DISTINCT to query.
See the issue
Unit tests
> Fixes #1244: Incorrect pagination with ToMany filtering

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/AggregationDataStoreTransaction.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/EntityProjectionTranslator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/QueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/QueryValidator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/ColumnProjection.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/MetricProjection.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/TimeDimensionProjection.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLQueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLMetric.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLReferenceTable.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLColumnProjection.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLMetricProjection.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLQueryConstructor.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLQueryTemplate.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLTimeDimensionProjection.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/EntityProjectionTranslatorTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/framework/SQLUnitTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/QueryEngineTest.java
Cleanup of AggregationDataStore SQL Generation logic.
1. ColumnProjection and subclasses are solely responsible for generating SQL for a column reference.
2. ColumnProjection and subclasses use the SQLReferenceTable to expand columns to SQL fragments.
3. Metrics and dimensions can now support dynamic SQL generation through client provided parameters.
The SQL generation logic was fragmented in different places.  This consolidates it into a single abstraction.
> Remove path logic from aggregation store

- elide-datastore/elide-datastore-inmemorydb/pom.xml
- elide-datastore/elide-datastore-jpa/pom.xml
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/FilterIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/GenerateIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/PaginateIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/ResourceIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/SortingIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/UserTypeIT.java
Runs elide-integration-tests against the in-memory store.
InMemoryStore should be a first class citizen and run all IT tests.
Runs all IT tests (except the ones where there are known problems).
> Added InMemoryStore to list of datastores that run IT tests

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Table.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/AggregationDataStoreIntegrationTest.java
Add TimeDimensions as an attribute to the Aggregation Store Table.
Time Dimension is not present in AggregationStore Table endpoint's schema. This is a concept defined in the metadata rfc. https://www.github.com/yahoo/elide/issues/1005
i) Existing test cases passed
ii) The test case was updated.
NA
> Elide-5.x Add TimeDimensions to AggregationStore table

- elide-core/src/test/java/com/yahoo/elide/core/LifeCycleTest.java
Added additional Elide lifecycle tests using Patch Extension
Test coverage
Unit testing
> Patch Extension Lifecycle tests

- elide-core/src/main/java/com/yahoo/elide/request/Argument.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Column.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Dimension.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Metric.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Table.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/TimeDimension.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/TimeDimensionGrain.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/ColumnProjection.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/Query.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLMetricProjection.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLTimeDimensionProjection.java
Make sure classes used in queries have correct equals/hashCode implementations, using Lombok if possible.
`Query` has `Set<ColumnProjection>` and `Set<TimeDimensionProjection>` fields, but for those sets to work as expected, `ColumnProjection` and `TimeDimensionProjection` need to implement equals/hashCode correctly, as well as classes held by those classes and their superclasses.
UTs are passing.
> Implement equals/hashCode and immutability where needed

- elide-core/src/main/java/com/yahoo/elide/core/EntityBinding.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
- elide-core/src/test/java/com/yahoo/elide/core/EntityDictionaryTest.java
Elide currently injects every model it manages.  This can be costly for large collections loaded from a database - especially if those models don't actually require injection.
This PR changes Elide to only inject models that are decorated with `@Inject`.
Performance improvement for loading large collections.
UT tests.
> Changes elide to only inject models annotated with @Inject

- elide-graphql/src/main/java/com/yahoo/elide/graphql/PersistentResourceFetcher.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/GraphQLIT.java
Resolves - Could not find any related issues
The GraphQL interface has a bug related to filtering values through a many-to-many relationship. An example of a broken filter would be `books.title=="1984"` on a request for the author object from the UT and integration test model. The books set in the author entity is a many-to-many relationship to the book entity. The filter fails to parse due to type errors since the `MultipleFilterDialect. parseTypedExpression` method does not properly handle parsing the nested types. 
The solution is to attempt to parse with the `MultipleFilterDialect.parseGlobalExpression` similar to the existing solution in the JsonAPI interface in `RequestScope`.
This bug unnecessarily limits how our UI can query the GraphQL endpoint.
I have added multiple integration …
> GraphQL Many-to-many filter Bug Fix

- elide-core/src/main/java/com/yahoo/elide/core/VerifyFieldAccessFilterExpressionVisitor.java
- elide-core/src/main/java/com/yahoo/elide/security/PermissionExecutor.java
- elide-core/src/test/java/com/yahoo/elide/core/LifeCycleTest.java
- elide-core/src/test/java/com/yahoo/elide/core/VerifyFieldAccessFilterExpressionVisitorTest.java
Allow customizing the enforcement of ReadPermission for filter joins added with:
`Enforce ReadPermission for filter joins` #1236
Provides the ability to allow special handling of the permission enforcement with a customized PermissionExecutor.  This can also disable enforcement for optimizing the queries.
To customize, create a custom PermissionExecutor and implement the new methods:
* **evaluateFilterJoinUserChecks**: customize processing checks in the filterexpression
* **handleFilterJoinReject**: customize handling of a rejected field in a filter
Also fixed a bug in the user check shortcut optimization.  If any check was deferred, it stopped looking for a failing user check and fell through to scanning the objects.  Now if any fails, the short cut fails.  If all are pass, the short cut …
> Allow customizing the handling of ReadPermission for filter joins

- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/AbstractHibernateStore.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateEntityManagerStore.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateSessionFactoryStore.java
- elide-datastore/elide-datastore-hibernate5/src/test/java/com/yahoo/elide/datastores/hibernate5/HibernateEntityManagerDataStoreHarness.java
Fixes ancient bug in legacy HIbernate 5 entity manager store.
Hibernate entity manager store recycles the entity manager - which is not thread safe.
IT tests including async tests which catch this.
> Fix hibernate entity manager store threading issue.

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/AggregationDataStoreTransaction.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/QueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/Cache.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/AbstractEntityHydrator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLEntityHydrator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLQueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/annotation/dimensionformula/DimensionFormulaTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/annotation/metricformula/MetricFormulaTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/framework/AggregationDataStoreTestHarness.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/framework/SQLUnitTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/QueryEngineTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SubselectTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/ViewTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java
Create an API for caching results of `QueryEngine.executeQuery`. The user will provide a `Cache` object (via bean for `buildQueryEngine` or otherwise) that implements a trivial API. Then QueryEngine implementations can use that cache for caching results. The `executeQuery` is given an additional argument to allow for cache bypass.
It is the responsibility of the QueryEngine implementation to generate a cache key from the given query. For example, SQLQueryEngine could use the SQL query string, combined with a table versioning token, as the key. To ensure a good hit rate implementations must ensure that they normalize the data used as the key, so that variations in the query that don't affect the results don't change the key.
Originally I was planning to use the Query object directly in key …
> QueryEngine result cache

- elide-datastore/elide-datastore-hibernate3/pom.xml
- elide-datastore/elide-datastore-hibernate5/pom.xml
- elide-datastore/elide-datastore-search/pom.xml
- elide-datastore/pom.xml
- elide-example/elide-blog-example-resteasy/pom.xml
- elide-integration-tests/pom.xml
- elide-spring/elide-spring-boot-autoconfigure/pom.xml
- elide-spring/elide-spring-boot-starter/pom.xml
- elide-standalone/pom.xml
- pom.xml
Build is failing because OWASP started flagging dom4j dependency as a security issue.
This PR is intended to upgrade necessary dependencies to resolve the build failure.
> Fixing Dom4J Owasp Build Failure (by upgrading hibernate 5)

- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/AbstractHQLQueryBuilder.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/RootCollectionPageTotalsQueryBuilder.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/SubCollectionPageTotalsQueryBuilder.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/SubCollectionFetchQueryBuilderTest.java
When Elide fetch joins toOne relationships, it can overlap with a join because of a filter expression resulting in two joins.  This complicates the SQL and reduces performance.
Updated unit tests.
> Removed redundant fetch join for filters

- CONTRIBUTING.md
- elide-contrib/elide-test-helpers/src/test/java/com/yahoo/elide/contrib/testhelpers/jsonapi/JsonApiDSLTest.java
- elide-core/src/main/java/com/yahoo/elide/audit/LogMessage.java
- elide-core/src/test/java/com/yahoo/elide/security/PermissionExecutorTest.java
- elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/AbstractHibernateStore.java
- elide-eclipse.importorder
- elide-example/elide-blog-example/src/test/java/com/yahoo/elide/example/ExampleTest.java
- elide-example/elide-blog-example/src/test/java/com/yahoo/elide/example/IntegrationTest.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/GraphQLEndpointTest.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/GraphQLIT.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideStandaloneSettings.java
- elide-standalone/src/test/java/com/yahoo/elide/standalone/ElideStandaloneTest.java
Add Eclipse import order.
To help maintain import order when using Eclipse IDE.
With Eclipse IDE ran Organize Imports on entire project.
> Add Eclipse import order

- elide-async/src/main/java/com/yahoo/elide/async/models/AsyncQuery.java
- elide-async/src/main/java/com/yahoo/elide/async/models/AsyncQueryResult.java
- elide-async/src/main/java/com/yahoo/elide/async/service/AsyncQueryDAO.java
- elide-async/src/main/java/com/yahoo/elide/async/service/DefaultAsyncQueryDAO.java
- elide-async/src/test/java/com/yahoo/elide/async/service/DefaultAsyncQueryDAOTest.java
- elide-contrib/elide-dynamic-config-helpers/pom.xml
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java
Async ID change from UUID to String to avoid database incompatibility errors for casting UUID to string.
Fixes issue in Dynamic Model config
Deployment errors with Postgres on heroku
Unit Test successful. 
> Async ID change from UUID to String and Dynamic Config FIx

- elide-core/src/main/java/com/yahoo/elide/core/pagination/PaginationImpl.java
- elide-core/src/main/java/com/yahoo/elide/request/Pagination.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/AggregationDataStoreTransaction.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/EntityProjectionTranslator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/QueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/Cache.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/ImmutablePagination.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/Query.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/QueryResult.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/AbstractEntityHydrator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLEntityHydrator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLQueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/QueryEngineTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SubselectTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/ViewTest.java
Currently QueryEngine.execute takes a Query as input and returns an iterable list of results as output. However, the Query can contain a mutable Pagination object which may be modified by `execute` to contain the page total. This complicates caching, since we want a single result object to cache. So for the purposes of QueryEngine, we make the Pagination used by Query immutable, and `execute` now returns a QueryResult which contains both the result data and the page total metadata.
Other caching-related changes:
- Polish Pagination/PaginationImpl - many fields do not need to be nullable or non-final, and they were not making full use of Lombok.
- Consolidate the bypassCache flag into the Query object
- Don't use a stub cache implementation when caching is disabled. When caching is not …
> Introduce QueryResult class for QueryEngine caching

- elide-example/elide-blog-example-resteasy/pom.xml
- elide-spring/elide-spring-boot-autoconfigure/pom.xml
maven build failed due to the below package not meeting CVSS score requirement. 
* resteasy-jaxrs
* tomcat-embed-core
After update, the local maven build succeeds. 
> update package whose cvss score raised above 7.0

- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/AbstractHQLQueryBuilder.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/RootCollectionFetchQueryBuilder.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/SubCollectionFetchQueryBuilder.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/AbstractHQLQueryBuilderTest.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/RootCollectionFetchQueryBuilderTest.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/SubCollectionFetchQueryBuilderTest.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/SortingIT.java
Resolves #920  (if appropriate)
Query with Sorting clause should have an explicit join clause and use its alias in order by clause. 
The implicit JPA join uses an inner join to fetch the relationship entity. We want JPA to perform left join to preserve all response records.
Unit test
IT test
> add explicit join

- elide-async/src/main/java/com/yahoo/elide/async/service/AsyncQueryInterruptThread.java
- elide-async/src/main/java/com/yahoo/elide/async/service/DefaultAsyncQueryDAO.java
- elide-async/src/test/java/com/yahoo/elide/async/service/AsyncQueryThreadTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideDynamicConfiguration.java
- elide-spring/elide-spring-boot-starter/pom.xml
i) Added `@ConditionalOnMissingBean` to `entityManagerFactory` method in Dynamic Config Configuration to allow overriding of the bean. 
ii)  `executeInTransaction` will throw a RuntimeException when IOException happens and not ignore the other exceptions too. 
i) If we want to override the entityManagerFactory Bean in one of our implementations, we need to have the annotation.
ii) The AsyncIT test fails intermittently with `Expected: asyncQueryResult Actual: null` error. The only possible scenario this could happen is if the AsyncQueryResult object was not persisted properly. 
Existing test case pass. 
> Miscellanous fix

- elide-contrib/elide-dynamic-config-helpers/src/main/java/com/yahoo/elide/contrib/dynamicconfighelpers/parser/handlebars/HandlebarsHydrator.java
- elide-contrib/elide-dynamic-config-helpers/src/main/resources/templates/table.hbs
- elide-contrib/elide-dynamic-config-helpers/src/test/java/com/yahoo/elide/contrib/dynamicconfighelpers/parser/handlebars/HandlebarsHydratorTest.java
- elide-datastore/elide-datastore-multiplex/src/main/java/com/yahoo/elide/datastores/multiplex/MultiplexTransaction.java
- elide-datastore/elide-datastore-multiplex/src/main/java/com/yahoo/elide/datastores/multiplex/MultiplexWriteTransaction.java
- elide-datastore/elide-datastore-multiplex/src/test/java/com/yahoo/elide/datastores/multiplex/MultiplexTransactionTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java
i) Lazy Initialization of transactions in Multiplex Transaction
ii) Handlebars escaping now limited to quotes, new line.  
Multiplex Transaction was committing all the transactions since they were initialized even though they were not used. This resuled in transaction not in progress errors.
Sqls have < , > etc which can not be escaped
Existing test cases pass. 
> Multiplex Transaction Lazy Initialize and Dynamic Config fixes

- elide-core/src/main/java/com/yahoo/elide/utils/coerce/converters/OffsetDateTimeSerde.java
- elide-core/src/main/java/com/yahoo/elide/utils/coerce/converters/TimeZoneSerde.java
- elide-core/src/test/java/com/yahoo/elide/utils/coerce/converters/TimeZoneTest.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/TimeDimension.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/GraphQLConversionUtilsTest.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/GraphQLScalarsTest.java
Add Serde for TimeZone that converts TimeZone into a scalar type (instead of a Java object) 
TimeZone shows up as an object in swagger and we want it to show as a scalar value
Tested in Spring boot example project
> CARBON-212 TimeZone Serde

- elide-spring/elide-spring-boot-autoconfigure/README.md
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/models/aggregation/Stats.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/AggregationStoreTest.java
Add test for Spring integration, checking that default configuration enables the Caffeine query cache, which should then publish metrics.
> Fixes for query cache spring integration

- elide-core/src/main/java/com/yahoo/elide/core/EntityBinding.java
Fix: Check for null super in `getInheritedTypes`
NPE
At application level
n/a
> Fix: Check for null super in `getInheritedTypes`

- elide-async/src/main/java/com/yahoo/elide/async/hooks/ExecuteQueryHook.java
- elide-async/src/main/java/com/yahoo/elide/async/models/AsyncBase.java
- elide-async/src/main/java/com/yahoo/elide/async/models/AsyncQuery.java
- elide-async/src/main/java/com/yahoo/elide/async/models/security/AsyncQueryOperationChecks.java
- elide-async/src/main/java/com/yahoo/elide/async/service/AsyncExecutorService.java
- elide-async/src/test/java/com/yahoo/elide/async/service/AsyncQueryTest.java
- elide-integration-tests/src/test/java/com/yahoo/elide/async/integration/tests/AsyncIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/async/integration/tests/framework/AsyncIntegrationTestApplicationResourceConfig.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAsyncConfiguration.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideResourceConfig.java
i) Moved Async execute query hook to onReadPreSecurity Hook.
ii) Had to tweak the logic for values updated using `@PrePersist` annotation as they were overriding the values set in onReadPreSecurity hook.
iii) A fix for potential NPE in Async Models Operation Check.
AsyncQuery submitted through Graphql end-point with asyncAfterSeconds 10 still comes back with embeddable results as null even though it finished before 10 seconds.
Based on debugging, its happening cos of [this](https://github.com/yahoo/elide/blob/d4901c6f07e57aa179c5afd640c9c67e90a8cdaf/elide-graphql/src/main/java/com/yahoo/elide/graphql/QueryRunner.java#L190). In GraphQL, the only part of the body that is lazily returned is the ID
Existing test cases passed.
Modified Graphql tests for Async
Verified that the example code …
> Async change to use onReadPreSecurity Hook

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/resources/JsonApiEndpoint.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/controllers/JsonApiController.java
Resolves #1410
See issue for details
query parameters currently not accessible from request scope when processing POST, PATCH or DELETE operations.
> add queryParams variants for post(), patch() and delete()

- README.md
The old code isn't valid Java. It has a stray `)` and isn't formatted correctly. Thus fix it.
Viewing without white space should make things easier
It bothered me when reading an otherwise very nice readme.
Doesn't have issues when pasted into IntelliJ
> [README] - Fix the standalone README Java sample

- elide-integration-tests/src/test/java/com/yahoo/elide/async/integration/tests/AsyncIT.java
- elide-spring/elide-spring-boot-autoconfigure/pom.xml
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/AsyncTest.java
- elide-standalone/src/test/java/example/ElideStandaloneTest.java
Async Tests will now exit the status check loop when failed.
Status check loop will continue till the iterations were exhausted even though query had failed.
> Elide 5.x - Async Tests, Break loop when fail

- elide-async/src/main/java/com/yahoo/elide/async/models/AsyncQuery.java
- elide-async/src/main/java/com/yahoo/elide/async/models/security/AsyncQueryOperationChecks.java
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/AnyFieldExpression.java
- elide-integration-tests/src/test/java/com/yahoo/elide/async/integration/tests/AsyncIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/async/integration/tests/framework/AsyncIntegrationTestApplicationResourceConfig.java
- elide-integration-tests/src/test/java/example/NoCommitEntity.java
- elide-integration-tests/src/test/resources/ResourceIT/testPatchExtNoCommit.req.json
Adding create permission check in AsyncQuery to make sure QueryStatus is set to Queued.
Changed PersistentResource to only do USER CHECKS when creating a new object.
ExecuteQueryHook.java has a check to trigger when the query status is Queued. 
Existing test cases pass.
New Test case is added. 
> Elide 5.x Async Create Permission Fix

- elide-core/src/main/java/com/yahoo/elide/core/filter/Operator.java
Resolves #683
Fix processing of collection in operator getFieldValue
Return a set of values instead of a set of lists.
Unit testing in Elide 5 exposed the error and ported to Elide 4
> Process collection in operator getFieldValue

- elide-core/src/main/java/com/yahoo/elide/utils/coerce/converters/InstantSerde.java
- elide-core/src/main/java/com/yahoo/elide/utils/coerce/converters/OffsetDateTimeSerde.java
- elide-core/src/test/java/com/yahoo/elide/utils/coerce/converters/InstantSerdeTest.java
- elide-core/src/test/java/com/yahoo/elide/utils/coerce/converters/OffsetDateTimeTest.java
Avoid "500 Internal Server Error" responses by handling DateTimeParseException.
Current OffsetDateTime and Instant (de)serializers can raise the JAVA standard `DateTimeParseException` if the value passed in is of an incorrect format.
This can cause a 500 Internal Server error to occur when invalid values are passed in via a REST API.
```json
500 Internal Server Error
{
"timestamp": "2020-07-13T11:36:07.924+00:00",
"status": 500,
"error": "Internal Server Error",
"message": "Text '2020-07-10T11:19:52+0200' could not be parsed, unparsed text found at index 22",
"path": "/pwStats"
}
```
We convert the exception into an `IllegalArgumentException` which the CoreceUtil class handles.
```json
400 Bad Request
{
"errors": [
{
"detail": "InvalidValueException: Invalid value: …
```
> Convert DateTimeParseException into IllegalArgumentException

- elide-core/src/main/java/com/yahoo/elide/audit/AuditLogger.java
- elide-core/src/main/java/com/yahoo/elide/audit/Slf4jLogger.java
- elide-core/src/test/java/com/yahoo/elide/audit/TestAuditLogger.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-integration-tests/src/test/java/com/yahoo/elide/audit/InMemoryLogger.java
The current `AuditLogger` current uses a `ThreadLocal<>` generic as a data member.
Given that typically there is only a single instance of an `AuditLogger`, this shouldn't cause a resource leak, however the documentation for [`ThreadLocal`](https://docs.oracle.com/javase/8/docs/api/java/lang/ThreadLocal.html) makes a strong suggestion that 
> ThreadLocal instances are typically private static fields in classes that wish to associate state with a thread (e.g., a user ID or Transaction ID).
This PR simply updates the implementation to make this a static field, as per the recommendation.
As part of the static analysis of one of our projects, that uses the Elide library, we have a possible "singleton race condition" which has been raised via bytecode analysis, which suggests our usage of  the …
> make ThreadLocal usage static as per recommendations

- elide-spring/elide-spring-boot-autoconfigure/pom.xml
- elide-spring/elide-spring-boot-starter/pom.xml
- elide-spring/pom.xml
Resolves #1116
Use Spring Dependency Management
see #1116. By using spring boot dependencies we won't have to provide versions for all the dependencies in autoconfigure and starter repo. 
Existing test case pass
Spring Example Code runs fine.
> Using spring's dependency management

- elide-async/src/main/java/com/yahoo/elide/async/models/AsyncQuery.java
- elide-async/src/main/java/com/yahoo/elide/async/models/security/AsyncQueryInlineChecks.java
- elide-integration-tests/src/test/java/com/yahoo/elide/async/integration/tests/AsyncIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/async/integration/tests/framework/AsyncIntegrationTestApplicationResourceConfig.java
Authored-by: rishi-aga
Make Async Model Read/Update Permissions open to Admin Role.
Make Async Model Read/Update Permissions open to Admin for the usage stats dashboard. Currently, only the query submitter can read/update the query. Update permissions are needed to cancel the query. 
Included Integration tests for added functionality
Existing Tests Pass
> Open Async Model Read/Update Permissions to Admin

- elide-graphql/src/main/java/com/yahoo/elide/graphql/PersistentResourceFetcher.java
Using Graphql fragments in debug mode gave error, `graphql.language.FragmentSpread cannot be cast to graphql.language.Field`. The error was caused by assuming the type is always Field during the getName operation. Put in a cast by checking the class before calling getName. 
Resolving Error 
Tested with the app that was failing.
> Fix for Graphql Fragment Error in Debug Mode - Elide 4.x

- elide-graphql/src/main/java/com/yahoo/elide/graphql/PersistentResourceFetcher.java
Using Graphql fragments in debug mode gave error, `graphql.language.FragmentSpread cannot be cast to graphql.language.Field`. The error was caused by assuming the type is always Field during the getName operation. Put in a cast by checking the class before calling getName. 
Resolving Error 
Tested with the app that was failing.
> Fix for Graphql Fragment Error in Debug Mode 

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLTimeDimensionProjection.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/example/PlayerStats.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/AggregationDataStoreIntegrationTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/resources/models/tables/playerStats.hjson
Authored-by: rishi-aga
Resolves https://github.com/yahoo/elide/issues/1398
Replace use of %s in TimeDimension to use handlebar {{}}
Please refer https://github.com/yahoo/elide/issues/1398
Existing Tests Pass
> Replace use of %s in TimeDimension to use handlebar {{}}

- elide-standalone/src/test/resources/logback.xml
- xml.header
Elide standalone has the most logging during builds (about half of the build).  This is an attempt to reduce that build logging.
> Reduce Standalone Logging

- elide-graphql/src/main/java/com/yahoo/elide/graphql/parser/GraphQLEntityProjectionMaker.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/parser/GraphQLEntityProjectMakerTest.java
This change enforces default pagination when running GraphQL queries.
GraphQL queries are not enforcing pagination if `first` or `after` arguments are not used. This results in large queries returning all the records which can cause the JVM to throw errors.
Sample Application was tested. 
> Graphql Query Default Pagination Setup

- elide-datastore/elide-datastore-search/src/test/resources/META-INF/persistence.xml
- elide-example/elide-blog-example/src/test/java/com/yahoo/elide/example/IntegrationTest.java
- elide-standalone/src/test/java/com/yahoo/elide/standalone/ElideStandaloneTest.java
- pom.xml
H2 deprecated the MVCC setting in version 1.4.198
https://github.com/h2database/h2database/releases/tag/version-1.4.198
This was removed entirely in 1.4.200 and use will now cause an error.
https://github.com/h2database/h2database/releases/tag/version-1.4.200
Required to upgrade H2
Unit and IT tests
> H2 MVCC setting is removed

- elide-contrib/elide-dynamic-config-helpers/src/main/java/com/yahoo/elide/contrib/dynamicconfighelpers/model/Table.java
- elide-contrib/elide-dynamic-config-helpers/src/main/resources/elideTableSchema.json
- elide-contrib/elide-dynamic-config-helpers/src/test/resources/models/tables/table3.hjson
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/annotation/FromSubquery.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/annotation/FromTable.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/annotation/VersionQuery.java
Co-authored-by: AvaniMakwana
FromTable and FromSubquery annotations are now inheritable when models will be extended. Schema is updated according to that. Also `extends` errors out as a keyword during JSON Validation, changed to `extend`.
Schema Verification Failures
Updated Test cases.
> Fixing the schema for Extend in Dynamic Config

- elide-contrib/elide-test-helpers/src/main/java/com/yahoo/elide/contrib/testhelpers/graphql/GraphQLDSL.java
- elide-contrib/elide-test-helpers/src/main/java/com/yahoo/elide/contrib/testhelpers/graphql/elements/Field.java
- elide-contrib/elide-test-helpers/src/test/java/com/yahoo/elide/contrib/testhelpers/graphql/GraphQLDSLTest.java
GraphQL test helper should escape any quotes when quoting the string.
GraphQL tests are failing for JSON strings.
Unit testing.  Local product testing with the fix.
> escape quotes in quoted strings

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/dialects/AbstractSqlDialect.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/dialects/SQLDialect.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/dialects/impl/PrestoDialect.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLQueryConstructor.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/PrestoExplainQueryTest.java
Resolves CARBON-258
Use an alias in order by clause for PRESTO
Order by for aggregated metric works only if the alias is mentioned in the query.
Unit test
> use alias for order by

- elide-core/src/main/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialect.java
- elide-core/src/test/java/com/yahoo/elide/core/VerifyFieldAccessFilterExpressionVisitorTest.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialectTest.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialectWithFIQLCompliantStrategyTest.java
- elide-core/src/test/java/com/yahoo/elide/jsonapi/EntityProjectionMakerTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/cache/QueryKeyExtractorTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/H2ExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/HiveExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/PrestoExplainQueryTest.java
- elide-datastore/elide-datastore-search/src/test/java/com/yahoo/elide/datastores/search/DataStoreLoadTest.java
- elide-datastore/elide-datastore-search/src/test/java/com/yahoo/elide/datastores/search/SearchDataStoreITTest.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/FilterIT.java
RSQL default operations are made case sensitive. Case Insensitive Equality operators are added. 
`==` and `=in=` are now Case Sensitive
`=ini=` is the case insensitive equivalent.
**Usage** :
`=ini='val'` -> IN_INSENSITIVE
`=ini='*val'` -> PREFIX_CASE_INSENSITIVE
`=ini='*val*'` -> INFIX_CASE_INSENSITIVE
`=ini='val*'` -> POSTFIX_CASE_INSENSITIVE
`=in='val'` or `=='val'` -> IN
`=in='*val'` or `=='*val'` -> PREFIX
`=in='*val*'` or `=='*val*'` -> INFIX
`=in='val*'` or `=='val*'` -> POSTFIX
Having a default case insensitive filter bypasses the datastore index (if exist) thereby making queries slow. User needs to select whether they want CI or CS filter. 
Integration test and Unit Test
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary …
> Introduce case insensitive equality rsql operator. Default is case sensitive

- elide-core/src/main/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialect.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/filter/visitor/MatchesTemplateVisitor.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/filter/visitor/MatchesTemplateVisitorTest.java
First PR to add table filters for Aggregation Data Store
This PR adds the logic to validate whether a client filter conforms to a template filter.
> Table filter validations

- elide-async/src/main/java/com/yahoo/elide/async/models/AsyncQuery.java
- elide-async/src/main/java/com/yahoo/elide/async/models/AsyncQueryResult.java
- elide-async/src/main/java/com/yahoo/elide/async/models/ResultFormatType.java
- elide-async/src/main/java/com/yahoo/elide/async/models/ResultType.java
- elide-async/src/main/java/com/yahoo/elide/async/service/AsyncQueryThread.java
- elide-async/src/test/java/com/yahoo/elide/async/service/AsyncQueryTest.java
- elide-async/src/test/java/com/yahoo/elide/async/service/AsyncQueryThreadTest.java
- elide-integration-tests/src/test/java/com/yahoo/elide/async/integration/tests/AsyncIT.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/AsyncTest.java
- elide-standalone/src/test/java/example/ElideStandaloneTest.java
Resolves part of #1272
Update the Async Models, per the RFC-1272 to add ResultFormat and move ResultType to AsyncQuery Class instead of AsyncQueryResult
Refer #1272
Existing Tests pass. Test Cases have been updated.
> Data Export - Model Changes

- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/AbstractHQLQueryBuilder.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/RootCollectionFetchQueryBuilder.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/SubCollectionFetchQueryBuilder.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/AbstractHQLQueryBuilderTest.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/RootCollectionFetchQueryBuilderTest.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/SubCollectionFetchQueryBuilderTest.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/SortingIT.java
Resolves #1520
When resolving hibernate query add explicit joins based on sort paths
See issue
Just by debugging generated query.
I would like to do some unit/IT tests, but didn't figured how can I debug elide while running IT.
> Fixes #1520 by using explicit left join when sorting over relationships

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/test/java/com/yahoo/elide/core/LifeCycleTest.java
Calls to delete a resource erroneously read the resource relationships - resulting in life cycle hook invocations for reads.  This PR fixes the problem.
Calling a delete on a resource should not trigger a read life cycle hook.
Existing life cycle hook tests were updated.
> Delete Requests no longer trigger read life cycle hooks

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/NamedParamPreparedStatement.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/timegrains/DateTime.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/timegrains/MonthYear.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/timegrains/SimpleDate.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/timegrains/WeekDate.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/timegrains/Year.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/timegrains/YearMonth.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/timegrains/serde/DateTimeSerde.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/timegrains/serde/MonthYearSerde.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/timegrains/serde/SimpleDateSerde.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/timegrains/serde/WeekDateSerde.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/timegrains/serde/YearMonthSerde.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/timegrains/serde/YearSerde.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/AggregationDataStoreIntegrationTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/timegrains/serde/DateTimeSerdeTest.java
- elide-datastore/elide-datastore-aggregation/src/test/resources/configs/models/tables/SalesView.hjson
- elide-datastore/elide-datastore-aggregation/src/test/resources/prepare_SalesDB_tables.sql
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideStandaloneSettings.java
One of the multiple PRs that will resolve https://github.com/yahoo/elide/issues/1465
Update: Timegrain serde to return java.sql.Date instead of java.util.Date
Improve regex for Parameter name matching
After switching to use PreparedStatement, found an issue that java.sql.Date is not supported by PreparedStatement of PrestoDB driver https://github.com/prestodb/presto/blob/master/presto-jdbc/src/main/java/com/facebook/presto/jdbc/PrestoPreparedStatement.java. So updating Timegrain serdes to return java.sql.Date instead of java.util.Date
Existing Tests Pass
> Update timegrain serde to return java.sql.Date instead of java.util.Date

- elide-async/src/main/java/com/yahoo/elide/async/models/AsyncQuery.java
- elide-async/src/test/java/com/yahoo/elide/async/hooks/ExecuteQueryHookTest.java
- elide-async/src/test/java/com/yahoo/elide/async/service/AsyncQueryTest.java
Setting Default Value for Result Type in AsyncQuery
Setting Default Value for Result Type in AsyncQuery
Setting Default Value for Result Type in AsyncQuery
Existing Test Cases pass
> ResultType Default Value

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/AggregationDataStoreTransaction.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/cache/CaffeineCache.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/AggregationDataStoreTransactionTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/AggregationStoreProperties.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideConfigProperties.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/AggregationStoreTest.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideStandaloneSettings.java
PR adds a default item expiration to the Aggregation Data Store query cache.
The cache was only leveraged if a particular table supported a version query.  This change allows the cache to work in a more primitive context - simply based on item expiration.
Updated unit tests.
> Added item expiration to AggregationDataStore cache

- elide-core/src/main/java/com/yahoo/elide/jsonapi/EntityProjectionMaker.java
- elide-core/src/main/java/com/yahoo/elide/parsers/state/StartState.java
- elide-core/src/test/java/com/yahoo/elide/core/LifeCycleTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/MetaDataStoreIntegrationTest.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/FilterIT.java
There was a regression in Elide 5 where  `@Include(rootLevel=false)` was being ignored.  This PR fixes the regression.
> Elide 5 ignores rootLevel = false

- elide-async/src/main/java/com/yahoo/elide/async/export/TableExporter.java
- elide-async/src/test/java/com/yahoo/elide/async/export/TableExporterTest.java
Resolves #1272 
TableExporter Initial Version using PersistentResource.loadObjects(...)
#1272
Existing Test Case pass. New Test case added.
> Table Exporter:  Initial Version

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/annotation/CardinalitySize.java
Make the cardinality sizes consistent between dynamic config and data aggregation
Existing test cases
> enum change for cardinality size

- elide-core/src/main/java/com/yahoo/elide/core/Path.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialect.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/dialect/graphql/FilterDialect.java
- elide-core/src/main/java/com/yahoo/elide/core/sort/SortingImpl.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/parser/GraphQLEntityProjectionMaker.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/FetcherFetchTest.java
- elide-graphql/src/test/resources/graphql/requests/fetch/filterByAlias.graphql
- elide-graphql/src/test/resources/graphql/requests/fetch/sortByAlias.graphql
- elide-graphql/src/test/resources/graphql/responses/fetch/filterByAlias.json
- elide-graphql/src/test/resources/graphql/responses/fetch/sortByAlias.json
Adds plumbing to sort and filter by alias for GraphQL queries.
Also adds plumbing to pass along attribute arguments to later support parameterized attributes.
> Elide 5: Support sorting and filtering by alias in GraphQL

- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/framework/SQLUnitTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/H2ExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/HiveExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/PrestoExplainQueryTest.java
Some of the SQL generation tests include scenarios that are not supported by the query engine when the validator is used.  These tests are removed.
> Cleaned SQL Generation Tests

- elide-core/src/main/java/com/yahoo/elide/core/EntityBinding.java
- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
- elide-core/src/test/java/com/yahoo/elide/core/EntityBindingTest.java
- elide-core/src/test/java/com/yahoo/elide/core/EntityDictionaryTest.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/NonEntityDictionary.java
Cleans up the logic that extracts the model names in elide 5.
> Removed entity name from Entity Binding

- elide-async/src/main/java/com/yahoo/elide/async/hooks/CompleteQueryHook.java
- elide-async/src/main/java/com/yahoo/elide/async/hooks/ExecuteQueryHook.java
- elide-async/src/main/java/com/yahoo/elide/async/hooks/UpdatePrincipalNameHook.java
- elide-core/src/main/java/com/yahoo/elide/core/LifecycleHookInvoker.java
- elide-core/src/main/java/com/yahoo/elide/functions/LifeCycleHook.java
- elide-core/src/test/java/com/yahoo/elide/core/LifeCycleTest.java
- elide-core/src/test/java/example/PublisherUpdateHook.java
- elide-core/src/test/java/example/models/triggers/InvoiceCompletionHook.java
- elide-graphql/src/test/java/hooks/BookUpdatePostCommitHook.java
- elide-graphql/src/test/java/hooks/BookUpdatePreCommitHook.java
- elide-graphql/src/test/java/hooks/BookUpdatePreSecurityHook.java
- elide-integration-tests/src/test/java/example/models/triggers/InvoiceCompletionHook.java
Pass Transaction phase to LifeCycleHook Execute.
Pass Transaction phase to LifeCycleHook Execute. Will assist in cases where we want to have the same hook called during different phases with separate logic.
Existing Test Cases Pass.
> Pass Transaction phase to LifeCycleHook Execute.

- elide-core/src/main/java/com/yahoo/elide/request/EntityProjection.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/parser/FragmentResolver.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/parser/GraphQLEntityProjectionMaker.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/parser/VariableResolver.java
Replace javax.ws.rs.BadRequestException with com.yahoo.elide.core.exceptions.BadRequestException
GraphQL API was returning 400 error code instead of 200 for certain scenarios. 
Per https://elide.io/pages/guide/v4/11-graphql.html, GraphQL API should return 200 error code. So making the behavior consistent. 
Existing test case pass.
> Replace javax.ws.rs.BadRequestException with com.yahoo.elide.core.exceptions.BadRequestException

- elide-spring/elide-spring-boot-autoconfigure/pom.xml
- elide-spring/elide-spring-boot-starter/pom.xml
Add micrometer dependency to spring boot starter pom.xml
Applications that use Elide should not have to add micrometer dependency explicitly
Tested in an application that uses elide, by removing the explicitly added micrometer dependency from its pom.xml
> Add micrometer dependency

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/AggregationDataStoreTransaction.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/QueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/MetaDataStore.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLQueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/framework/SQLUnitTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/QueryEngineTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/ViewTest.java
Small cleanup for QueryEngine to remove a metadata method that belongs in the MetadataStore.
> Migrate metadatacalls to metadata store

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/annotation/TableMeta.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Table.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/example/Continent.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/MetaDataStoreIntegrationTest.java
- elide-spring/pom.xml
- pom.xml
Resolves https://github.com/yahoo/elide/issues/1544
Not all `@Table` and `@Subselect` Annotated Models satisfy the Analytics/Aggregated Model requirement. So we should be able to flag them.
* `@TableMeta` annotation introduces a new property `isFact` with default value 'true' which can be used to mark the flag. 
* `FromTable` and `FromSubquery` annotated models will always default to isFact = true unless marked otherwise. 
* `@Table` and `@Subselect` annotated models will always default to isFact = false unless marked otherwise. 
Not all `@table` and `@Subselect` Annotated Models satisfy the Analytics/Aggregated Model requirements. The UI will use the isFact flag to filter the non-supported models.
New and existing test cases work.
I confirm that this contribution is made under an Apache …
> New isFact flag for Analytical Models

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/timegrains/Hour.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/timegrains/Minute.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/timegrains/Second.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/AggregationDataStoreIntegrationTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/timegrains/serde/HourSerdeTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/timegrains/serde/MinuteSerdeTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/timegrains/serde/SecondSerdeTest.java
For consistency with default time formats in Elide. Include `T` date separator in the time dimension formats 
Existing test cases were updated.
> Include ISO `T` Date Separator in time dimension formats

- elide-model-config/README.md
- elide-spring/elide-spring-boot-autoconfigure/pom.xml
- elide-standalone/pom.xml
Generate shade jar to enable dynamic config validation from command line.
Command line validation of dynamic config hjson files
Tested command line validation of hjson files using the new shaded jars
> Generate shade jar to enable dynamic config validation from command line.

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Table.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/example/Planet.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/MetaDataStoreIntegrationTest.java
- elide-datastore/elide-datastore-aggregation/src/test/resources/prepare_tables.sql
Fixes the logic for isFlag property. Missing a case when it was set to false in TableMeta for FromTable and FromSubSelect Annotated models. 
Existing and New test cases.
> Bug Fix for missed case in isFlag logic

- elide-spring/elide-spring-boot-autoconfigure/pom.xml
- elide-standalone/pom.xml
Remove shade plugin
Remove shade plugin from elide spring and standalone maven pom config
> remove shade

- elide-standalone/README.md
Updated elide-standalone getting started docs for elide 5.  Added an analytic model to the example.
> Update elide standalone getting started docs

- elide-async/src/main/java/com/yahoo/elide/async/service/AsyncCleanerService.java
Changes the default run time for the Cleaner thread from 360 Minutes to 120 Minutes. The cleaner thread is responsible for updating the status of interrupted async queries (due to app crash or restart) to TIMEDOUT from PROCESSING. It is also responsible for cleaning up history. 
> Tweak Cleaner Thread Delays

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/dialects/SQLDialectFactory.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/dialects/impl/PostgresDialect.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/framework/SQLUnitTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/PostgresExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/PrestoDBExplainQueryTest.java
Postgres Dialect Support for Analytical Queries.
Renamed Presto classes to PrestoDB cos PrestoSQL will be different implementations.
Existing and new test cases.
> Postgres Dialect

- elide-standalone/src/main/java/com/yahoo/elide/standalone/Util.java
Default DataSource not reading all config params
Elide Standalone Example was not able to use the Hikari Pool Settings.
Standalone Example.
> Elide Standalone: Default DataSource not reading all config params

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Table.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/MetaDataStoreIntegrationTest.java
Added tests to ensure that relationships and complex attributes are excluded as column metadata for the MetadataStore.
> Add static metadata test

- elide-async/src/main/java/com/yahoo/elide/async/export/TableExporter.java
- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/core/datastore/DataStoreTransaction.java
- elide-core/src/main/java/com/yahoo/elide/core/datastore/inmemory/HashMapStoreTransaction.java
- elide-core/src/main/java/com/yahoo/elide/core/datastore/inmemory/InMemoryStoreTransaction.java
- elide-core/src/main/java/com/yahoo/elide/core/datastore/wrapped/TransactionWrapper.java
- elide-core/src/test/java/com/yahoo/elide/core/datastore/DataStoreTransactionTest.java
- elide-core/src/test/java/com/yahoo/elide/core/datastore/inmemory/InMemoryStoreTransactionTest.java
- elide-core/src/test/java/com/yahoo/elide/core/datastore/wrapped/TransactionWrapperTest.java
- elide-core/src/test/java/com/yahoo/elide/core/lifecycle/LifeCycleTest.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/MetaDataStoreTransaction.java
- elide-datastore/elide-datastore-multiplex/src/main/java/com/yahoo/elide/datastores/multiplex/MultiplexTransaction.java
- elide-datastore/elide-datastore-multiplex/src/test/java/com/yahoo/elide/datastores/multiplex/MultiplexTransactionTest.java
- elide-datastore/elide-datastore-multiplex/src/test/java/com/yahoo/elide/datastores/multiplex/bridgeable/BridgeableRedisStore.java
- elide-datastore/elide-datastore-search/src/main/java/com/yahoo/elide/datastores/search/SearchDataTransaction.java
- elide-datastore/elide-datastore-search/src/test/java/com/yahoo/elide/datastores/search/DataStoreSupportsFilteringTest.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/QueryRunner.java
- elide-model-config/src/test/java/com/yahoo/elide/modelconfig/validator/DynamicConfigValidatorTest.java
- suppressions.xml
Adds additional context parameters to DataStoreTransaction interfaces:
- precommit takes a RequestScope
- supportsFiltering, supportsSorting, and supportsPagination all take a request scope, an optional parent entity, and the entity projection.
The latter changes are required to implement an N+1 optimization.
> Add context to supports filtering

- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/DynamicConfigHelpers.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/validator/DynamicConfigValidator.java
Instantiate DynamicConfigSchemaValidator once instead of multiple times.
> Instantiate DynamicConfigSchemaValidator once instead of multiple times.

- elide-async/src/main/java/com/yahoo/elide/async/models/AsyncQueryResult.java
Use LOB for responseBody so that its not limited by varchar size.
Existing Test case and example App passed.
> LOB for ResponseBody

- elide-contrib/elide-swagger/src/main/java/com/yahoo/elide/contrib/swagger/SwaggerBuilder.java
- elide-contrib/elide-swagger/src/main/java/com/yahoo/elide/contrib/swagger/model/Data.java
- elide-contrib/elide-swagger/src/main/java/com/yahoo/elide/contrib/swagger/model/Datum.java
- elide-contrib/elide-swagger/src/main/java/com/yahoo/elide/contrib/swagger/property/Data.java
- elide-contrib/elide-swagger/src/main/java/com/yahoo/elide/contrib/swagger/property/Datum.java
- elide-contrib/elide-swagger/src/main/java/com/yahoo/elide/contrib/swagger/property/Relationship.java
- elide-contrib/elide-swagger/src/test/java/com/yahoo/elide/contrib/swagger/SwaggerBuilderTest.java
- pom.xml
- screwdriver.yaml
- suppressions.xml
For large APIs, the swagger builder has a N squared loop that slows down service boot.  
Faster boot time.
Existing unit tests plus profiling to measure the performance impact of before and after changes.
> Improve swagger doc creation time

- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java
- elide-swagger/src/main/java/com/yahoo/elide/swagger/SwaggerBuilder.java
- elide-swagger/src/main/java/com/yahoo/elide/swagger/model/Data.java
- elide-swagger/src/main/java/com/yahoo/elide/swagger/model/Datum.java
- elide-swagger/src/main/java/com/yahoo/elide/swagger/property/Data.java
- elide-swagger/src/main/java/com/yahoo/elide/swagger/property/Datum.java
- elide-swagger/src/main/java/com/yahoo/elide/swagger/property/Relationship.java
- elide-swagger/src/test/java/com/yahoo/elide/swagger/SwaggerBuilderTest.java
- pom.xml
- screwdriver.yaml
1. Swagger document is only constructed if the controller is enabled in Spring.
2. Fixed a number of bottlenecks during construction.
For large APIs (many models), the boot time was impacted by swagger document construction.
Existing unit tests plus manual profiling.
> Boost swagger boot time

- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideConfigProperties.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/JsonApiControllerProperties.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/com/yahoo/elide/spring/tests/ControllerTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/com/yahoo/elide/spring/tests/IntegrationTestSetup.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/resources/application.yaml
Makes turning on JSON-API links push button simple.
> Adding simple setting to enable JSON-API links

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/QueryTranslator.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/example/VideoGame.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/framework/SQLUnitTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/DruidExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/H2ExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/HiveExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/MySQLExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/PostgresExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/PrestoDBExplainQueryTest.java
- elide-datastore/elide-datastore-aggregation/src/test/resources/prepare_tables.sql
Resolves #1778
The JOIN SQL expression needs to be added whenever there is a dimension projection, metric projection, or time dimension that refers to a joined parameter in the Aggregation Store. 
The Aggregation Store currently only generates a JOIN SQL expression for columns that contain a join expression that are referenced in the client query dimensions, filter clauses, and sort clauses.
Metrics might also reference a column requiring a join leading to invalid SQL generation.
Unit test
> add join expression for all column projection including metrics

- elide-core/src/main/java/com/yahoo/elide/jsonapi/EntityProjectionMaker.java
- elide-core/src/test/java/com/yahoo/elide/jsonapi/EntityProjectionMakerTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/AggregationDataStoreIntegrationTest.java
Resolves #1779
Issue#1779 Invalid sparse fields should return 4xx
> Issue#1779 Invalid sparse fields should return 4xx

- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/AsyncProperties.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAsyncConfiguration.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ExportControllerProperties.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideResourceConfig.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideStandaloneAsyncSettings.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideStandaloneSettings.java
Bind TableExportHook at startup. Other properties update for Table Export.
Existing Tests Pass
> TableExportHook Binding

- elide-spring/elide-spring-boot-starter/README.md
- elide-spring/elide-spring-boot-starter/pom.xml
Removes Jetty from spring boot starter to allow other containers to be leveraged.
Elide should not pin the container.
Verified the spring boot example project launches and all tests pass.
> Removing jetty from spring boot starter

- elide-graphql/pom.xml
> Upgrading ant on elide-4.x for CVE security fix.

- elide-core/src/test/java/com/yahoo/elide/core/PersistenceResourceTestSetup.java
- elide-core/src/test/java/com/yahoo/elide/core/security/PermissionExecutorTest.java
- elide-core/src/test/java/example/FirstClassFields.java
- elide-core/src/test/java/example/FunWithPermissions.java
- elide-core/src/test/java/example/Parent.java
- elide-core/src/test/java/example/Post.java
- elide-core/src/test/java/example/Right.java
- elide-core/src/test/java/example/TestCheckMappings.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/package-info.java
- elide-datastore/elide-datastore-multiplex/src/test/java/com/yahoo/elide/example/beans/HibernateUser.java
- elide-datastore/elide-datastore-multiplex/src/test/java/com/yahoo/elide/example/hbase/beans/RedisActions.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/GraphQLTest.java
- elide-integration-tests/src/test/java/example/AuditEntity.java
- elide-integration-tests/src/test/java/example/AuditEntityInverse.java
- elide-integration-tests/src/test/java/example/CreateButNoRead.java
- elide-integration-tests/src/test/java/example/CreateButNoReadChild.java
- elide-integration-tests/src/test/java/example/CreateButNoUpdate.java
- elide-integration-tests/src/test/java/example/FunWithPermissions.java
- elide-integration-tests/src/test/java/example/NoCommitEntity.java
- elide-integration-tests/src/test/java/example/NotIncludedResource.java
- elide-integration-tests/src/test/java/example/OneToOneNonRoot.java
- elide-integration-tests/src/test/java/example/OneToOneRoot.java
- elide-integration-tests/src/test/java/example/Parent.java
- elide-integration-tests/src/test/java/example/Post.java
- elide-integration-tests/src/test/java/example/ResourceWithInvalidRelationship.java
- elide-integration-tests/src/test/java/example/SpecialRead.java
- elide-integration-tests/src/test/java/example/TestCheckMappings.java
- elide-integration-tests/src/test/java/example/YetAnotherPermission.java
Add permissions on Metadatastore models to make them read-only.
Add permissions on Metadatastore models to make them read-only.
> Metadatastore Models Permission

- elide-async/src/main/java/com/yahoo/elide/async/export/validator/NoRelationshipsProjectionValidator.java
- elide-async/src/main/java/com/yahoo/elide/async/export/validator/SingleRootProjectionValidator.java
- elide-async/src/main/java/com/yahoo/elide/async/export/validator/Validator.java
- elide-async/src/main/java/com/yahoo/elide/async/operation/GraphQLTableExportOperation.java
- elide-async/src/main/java/com/yahoo/elide/async/operation/JSONAPITableExportOperation.java
- elide-async/src/main/java/com/yahoo/elide/async/operation/TableExportOperation.java
- elide-async/src/test/java/com/yahoo/elide/async/models/ArtifactGroup.java
- elide-async/src/test/java/com/yahoo/elide/async/models/ArtifactProduct.java
- elide-async/src/test/java/com/yahoo/elide/async/operation/GraphQLTableExportOperationTest.java
- elide-async/src/test/java/com/yahoo/elide/async/operation/JsonAPITableExportOperationTest.java
Validators for JSON and Graphql Exporter
> Validators for JSON and Graphql Exporter

- elide-core/src/main/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialect.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/dialect/jsonapi/DefaultFilterDialect.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/dialect/DefaultFilterDialectTest.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialectTest.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/QueryTranslator.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/filter/FilterTranslator.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/filter/HasMemberJPQLGenerator.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/AbstractHQLQueryBuilder.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/RootCollectionFetchQueryBuilder.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/RootCollectionPageTotalsQueryBuilder.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/SubCollectionFetchQueryBuilder.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/hibernate/hql/SubCollectionPageTotalsQueryBuilder.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/core/filter/FilterTranslatorTest.java
- elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/core/filter/HasMemberJPQLGeneratorTest.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/FilterIT.java
Resolves #1822
Add support for 'hasmember' queries that traverse to-many relationships like:
`/item?filter=tags.id=hasmember='new';tags.id=hasmember='sale'`
See #1822 
New operator unit tests, dialect unit tests, and JSON-API integration tests.
> Add 'hasmember' operator support across to-many relationships.

- elide-integration-tests/src/test/java/com/yahoo/elide/async/integration/tests/TableExportIT.java
Removing system.out from TableExport
> Removing system.out from TableExport

- elide-standalone/pom.xml
- pom.xml
> Removing mysql connector as a dependency (no longer needed)

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/filter/visitor/MatchesTemplateVisitor.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/filter/visitor/MatchesTemplateVisitorTest.java
MatchesTemplateVisitor.TEMPLATE_REGEX is wrong and we should also allow {{}} for substitution.
> Fixing the regular expression for required filter templates

- elide-integration-tests/src/test/java/com/yahoo/elide/async/integration/tests/AsyncDelayDataStore.java
- elide-integration-tests/src/test/java/com/yahoo/elide/async/integration/tests/AsyncDelayStoreTransaction.java
- elide-integration-tests/src/test/java/com/yahoo/elide/async/integration/tests/AsyncIT.java
Cleanup Delay Logic in the AsyncIT.java
Pass the delay through request headers instead of constructor args.
Existing test cases pass.
> Async IT cleanup

- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/Config.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/DynamicConfigHelpers.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/validator/DynamicConfigValidator.java
It seems getResources function requires unix style path on windows.
So `resolver.getResources("file:C:\\<configDir>\\**\\*.hjson")` doesn't work on Windows but `resolver.getResources("file:C:/<configDir>/**/*.hjson")` works
> Fix Config Path to work correctly with Windows

- screwdriver.yaml
Elide build has no build pipelines so effectively there is no [cache](https://docs.screwdriver.cd/user-guide/configuration/build-cache.html).
Build optimization.
Building
> use pipeline cache

- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/controllers/ExportController.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/AsyncDisableExportControllerTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/DisableExportControllerTest.java
Currently Spring Export Controller is disabled when Export is disabled. Additional condition is added to make sure to check if Async is enabled or not. 
If Async is disabled and export is enabled, it shouldn't launch the export controller as it can not be used without async components.
New test cases have been added.
> Export Controller Disable on Async Disabled or Export Disabled

- pom.xml
Update jetty
Pass CVE checks
Unit testing
> bump jetty to 9.4.38.v20210224 for CVE-2020-27223

- elide-async/src/main/java/com/yahoo/elide/async/operation/AsyncAPIUpdateOperation.java
- elide-async/src/main/java/com/yahoo/elide/async/service/AsyncExecutorService.java
- elide-async/src/main/java/com/yahoo/elide/async/service/dao/DefaultAsyncAPIDAO.java
- elide-async/src/main/java/com/yahoo/elide/async/service/thread/AsyncAPICancelRunnable.java
- elide-async/src/main/java/com/yahoo/elide/async/service/thread/AsyncAPICleanerRunnable.java
- elide-core/src/main/java/com/yahoo/elide/core/dictionary/EntityPermissions.java
- elide-integration-tests/src/test/java/com/yahoo/elide/async/integration/tests/AsyncDelayStoreTransaction.java
Always re-throw or re-interrupt when catching the `InterruptedException`.
When the final argument in a slf4j log message is a throwable, it generates a stack trace and is not one of the formatting arguments.
It appears the code had intended to display only the .toString based on the unused `{}`
> 05:46:51.561 [qtp135639164-244] ERROR c.y.e.a.service.AsyncExecutorService.executeQuery(AsyncExecutorService.java:96) - TimeoutException: {}
java.util.concurrent.TimeoutException: null
at java.util.concurrent.FutureTask.get(FutureTask.java:205)
at com.yahoo.elide.async.service.AsyncExecutorService.executeQuery(AsyncExecutorService.java:85)
at com.yahoo.elide.async.hooks.AsyncAPIHook.executeAsync(AsyncAPIHook.java:100)
at com.yahoo.elide.async.hooks.AsyncAPIHook.executeHook(AsyncAPIHook.java:67) …
> Correct exception logging

- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/verify/DynamicConfigVerifier.java
Resource Leak warning is shown in DynamicConfigVerifier by the IDE. Replacing with a try-resource block. Also adding a null check before calling close.
Resource Leak warning is shown in DynamicConfigVerifier by the IDE. 
Existing test case pass. IDE not showing the warning any more.
> try-resource block to avoid resource leak warnings

- elide-datastore/elide-datastore-inmemorydb/pom.xml
Removed the duplicate entry for dependency - javax.persistence-api in elide/elide-datastore/elide-datastore-inmemorydb/pom.xml
Removed duplicate entry for the dependency javax.persistence-api.
The build when ran was giving a warning 
**[WARNING] Some problems were encountered while building the effective model for com.yahoo.elide:elide-datastore-inmemorydb:jar:5.0.0-pr32-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: javax.persistence:javax.persistence-api:jar -> duplicate declaration of version 2.2 @ com.yahoo.elide:elide-datastore-inmemorydb:[unknown-version], elide/elide-datastore/elide-datastore-inmemorydb/pom.xml, line 73, column 21**
After removing this line, the warning did not show up when …
> Removed the duplicate entry for dependency - javax.persistence-api in 

- elide-core/src/main/java/com/yahoo/elide/core/dictionary/EntityBinding.java
- elide-core/src/main/java/com/yahoo/elide/core/dictionary/EntityDictionary.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/Operator.java
- elide-core/src/main/java/com/yahoo/elide/core/security/checks/Check.java
- elide-core/src/main/java/com/yahoo/elide/core/security/checks/FilterExpressionCheck.java
- elide-core/src/main/java/com/yahoo/elide/core/security/checks/OperationCheck.java
- elide-core/src/main/java/com/yahoo/elide/core/security/checks/UserCheck.java
- elide-core/src/main/java/com/yahoo/elide/core/security/executors/ActivePermissionExecutor.java
- elide-core/src/main/java/com/yahoo/elide/core/security/permissions/PermissionCondition.java
- elide-core/src/main/java/com/yahoo/elide/core/security/permissions/expressions/CheckExpression.java
- elide-core/src/test/java/com/yahoo/elide/core/lifecycle/LegacyTestModel.java
- elide-core/src/test/java/com/yahoo/elide/core/lifecycle/LifeCycleTest.java
- elide-core/src/test/java/com/yahoo/elide/core/security/PermissionExecutorTest.java
- elide-core/src/test/java/example/TestCheckMappings.java
- elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/filter/FilterTranslator.java
* Multiple legacy life cycle annotations can be on same method.
* Process "this" placeholder correctly in `FilterTranslator` and `Operator`
* Restore functionality previously available with CommitChecks using `runAtCommit` method in Check.
Fixing issues found in migrating from 4.x to 5.x
Unit testing.  Local testing with own Elide project.
> Refactor legacy hooks

- elide-async/src/main/java/com/yahoo/elide/async/export/formatter/JSONExportFormatter.java
- elide-async/src/main/java/com/yahoo/elide/async/service/AsyncExecutorService.java
- elide-integration-tests/src/test/java/com/yahoo/elide/async/integration/tests/AsyncApiIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/async/integration/tests/AsyncIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/async/integration/tests/TableExportIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/initialization/IntegrationTest.java
i) Cleanup and Refactor Async IT classes.
ii) Fix for Json Format Export not using an alias in the final output.
i) Refactoring.
ii) Fix for Alias.
Existing and new test cases pass.
> Refactor async IT and Fix for Alias in JSON Formatted Export

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/cache/QueryKeyExtractor.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/ColumnVisitor.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/FormulaValidator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Column.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Table.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/ColumnProjection.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/DefaultQueryPlanResolver.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/MetricProjection.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/QueryPlan.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/QueryPlanResolver.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLQueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLJoinVisitor.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLReferenceTable.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLReferenceVisitor.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLTable.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/QueryPlanTranslator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/QueryTranslator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLColumnProjection.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLDimensionProjection.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLMetricProjection.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLTimeDimensionProjection.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/cache/QueryKeyExtractorTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/core/SqlReferenceVisitorTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/AggregationDataStoreIntegrationTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/resolvers/DailyAverageScorePerPeriodResolver.java
Currently, `ColumnProjection` has a reference to the source `Query`.  This makes using the builder problematic because the association is bidirectional AND both `Query` and the projection classes are lombok `Value` classes (meaning they are immutable).
To make it easier to build queries, we are removing the source field in ColumnProjection (breaking the bi-directional association).
> Remove source from ColumnProjection

- elide-integration-tests/src/test/java/com/yahoo/elide/tests/FilterIT.java
> Added IT test for numeric value prefix, postfix, infix, and in operators

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLTimeDimensionProjection.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SubqueryFilterSplitter.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SubqueryFilterSplitterTest.java
This is part 2 of a new query plan optimizer for the Aggregation data store.
The goal is to rewrite queries of the form:
```
SELECT SUM(factTable.measure), factTable.dimensionA 
FROM factTable LEFT JOIN dimTableB 
ON factTable.dimensionB = dimTableB.id 
GROUP BY factTable.dimensionA
WHERE dimTableB.otherField > 0 AND factTable.anotherField = 0;
```
Into an optimized query like:
```
SELECT SUM(subquery.measure), subquery.dimensionA 
FROM 
(SELECT SUM(factTable.measure), factTable.dimensionA, factTable.dimensionB 
FROM factTable 
GROUP BY factTable.dimensionA, factTable.dimensionB 
WHERE factTable.anotherField = 0) subquery 
LEFT JOIN dimTableB 
ON subquery.dimensionB = dimTableB.id
GROUP BY subquery.dimensionA 
WHERE dimTableB.otherField > 0;
```
This phase adds the logic to split the …
> Query Plan Optimizer (Part 2)

- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ExportControllerProperties.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/JsonApiControllerProperties.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/SwaggerControllerProperties.java
Resolves #1904 
lombok's `@Data` annotation aggregates several functionalities. one is `@EqualsAndHashCode` 
in order to get rid of build warning in extending classes we should explicitly declare `@EqualsAndHashCode`, here with `(callSuper = true)`  option to also include fields from super class when implementing `hashCode()` and `equals()`
in this specific case - no applicative code was changed, so no tests (unless you'd like me to add tests for lombok functionality - not sure what is the agenda for such cases in this repo)
> issue 1904 - fix lombok build warnings

- elide-async/src/main/java/com/yahoo/elide/async/models/AsyncQuery.java
- elide-async/src/main/java/com/yahoo/elide/async/models/AsyncQueryResult.java
- elide-async/src/main/java/com/yahoo/elide/async/models/TableExport.java
- elide-async/src/main/java/com/yahoo/elide/async/models/TableExportResult.java
Resolves #1888
Lombok throws a warning when `@Data` annotation is used for classes that extends another because it generates equals/hashcode without the call to super. In this case, it is fixed by explicitly setting `@EqualsAndHashCode(callSuper = true)`
Verified that the warnings logged in the related issue no longer happen. I haven't added any additional tests to verify lombok's functionality, but please let me know if we need additional tests here.
> [HackTogether]Fix Lombok EqualsAndHashCode warnings

- elide-integration-tests/src/test/java/com/yahoo/elide/async/integration/tests/AsyncIT.java
- elide-integration-tests/src/test/java/com/yahoo/elide/async/integration/tests/TableExportIT.java
Random Async/TableExport IT failure fix when using Graphql with Non-zero Delay value in AsyncDelayStore.
i) Removed check on `status` column in the response when the request is posted.
TBD
Random Test Failures.
Existing test cases pass.
> Random Async/TableExport IT failure fix

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/core/JoinPath.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/ColumnVisitor.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/FormulaValidator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/MetaDataStore.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLJoin.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLJoinVisitor.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLReferenceTable.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLReferenceVisitor.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLTable.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SubqueryFilterSplitter.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/core/JoinPathTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/core/SqlReferenceVisitorTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLReferenceTableTest.java
Creates a new class, SQLJoin and adds a set of these to the SQLTable for join metadata.
All references throughout Elide where the Join annotation is referenced at query time have been replaced with the new SQLJoin class.
> Add join metadata to SQLTable.

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/jsonapi/parser/state/RelationshipTerminalState.java
I found this error while migrating to Elide 5. 
Fixes NPE if projection does not have permission for provided relationshipName.
NPE caused lookup errors.
Unit testing.  Local project testing.
> Projection may not have permission for relationshipName

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/QueryValidator.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/AggregationDataStoreIntegrationTest.java
Additional Validation to ensure the Grain Argument to a time-dimension in Filter Clause which gets pushed to a Having Filter matches the Grain Argument to a time-dimension in  the Projection 
It may result in some databases throwing errors that the column in HAVING is not present in GROUP BY or is not an aggregate.
Existing and new test cases.
> TimeDimension Grain Arg match check between Having Filter and Projection

- pom.xml
Resolves Build errors temporarily due to https://github.com/jeremylong/DependencyCheck/issues/3306
Existing test cases pass
> Disable Dependency Check

- elide-core/src/main/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialect.java
- elide-core/src/main/java/com/yahoo/elide/core/request/Argument.java
- elide-core/src/main/java/com/yahoo/elide/core/utils/TypeHelper.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/AggregationDataStoreTransaction.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/EntityProjectionTranslator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/ColumnVisitor.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/TableContext.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Column.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/Query.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/Queryable.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLQueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/DynamicSQLReferenceTable.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLReferenceTable.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLTable.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/QueryPlanTranslator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/QueryTranslator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLColumnProjection.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLMetricProjection.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLPhysicalColumnProjection.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLTimeDimensionProjection.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/EntityProjectionTranslatorTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/metadata/TableContextTest.java
Expression resolution using TableContext.
> Resolution using Table Context

- elide-core/src/main/java/com/yahoo/elide/core/filter/expression/FilterPredicatePushdownExtractor.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/expression/FilterPredicatePushdownExtractorTest.java
Resolves #2029
Modified FilterPredicatePushdownExtractor to return the right FilterExpression.  
Fixes an issue where filtering might not work properly when it involves a computed attribute/relationship, described in the linked issue.
Added new unit tests which before the fix is applied. 
Also tested our application where we were seeing an error due to this and that is resolved as well.
> Fix handling in filter pushdown extractor

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/QueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/annotation/NamespaceMeta.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/dynamic/NamespacePackage.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/MetaDataStore.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Namespace.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLQueryEngine.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/NamespaceConfig.java
- elide-model-config/src/main/resources/elideNamespaceConfigSchema.json
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/AsyncTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/ControllerTest.java
- elide-standalone/src/test/java/example/ElideStandaloneExportTest.java
- elide-standalone/src/test/java/example/ElideStandaloneTest.java
Resolves #2010
Metadata Model changes to Support namespace.
i) New Metadata Model called `Namespace` has been added.
ii) New Package Type `NamespacePackage` has been added.
iii) Backward compatible changes in `MetaDataStore`
iv) Populating of Namespace Metadata logic added in QueryEngine. 
#2010 
Existing Test cases pass. New test cases to be added later.
> Aggregation Store: Namespace Metadata changes

- elide-core/src/main/java/com/yahoo/elide/core/security/permissions/PermissionExpressionBuilder.java
- elide-core/src/main/java/com/yahoo/elide/core/security/permissions/expressions/AndExpression.java
- elide-core/src/main/java/com/yahoo/elide/core/security/permissions/expressions/AnyFieldExpression.java
- elide-core/src/main/java/com/yahoo/elide/core/security/permissions/expressions/CheckExpression.java
- elide-core/src/main/java/com/yahoo/elide/core/security/permissions/expressions/Expression.java
- elide-core/src/main/java/com/yahoo/elide/core/security/permissions/expressions/ExpressionVisitor.java
- elide-core/src/main/java/com/yahoo/elide/core/security/permissions/expressions/NotExpression.java
- elide-core/src/main/java/com/yahoo/elide/core/security/permissions/expressions/OrExpression.java
- elide-core/src/main/java/com/yahoo/elide/core/security/permissions/expressions/SpecificFieldExpression.java
- elide-core/src/main/java/com/yahoo/elide/core/security/visitors/PermissionExpressionNormalizationVisitor.java
- elide-core/src/main/java/com/yahoo/elide/core/security/visitors/PermissionToFilterExpressionVisitor.java
- elide-core/src/test/java/com/yahoo/elide/parsers/expression/PermissionExpressionNormalizationVisitorTest.java
- elide-core/src/test/java/com/yahoo/elide/parsers/expression/PermissionExpressionVisitorTest.java
- elide-core/src/test/java/com/yahoo/elide/parsers/expression/PermissionToFilterExpressionVisitorTest.java
Add Normalization visitor for Permission Expression class. 
Change PermissionToFilterExpressionVisitor to work on normalized expression. 
Unit Test
> Permission visitor normalization

- elide-core/src/main/java/com/yahoo/elide/parsers/expression/PermissionExpressionNormalizationVisitor.java
- elide-core/src/main/java/com/yahoo/elide/parsers/expression/PermissionToFilterExpressionVisitor.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/PermissionExpressionBuilder.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/AndExpression.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/AnyFieldExpression.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/CheckExpression.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/Expression.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/ExpressionVisitor.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/NotExpression.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/OrExpression.java
- elide-core/src/main/java/com/yahoo/elide/security/permissions/expressions/SpecificFieldExpression.java
- elide-core/src/test/java/com/yahoo/elide/parsers/expression/PermissionExpressionVisitorTest.java
- elide-core/src/test/java/com/yahoo/elide/parsers/expression/PermissionToFilterExpressionVisitorTest.java
Add Normalization visitor for Permission Expression class.
Change PermissionToFilterExpressionVisitor to work on normalized expression.
Unit Test
> normalize permission expression before converting to filter expression

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/dynamic/NamespacePackage.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Namespace.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/dynamic/NamespacePackageTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/framework/AggregationDataStoreTestHarness.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/MetaDataStoreIntegrationTest.java
- elide-datastore/elide-datastore-aggregation/src/test/resources/configs/models/namespaces/namespaces.hjson
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/DraftV4LibraryWithElideFormatAttr.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/DynamicConfiguration.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/MessageBundleWithElideMessages.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/jsonformats/ElideNamespaceNameFormatAttr.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/NamespaceConfig.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/Table.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/validator/DynamicConfigValidator.java
- elide-model-config/src/main/resources/elideNamespaceConfigSchema.json
- elide-model-config/src/main/resources/elideTableSchema.json
- elide-model-config/src/test/java/com/yahoo/elide/modelconfig/validator/DynamicConfigValidatorTest.java
- elide-model-config/src/test/resources/validator/bad_default_namespace/models/namespaces/test_namespace.hjson
- elide-model-config/src/test/resources/validator/bad_default_namespace/models/tables/namespace_test_model.hjson
- elide-model-config/src/test/resources/validator/valid/models/tables/referred_model.hjson
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/AggregationStoreTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/DisableAggStoreAsyncTest.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideStandaloneSettings.java
- elide-standalone/src/test/java/example/ElideStandaloneDisableAggStoreTest.java
- elide-standalone/src/test/java/example/ElideStandaloneDisableMetaDataStoreTest.java
- elide-standalone/src/test/java/example/ElideStandaloneTest.java
Resolves #2010 
i) Enable Namespace HJSON Config parsing in Elide Standalone and Spring.
ii) Test cases for Agg Store Changes to add namespace metadata
#2010
Existing and new test cases pass
> Test Cases + Enable Namespace in Standalone and Spring

- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java
Prevents SpelParseException on parsing the expression.
Resolves #2021
I'm setting a default value for the elide configuration as it doesn't seem to be loaded at this stage
For steps how to reproduce see the issue.
I tested the fix on my project. With pr34 it fails to start, with my local pr35-SNAPSHOT changes it launches.
There is also a reference implementation with the exact same appraoch inside Elide here: https://github.com/yahoo/elide/blob/b126fc12c0102fa8441e5900b81ad95d1b0bb3c3/elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/controllers/ExportController.java#L40
> Add missing default values for ElideAutoConfiguration

- elide-core/src/main/java/com/yahoo/elide/core/security/permissions/PermissionExpressionBuilder.java
- elide-core/src/main/java/com/yahoo/elide/core/security/permissions/expressions/AnyFieldExpression.java
- elide-core/src/test/java/com/yahoo/elide/core/security/permissions/PermissionExpressionBuilderTest.java
Changes AnyField permission logic from Elide 3 semantics to match current documentation.
> Refactored AnyFieldExpression logic

- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/main/java/com/yahoo/elide/core/pagination/PaginationImpl.java
- elide-core/src/main/java/com/yahoo/elide/core/security/RequestScope.java
- elide-core/src/main/java/com/yahoo/elide/core/sort/SortingImpl.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/EntityProjectionMaker.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/document/processors/DocumentProcessor.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/document/processors/IncludedProcessor.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/parser/state/BaseState.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/parser/state/CollectionTerminalState.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/parser/state/RelationshipTerminalState.java
- elide-core/src/test/java/com/yahoo/elide/core/TestRequestScope.java
- elide-core/src/test/java/com/yahoo/elide/core/pagination/PaginationImplTest.java
- elide-core/src/test/java/com/yahoo/elide/jsonapi/document/processors/IncludedProcessorTest.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/core/QueryLogger.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/core/Slf4jQueryLogger.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/core/Slf4jQueryLoggerTest.java
Resolves https://github.com/yahoo/elide/discussions/1985
This changes exposes the already existing queryParams to the security.RequestScope interface.
LifeCycleHooks only expose the security.RequestScope. This change makes the queryParams visible there as well.
It's implicitly tested as we just extend an already tested interface.
> Expose query params on security.RequestScope

- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/main/java/com/yahoo/elide/core/dictionary/EntityDictionary.java
- elide-core/src/main/java/com/yahoo/elide/core/security/PermissionExecutor.java
- elide-core/src/main/java/com/yahoo/elide/core/security/executors/ActivePermissionExecutor.java
- elide-core/src/main/java/com/yahoo/elide/core/security/executors/MultiplexPermissionExecutor.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/AggregationDataStore.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/QueryRunner.java
Each model a datastore manages can now have its own permission executor generator. new Multiplex permission executor delegates the call to the model's permission executor. 
Support multiple permission executors
IT
> get permission executor from datastore for each model that it manages.

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/main/java/com/yahoo/elide/core/request/EntityProjection.java
- elide-core/src/main/java/com/yahoo/elide/core/security/PermissionExecutor.java
- elide-core/src/main/java/com/yahoo/elide/core/security/executors/ActivePermissionExecutor.java
- elide-core/src/main/java/com/yahoo/elide/core/security/executors/BypassPermissionExecutor.java
- elide-core/src/main/java/com/yahoo/elide/core/security/executors/MultiplexPermissionExecutor.java
- elide-core/src/main/java/com/yahoo/elide/core/security/permissions/PermissionExpressionBuilder.java
- elide-core/src/main/java/com/yahoo/elide/core/security/visitors/CanPaginateVisitor.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/visitors/VerifyFieldAccessFilterExpressionVisitorTest.java
- elide-core/src/test/java/com/yahoo/elide/core/security/PermissionExecutorTest.java
- elide-core/src/test/java/com/yahoo/elide/core/security/permissions/PermissionExpressionBuilderTest.java
- elide-core/src/test/java/com/yahoo/elide/parsers/expression/CanPaginateVisitorTest.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/GraphQLEndpointTest.java
Some logic in Elide that examines JSON-API sparse fields is not applied for GraphQL:
- Determining whether a collection can be paginated.
- Building security filters from only the set of requested fields (not the entire entity model).
.
This PR changes Elide core to leverage the EntityProjection to build the list of requested fields (rather than sourcing from sparse fields from the request header) allowing the same logic to be leveraged for both JSON-API and GraphQL
> Source sparse fields from entity projection

- elide-core/src/main/java/com/yahoo/elide/utils/coerce/converters/ISO8601DateSerde.java
- elide-core/src/test/java/com/yahoo/elide/utils/coerce/CoerceUtilTest.java
- elide-core/src/test/java/com/yahoo/elide/utils/coerce/converters/ISO8601DateSerdeTest.java
Resolves #2045
ISO8601DateSerde can now handle conversion from the different instances of Date class as well.
Details in #2045
Added unit test
> Add ability to handle conversion of Date instances to ISO8601DateSerde

- pom.xml
Bump dependency-check.  Required for latest CVE files.
Fixes build failure.
>Caused by: java.lang.NullPointerException
at org.owasp.dependencycheck.data.nvd.ecosystem.CveEcosystemMapper.hasMultipleVendorProductConfigurations (CveEcosystemMapper.java:93)
at org.owasp.dependencycheck.data.nvd.ecosystem.CveEcosystemMapper.getEcosystem (CveEcosystemMapper.java:67)
Build
> bump dependency-check

- elide-core/src/main/java/com/yahoo/elide/core/security/executors/ActivePermissionExecutor.java
ActivePermissionExecutor's userPermissionCheckCache needs to include a set of all requested fields in its cache key. 
> change permission executor cache to store set of fields

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/AggregationDataStore.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/DefaultQueryValidator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/QueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/ColumnContext.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/ColumnSubContext.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/MetaDataStore.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/PhysicalRefColumnContext.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/TableContext.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/TableSubContext.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/ArgumentDefinition.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Column.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Table.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/Query.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/Queryable.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/expression/ExpressionParser.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/expression/JoinExpressionExtractor.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLTable.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/QueryTranslator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLColumnProjection.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLTimeDimensionProjection.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/MetaDataStoreIntegrationTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/expression/JoinExpressionExtractorTest.java
Propagate client query arguments to join tables
Refactor: Getting column projection from queryable's source itself, this column projection will have default/available arguments for the column.  So no need to go-to source for default/available arguments again.
> Propogate client query arguments to join tables

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/QueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/ArgumentDefinition.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Column.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Table.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLQueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/expression/ExpressionParser.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLReferenceTable.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/validator/TableArgumentValidator.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/metadata/ColumnContextTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/validator/TableArgumentValidatorTest.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/validator/DynamicConfigValidator.java
For any table:
All the table arguments used (in the column definition, Join expressions, or table's SQL) must be defined in the argument list for this table (with or without default value).
All the table arguments required for join tables must be defined in the argument list for this table (with or without default value).
> Verify table arguments.

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLQueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/expression/ReferenceExtractor.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/QueryPlanTranslator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLColumnProjection.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/validator/ColumnArgumentValidator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/validator/TableArgumentValidator.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/metadata/ColumnContextTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/expression/HasColumnArgsVisitorTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/expression/LogicalReferenceExtractorTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/expression/PhysicalReferenceExtractorTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLColumnProjectionTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/validator/ColumnArgumentValidatorTest.java
For any column:
- All the column arguments used (Either in column definition Or in Join expressions for join referenced directly in column definition) must be defined in the argument list for this column (with or without default value)
- If the column references another logical column (Either in column definition Or in Join expressions for join referenced directly in column definition), If any argument in the argument list for this logical column doesn’t have default value then that argument must be defined for this column also (with or without default value). The only exception is if this logical column is referenced using SQL helper by this column, which defines a fixed value for this argument, then there is no need to redefine the argument for this column. 
I confirm that this …
> Verify column arguments.

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/cache/QueryKeyExtractor.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/cache/QueryKeyExtractorTest.java
Using an alias as a key could be misleading since users can use the same alias for different columns across different requests.  Use name instead. 
> use column name to extract cache key in agg datastore

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
Create object does not run entity level operation checks.  This behavior reverts to Elide 4 semantics.
> use CheckPermission for CreateObject to include user checks and operation checks

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/TableSource.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/example/PlayerStats.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/MetaDataStoreIntegrationTest.java
Resolves #2163 
Currently the config for suggestionColumns is ignored and for each suggestionColumn the valueSource column is added again
Fix for suggestionColumns
Added a test to show tableSource is properly populated in metadata
> Fix suggestionColumns to add correct columns

- elide-core/src/main/java/com/yahoo/elide/jsonapi/resources/JsonApiEndpoint.java
- elide-core/src/main/java/com/yahoo/elide/utils/HeaderUtils.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLEndpoint.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/controllers/GraphqlController.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/controllers/JsonApiController.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/ControllerTest.java
Resolves #2166
1. The JsonApiController now uses a MultiValueMap to accept multiple values. Since Elide requires MultivaluedHashMap which is not supported by Spring I also added a convert method.
2. Header cleaning now takes into account that headers are to be treated as lowercase. Since we don't have a guarantee that all webservers out there will properly convert headers, I force them into a lowercased map.
1) was a bug I encountered when writing a custom hook. The hooks give multivalue maps but in my integration tests it didn't work.
2) I encountered it when writing integration tests for 1)
There are new integration tests for each JsonApiController method verifying the passthrough of the headers and the correct removal of the auth headers.
I confirm that this contribution is made under …
> Allow multivalue params and fix header sanitization

- elide-graphql/src/main/java/com/yahoo/elide/graphql/parser/GraphQLEntityProjectionMaker.java
Fix defaultMaxPageSize setting. I see `defaultPageSize` was passed instead of `defaultMaxPageSize`, so it was throwing error despite correct settings used.
> Fix defaultMaxPageSize setting

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLQueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/dialects/AbstractSqlDialect.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/dialects/SQLDialect.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/expression/JoinExpressionExtractor.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/QueryTranslator.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/UseASBeforeTableAliasExplainQueryTest.java
Make AS before table alias optional, i.e. dialect based.
Oracle doesn’t support `AS` in FROM clause and currently, we generate SQL like `table_name AS table_alias` so it doesn't work. Oracle supports `AS` in the SELECT clause so no issues with `column_name AS column_alias`. 
> Make AS before table alias optional, i.e. dialect based

- elide-async/pom.xml
- elide-datastore/elide-datastore-aggregation/pom.xml
- pom.xml
Calcite uses `json-path` version `2.4.0` which conflicts with elide-async's required json version `2.6.0`.
> Exclude json-path from calcite

- translations/es/README.md
Resolves #1943
Added spanish translation for `README.md` file
Completly translated the main `README.md` file into the file at `/translations/es/README.md` except for the names of the articles at the very bottom. I thought it would be better to keep those in english but can translate them too if need it.
Also i noticed that on the other translation they translated the `CONTRIBUTING.md` file as well, should i do the same?
> Added spanish translation for README.md

- elide-core/src/main/java/com/yahoo/elide/core/dictionary/EntityDictionary.java
- elide-core/src/test/java/com/yahoo/elide/core/dictionary/EntityDictionaryTest.java
- elide-core/src/test/java/example/Publisher.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/ModelBuilder.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/ModelBuilderTest.java
- elide-graphql/src/test/java/example/Book.java
- elide-graphql/src/test/java/example/Publisher.java
- elide-swagger/src/main/java/com/yahoo/elide/swagger/JsonApiModelResolver.java
- elide-swagger/src/test/java/com/yahoo/elide/swagger/JsonApiModelResolverTest.java
- elide-swagger/src/test/java/example/models/Author.java
> Use include to set model description

- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/annotation/LifeCycleHookBinding.java
- elide-core/src/main/java/com/yahoo/elide/core/RequestScope.java
- elide-core/src/test/java/com/yahoo/elide/core/lifecycle/FieldTestModel.java
- elide-core/src/test/java/com/yahoo/elide/core/lifecycle/LifeCycleTest.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/QueryRunner.java
Resolves #1397 
This phase is also useful if you want to clean up references prior to a model deletion in a lifecycle hook - but don't want it to happen prior to security checks.
> Added PREFLUSH phase for lifecycle hooks

- README.md
Fixes broken invite link to discord.
> Fix invite link for Discord

- elide-test/pom.xml
Fixes bug where elide-tests is pulling in old graphql-java.
> Fixed mismatching graphQL versions in pom

- elide-core/src/main/java/com/yahoo/elide/core/dictionary/EntityDictionary.java
- elide-core/src/test/java/com/yahoo/elide/core/dictionary/EntityDictionaryTest.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLConversionUtils.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLNameUtils.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/ModelBuilder.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/subscriptions/Subscription.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/subscriptions/SubscriptionField.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/subscriptions/SubscriptionModelBuilder.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/GraphQLConversionUtilsTest.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/ModelBuilderTest.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/subscriptions/SubscriptionModelBuilderTest.java
- elide-graphql/src/test/java/example/Author.java
- elide-graphql/src/test/java/example/Book.java
This first PR adds the Subscription and SubscriptionField annotations and constructs a new GraphQL schema for subscription models (which are subsets of Elide models).
> GraphQL Subscriptions PR1: Subscription model builder

- elide-datastore/elide-datastore-jms/pom.xml
- elide-datastore/elide-datastore-jms/src/main/java/com/yahoo/elide/datastores/jms/JMSDataStore.java
- elide-datastore/elide-datastore-jms/src/main/java/com/yahoo/elide/datastores/jms/JMSDataStoreTransaction.java
- elide-datastore/elide-datastore-jms/src/main/java/com/yahoo/elide/datastores/jms/MessageDeserializer.java
- elide-datastore/elide-datastore-jms/src/main/java/com/yahoo/elide/datastores/jms/MessageIterator.java
- elide-datastore/elide-datastore-jms/src/main/java/com/yahoo/elide/datastores/jms/SubscriptionRequestScope.java
- elide-datastore/elide-datastore-jms/src/main/java/com/yahoo/elide/datastores/jms/TopicType.java
- elide-datastore/elide-datastore-jms/src/test/java/com/yahoo/elide/datastores/jms/JMSDataStoreTest.java
- elide-datastore/elide-datastore-jms/src/test/java/com/yahoo/elide/datastores/jms/MessageDeserializerTest.java
- elide-datastore/elide-datastore-jms/src/test/java/com/yahoo/elide/datastores/jms/MessageIteratorTest.java
- elide-datastore/elide-datastore-jms/src/test/java/example/Author.java
- elide-datastore/elide-datastore-jms/src/test/java/example/Book.java
- elide-datastore/pom.xml
- pom.xml
Adds a new, read-only JMS data store that deserializes Elide models from JMS topics.
> GraphQL Subscriptions PR2: Jms data store

- elide-core/src/main/java/com/yahoo/elide/core/datastore/inmemory/HashMapDataStore.java
- elide-core/src/main/java/com/yahoo/elide/core/utils/ClassScanner.java
- elide-core/src/test/java/com/yahoo/elide/core/utils/ClassScannerTest.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/MetaDataStore.java
ClassGraph scans are really expensive.  This reduces scans at service startup from 7 to 1.
Existing tests.
Profiling spring-boot example before and after change.
> Improve Server Boot Time: Reducing ClassGraph scans to a single scan

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/core/datastore/DataStoreTransaction.java
If the default datastore `loadObject` fails to filter to a single result, do not return any.
Currently the first element of the collection would erroneously be returned.
> loadObject should return unique result

- elide-async/pom.xml
- elide-async/src/main/java/com/yahoo/elide/async/operation/AsyncQueryOperation.java
- elide-async/src/main/java/com/yahoo/elide/async/operation/GraphQLAsyncQueryOperation.java
- elide-async/src/main/java/com/yahoo/elide/async/operation/JSONAPIAsyncQueryOperation.java
- elide-async/src/test/java/com/yahoo/elide/async/operation/SafeJsonPathTest.java
- elide-datastore/elide-datastore-aggregation/pom.xml
- pom.xml
com.jayway.jsonpath has breaking API changes between 2.4 and 2.6.  
Expressions like 'foo.bar.length()' return an array containing an integer in 2.4 and just an integer in 2.6.
This change makes Elide JSONPath proof for customers who might pull in the wrong version of JSONPath in their pom by mistake.
> Makes Elide JSONPath version proof

- screwdriver.yaml
Disable PR builds from forked repos in light of the recent security issue with a PR where some code was executed on the build containers by an unknown entity. https://patch-diff.githubusercontent.com/raw/yahoo/elide/pull/2260.patch
SD has feature to disable this: https://docs.screwdriver.cd/user-guide/configuration/annotations#:~:text=restrictPR
Prevent harmful code from an unknown user being executed in the build containers.
Existing builds pass. Will manually verify after the PR is merged.
> Disable PR build from forked repo

- screwdriver.yaml
Create a new build for Elide 6 using open JDK 11.
> Updating screwdriver build for JDK11 and Elide 6

- elide-core/src/main/java/com/yahoo/elide/core/datastore/DataStoreTransaction.java
- elide-core/src/main/java/com/yahoo/elide/core/datastore/inmemory/InMemoryStoreTransaction.java
- elide-core/src/main/java/com/yahoo/elide/core/datastore/wrapped/TransactionWrapper.java
- elide-core/src/main/java/com/yahoo/elide/core/security/RequestScope.java
- elide-core/src/test/java/com/yahoo/elide/core/datastore/inmemory/InMemoryStoreTransactionTest.java
- elide-core/src/test/java/com/yahoo/elide/core/datastore/wrapped/TransactionWrapperTest.java
- elide-datastore/elide-datastore-jpa/src/main/java/com/yahoo/elide/datastores/jpa/transaction/AbstractJpaTransaction.java
- elide-datastore/elide-datastore-jpa/src/test/java/com/yahoo/elide/datastores/jpa/EntityManagerLifeCycleHookIT.java
- elide-datastore/elide-datastore-jpa/src/test/java/example/BookCatalog.java
- elide-datastore/elide-datastore-jpa/src/test/java/example/hook/BookCatalogOnCreateHook.java
- elide-datastore/elide-datastore-multiplex/src/main/java/com/yahoo/elide/datastores/multiplex/MultiplexTransaction.java
- elide-datastore/elide-datastore-multiplex/src/test/java/com/yahoo/elide/datastores/multiplex/MultiplexTransactionTest.java
A common use case for life cycle hooks is to use an entity manager to load something from a database and edit the model in the lifecycle hook.
There is no convenient way in Elide to gain access to the current entity manager/session.
This PR provides that by:
1. Adding a method to get access to the current data store transaction via the request scope.
2. Adding a getProperty method in the data store transaction.
3. Implementing the getProperty method in data store transaction implementations.
> Add ability to retrieve data store properties in life cycle hooks.

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/AggregationDataStoreTransaction.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/filter/visitor/MatchesTemplateVisitor.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/Query.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLTable.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/validator/TableArgumentValidator.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/filter/visitor/MatchesTemplateVisitorTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/AggregationDataStoreIntegrationTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/validator/TableArgumentValidatorTest.java
- elide-datastore/elide-datastore-aggregation/src/test/resources/configs/models/tables/SalesView.hjson
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/validator/DynamicConfigValidator.java
- elide-model-config/src/test/java/com/yahoo/elide/modelconfig/validator/DynamicConfigValidatorTest.java
Resolves #1956
This change promotes filterTemplate variables defined in aggregation store data models into table arguments that can be used in table, join, and column expressions.
For example, a table may have defined a filter template (a table required filter) such as:
```
filterTemplate : deliveryTime>={{start}};deliveryTime<{{end}}
```
The variables 'start' and 'end' can then be referenced in a join as follows:
```
{
name: delivery
to: deliveryDetails
namespace: SalesNamespace
kind: toOne
// References Logical Columns, multiple join condition
definition: '''
{{ orderId}} = {{delivery.orderId}} AND
{{ delivery.$delivered_on }} >= '{{ $$table.args.start }}' AND
{{ delivery.$delivered_on }} < '{{ $$table.args.end }}'
'''
}
```
Allow more powerful generated SQL that leverage required …
> Templated filter table arguments

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/dynamic/TableType.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/expression/ExpressionParser.java
- elide-datastore/elide-datastore-aggregation/src/test/java/example/metrics/SalesViewOrderMax.java
- elide-datastore/elide-datastore-aggregation/src/test/resources/configs/models/tables/SalesView.hjson
- elide-model-config/src/main/resources/elideTableSchema.json
- elide-model-config/src/test/java/com/yahoo/elide/modelconfig/DynamicConfigSchemaValidatorTest.java
- elide-model-config/src/test/java/com/yahoo/elide/modelconfig/validator/DynamicConfigValidatorTest.java
- elide-model-config/src/test/resources/validator/valid/models/tables/player_stats_extends.hjson
It was not possible to configure a 'maker' for metric/measure using HJSON.
Class configuration worked fine but HJSON configuration was broken.
Modified existing HJSON to include a new measure with a custom maker.  
Modified existing UTs.
> Aggregation Store: Fix hjson metric projection maker config

- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/main/java/com/yahoo/elide/ElideSettings.java
- elide-core/src/main/java/com/yahoo/elide/ElideSettingsBuilder.java
- elide-core/src/main/java/com/yahoo/elide/core/exceptions/ErrorMapper.java
- elide-core/src/test/java/com/yahoo/elide/core/exceptions/ErrorMapperTest.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/QueryRunner.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/GraphQLEndpointTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideStandaloneSettings.java
- elide-standalone/src/test/java/example/ElideStandaloneDisableAggStoreTest.java
- elide-standalone/src/test/java/example/ElideStandaloneDisableMetaDataStoreTest.java
- elide-standalone/src/test/java/example/ElideStandaloneExportTest.java
- elide-standalone/src/test/java/example/ElideStandaloneMetadataStoreMissingTest.java
- elide-standalone/src/test/java/example/ElideStandaloneTestSettings.java
Resolves #2204
ElideSettings now take an (optional) ErrorMapper. This is a functional interface that can map any Exception into a different CustomErrorException.
When handling a request now, Elide runs throw the previous error handling up to the point where it is considered an unknown exception. In that case, the unknown exception is passed to the error mapper, which can map it into a CustomErrorException. If the mapping is successful, we build an error response out of it, otherwise we rethrow the untouched exception (just as before).
While Elide maps javax.validation.ConstraintValidationException into proper error messages, it fails to do the same for org.hibernate.ConstraintViolationException as the latter ones might only refer to database constraint names, which have no context.
With a …
> Add ability to map unknown exceptions to custom exceptions

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/AggregationDataStoreTransaction.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/annotation/ColumnMeta.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/dynamic/TableType.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Column.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/RequiresFilter.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Table.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/validator/ColumnArgumentValidator.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/AggregationDataStoreTransactionTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/AggregationDataStoreIntegrationTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/validator/ColumnArgumentValidatorTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/example/PlayerStatsWithRequiredFilter.java
- elide-datastore/elide-datastore-aggregation/src/test/resources/configs/models/tables/SalesView.hjson
- elide-integration-tests/src/test/java/com/yahoo/elide/initialization/GraphQLIntegrationTest.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/jsonformats/ValidateDimPropertiesValidator.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/Dimension.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/Measure.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/validator/DynamicConfigValidator.java
- elide-model-config/src/main/resources/elideTableSchema.json
- elide-model-config/src/test/java/com/yahoo/elide/modelconfig/parser/handlebars/HandlebarsHydratorTest.java
- elide-model-config/src/test/java/com/yahoo/elide/modelconfig/validator/DynamicConfigValidatorTest.java
- elide-model-config/src/test/resources/validator/duplicate_column_args/models/tables/table.hjson
- elide-model-config/src/test/resources/validator/valid/models/tables/player_stats.hjson
Feature support for templated filters (required filters) for columns:
Column definitions can now have a filterTemplate:
```
{
name: deliveryYear
type: TIME
// Logical Column Reference in same table, which references another Logical Column in referred table, which references another Logical column in referred table, which references another Logical column in referred table, which references Physical column in referred table
definition: '{{deliveryMonth}}'
readAccess: guest user
grains:
[{
type: YEAR
sql: PARSEDATETIME(FORMATDATETIME({{$$column.expr}}, 'yyyy'), 'yyyy')
}]
filterTemplate: 'deliveryYear=={{deliveryYear}}'
}
```
or in Java:
```java
@MetricFormula("MAX(highScore)")
@ColumnMeta(description = "very awesome score", category = "Score Category", filterTemplate = …
```
> AggregationStore: Templated filter column arguments

- elide-core/src/main/java/com/yahoo/elide/core/lifecycle/CRUDEvent.java
- elide-core/src/main/java/com/yahoo/elide/core/lifecycle/LifeCycleHook.java
- elide-core/src/main/java/com/yahoo/elide/core/lifecycle/LifecycleHookInvoker.java
- elide-datastore/elide-datastore-jms/src/main/java/com/yahoo/elide/datastores/jms/TopicType.java
- elide-datastore/elide-datastore-jms/src/main/java/com/yahoo/elide/datastores/jms/hooks/NotifyTopicLifeCycleHook.java
- elide-datastore/elide-datastore-jms/src/test/java/com/yahoo/elide/datastores/jms/hooks/NotifyTopicLifeCycleHookTest.java
- suppressions.xml
Part 3 of GraphQL subscription work.
Adds an internal life cycle hook that will be registered for Elide models with subscriptions.  The hook will publish a message to a JMS topic whenever a subscription model is created, updated, or deleted.
Other improvements include:
- Provides a mechanism for life cycle hooks to get access to the PersistentResource (and corresponding lineage) if needed.
- Updates suppression.xml to ignore a tomcat CVE
New unit tests.  IT tests will come later when other pieces are in place.
> GraphQL subscription life cycle hooks

- elide-graphql/src/main/java/com/yahoo/elide/graphql/subscriptions/annotations/Subscription.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/subscriptions/websocket/RequestHandler.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/subscriptions/websocket/SessionHandler.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/subscriptions/websocket/protocol/ConnectionAck.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/subscriptions/websocket/protocol/ConnectionInit.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/subscriptions/websocket/protocol/Error.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/subscriptions/websocket/protocol/Next.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/subscriptions/websocket/protocol/Subscribe.java
- pom.xml
We can't release Elide 6 because the nexus plugin requires every artifact to have javadoc.   This was broken when we moved from Elide 5 because of a delombok step in maven.
Other changes include small edits in GraphQL subscriptions that break javadoc.
> Fixing release build javadoc creation

- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/test/java/com/yahoo/elide/core/lifecycle/FieldTestModel.java
- elide-core/src/test/java/com/yahoo/elide/core/lifecycle/LifeCycleTest.java
When updating a relationship, lifecycle hooks were being invoked multiple times - once for each change to the relationship.  
This PR ensures a hook is called once per field (regardless of how many relationships are being added or removed). 
> Lifecycle events should trigger once for relationship updates

- elide-spring/pom.xml
- elide-standalone/pom.xml
- pom.xml
- suppressions.xml
log4j2 API to 2.17.0
CVE-2021-45105, CVE-2021-45046
Build and unit testing
> bump log4j2 API to 2.17.0

- elide-graphql/pom.xml
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLConversionUtils.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/ModelBuilderTest.java
- elide-graphql/src/test/resources/graphql/requests/update/updateComplexAttributeMap.graphql
- elide-graphql/src/test/resources/graphql/responses/fetch/complexAttribute.json
- elide-graphql/src/test/resources/graphql/responses/fetch/complexAttributeList.json
- elide-graphql/src/test/resources/graphql/responses/fetch/complexAttributeMap.json
- elide-graphql/src/test/resources/graphql/responses/update/updateComplexAttributeList.json
- elide-graphql/src/test/resources/graphql/responses/update/updateComplexAttributeMap.json
- elide-spring/pom.xml
- elide-standalone/pom.xml
- pom.xml
Uses JavaPrimitives.GraphQLBigDecimal for Converting BigDecimal Values to Graphql Input.
BigDecimal Values were converted to Float resulting in precision loss and returning values with Exponents.
Existing test cases passed with updates.
> Use GraphQLBigDecimal for BigDecimal Conversions in GraphQLConversionUtils

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLQueryEngine.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/QueryEngineTest.java
Resolves #2465
This uses the original query with filters to populate pagination query filter parameters. 
Unit test
> use query with filter to populate query parameters in pagination

- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/test/java/com/yahoo/elide/core/exceptions/ErrorMapperTest.java
- elide-core/src/test/java/com/yahoo/elide/core/lifecycle/LifeCycleTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideResourceConfig.java
This PR improves developer ergonomics whenever the Elide bean is overridden.   Elide.doScan currently must be explicitly called.  With this change, doScan happens automatically for spring boot (but must still be called separately for Elide standalone which relies on Jersey's phased dependency injection).
> Enable lifecycle, check, and other entity scans by default for Spring.

- elide-core/src/main/java/com/yahoo/elide/core/dictionary/EntityDictionary.java
- elide-core/src/main/java/com/yahoo/elide/core/security/checks/prefab/Role.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/store/models/ConfigFile.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/ConfigStoreTest.java
ConfigFile path cannot be changed as the ID is derived from it.  It is immutable.  This PR explicitly disallows changes.
> Disallow ConfigFile path to be changed in ConfigStore

- elide-async/src/main/java/com/yahoo/elide/async/models/FileExtensionType.java
- elide-async/src/main/java/com/yahoo/elide/async/models/ResultType.java
- elide-async/src/main/java/com/yahoo/elide/async/operation/TableExportOperation.java
- elide-async/src/main/java/com/yahoo/elide/async/service/storageengine/FileResultStorageEngine.java
- elide-async/src/main/java/com/yahoo/elide/async/service/storageengine/ResultStorageEngine.java
- elide-async/src/test/java/com/yahoo/elide/async/operation/GraphQLTableExportOperationTest.java
- elide-async/src/test/java/com/yahoo/elide/async/operation/JsonAPITableExportOperationTest.java
- elide-async/src/test/java/com/yahoo/elide/async/service/storageengine/FileResultStorageEngineTest.java
- elide-integration-tests/src/test/java/com/yahoo/elide/async/integration/tests/framework/AsyncIntegrationTestApplicationResourceConfig.java
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/validator/DynamicConfigValidator.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAsyncConfiguration.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ExportControllerProperties.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/AsyncTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/resources/application.yaml
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideResourceConfig.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideStandaloneAsyncSettings.java
Resolves #2451  (if appropriate)
Add file extension support to Table Export. Alternative Approach to #2453
See #2451 and #2437
Existing test cases and new test cases.
> File Extension Support for Export Attachments

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/dynamic/TableType.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/cache/QueryKeyExtractorTest.java
Make Cachekey Unique for Same Hjson model name across namespaces
There are use cases of the same model name across diff namespaces that have exact same definition. We pull incorrect results from cache cos of that.
Existing and New Test cases.
> Make CacheKey Unique for same model name across namespaces

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/QueryPlanTranslator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLColumnProjection.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLMetricProjection.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLTimeDimensionProjection.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/framework/AggregationDataStoreTestHarness.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/AggregationDataStoreIntegrationTest.java
Use alias to check if the column is already present in the query. 
The AggregationBeforeJoin optimizer assumes the projectionWithAlias is not found in the query since getColumnProjection returns null for projection name. So the given projection is marked as hidden by the optimizer. 
Integration Test
> use alias to get column projection in query plan translator and while nesting projection

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/DefaultQueryValidator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/EntityProjectionTranslator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/Queryable.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/EntityProjectionTranslatorTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/AggregationDataStoreIntegrationTest.java
- elide-integration-tests/src/test/java/com/yahoo/elide/initialization/GraphQLIntegrationTest.java
There was a bug where the aggregation store was rejecting queries (as invalid) because it could not pair up a measure in the query (with an alias) with a filter predicate on the same measure (with or without the alias). 
> Aggregation Store: Fix filter by alias with parameterized metric.

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLColumnProjection.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLMetricProjection.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLTimeDimensionProjection.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/AggregationDataStoreIntegrationTest.java
SQLColumnProjection and SQLMetricProjection nest method identify a column with either getName or getAlias depending on the source. If the source is SQLTable which has no user-supplied alias, we use getName. Else we use getAlias. 
With the Current behavior of using an alias for column id, the metric column set with projected=false, when the source is an instance of SQLTable. This happens if the queryPlan of the simple metric is merged with the queryPlan of 2-pass aggregation metrics. 
Integration Test
> make getColumnProjection() method use different name for column Id for different source when alias are involved

- changelog.md
- elide-async/pom.xml
- elide-async/src/main/java/com/yahoo/elide/async/operation/TableExportOperation.java
- elide-async/src/main/java/com/yahoo/elide/async/service/storageengine/FileResultStorageEngine.java
- elide-async/src/main/java/com/yahoo/elide/async/service/storageengine/RedisResultStorageEngine.java
- elide-async/src/main/java/com/yahoo/elide/async/service/storageengine/ResultStorageEngine.java
- elide-async/src/test/java/com/yahoo/elide/async/service/storageengine/RedisResultStorageEngineTest.java
Adds an implementation of Redis Result Storage Engine.
In a distributed setup File Result Storage Engine can not be used because it saves the file locally. Using Redis for storing the Export Results in such cases.
New Test Cases.
> Redis Result Storage Engine

- elide-core/src/main/java/com/yahoo/elide/core/dictionary/EntityDictionary.java
- elide-core/src/test/java/com/yahoo/elide/core/dictionary/EntityDictionaryTest.java
- elide-core/src/test/java/example/Price.java
- elide-spring/elide-spring-boot-autoconfigure/pom.xml
- elide-spring/pom.xml
Ignored Elide models that are embedded in complex attributes.  Currently, Elide has strange behavior where it sometimes will bind the model as an attribute and later ignore it as an exposed entity.
> Ignoring Elide models embedded in complex attributes

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/enums/ValueType.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/metadata/enums/ValueTypeTest.java
> Update: Make `-` a valid TEXT value type character

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/enums/ValueType.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/metadata/enums/ValueTypeTest.java
Reverts yahoo/elide#2565
This could open a security hole because '--' is SQL comment.  Parameterized columns/tables is the only place in Elide where we cannot rely on prepared statements to prevent SQL injection.   Parameters need to be more or less ASCII labels with no white space or other control characters or match a very strict REGEX (like a date).
> Revert "Update: Make `-` a valid TEXT value type character"

- elide-spring/pom.xml
Should fix:
spring-beans-5.3.17.jar: CVE-2022-22965
> Bumping Spring to work around CVE

- elide-core/src/main/java/com/yahoo/elide/Elide.java
- elide-core/src/test/java/com/yahoo/elide/core/exceptions/ErrorMapperTest.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/QueryRunner.java
- elide-integration-tests/src/test/java/com/yahoo/elide/tests/ResourceIT.java
Resolves #2601
ErrorMapper interface was only invoked for runtime exceptions.  Now it will also be invoked for IOExceptions as well (allowing all exception handling to be customized).  
If no error mapper is defined or the error is not mapped, the behavior should remain the same.
> Fixes #2601

- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/AggregationDataStoreIntegrationTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/QueryEngineTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SubselectTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/example/PlayerStats.java
- elide-datastore/elide-datastore-aggregation/src/test/resources/graphql/responses/testGraphQLSchema.json
- elide-datastore/elide-datastore-aggregation/src/test/resources/prepare_tables.sql
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLConversionUtils.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/ModelBuilderTest.java
This PR fixes an issue when aggregating large numbers:
```
Can&#39;t serialize value (/RADM_NWFPty/edges[0]/node/col0) : Expected type &#39;Int&#39; but was &#39;Long&#39;.
```
> fix: support big number aggregations

- elide-core/src/main/java/com/yahoo/elide/ElideSettings.java
- elide-core/src/main/java/com/yahoo/elide/ElideSettingsBuilder.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/resources/JsonApiEndpoint.java
- elide-core/src/main/java/com/yahoo/elide/utils/HeaderUtils.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLEndpoint.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideConfigProperties.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/controllers/GraphqlController.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/controllers/JsonApiController.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/HeaderIdentityTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/IntegrationTestSetup.java
Adds configuration to enable/disable security credential stripping in HTTP headers.
Elide automatically removes Authorization headers from client requests before the framework is invoked.  Some users want to leverage the credentials in these headers to invoke other services from life cycle hooks or data stores.
New IT tests.
> Header filtering config

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/dynamic/TableType.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/DefaultTableSQLMaker.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/TableSQLMaker.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/annotation/FromSubquery.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/dialects/SQLDialectFactory.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/expression/JoinExpressionExtractor.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLTable.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/QueryTranslator.java
- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/validator/TableArgumentValidator.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/AggregationDataStoreIntegrationTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/MetaDataStoreIntegrationTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/example/tables/OrderDetailsMaker.java
- elide-datastore/elide-datastore-aggregation/src/test/resources/configs/models/tables/OrderDetailsMakerExample.hjson
- elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/Table.java
- elide-model-config/src/main/resources/elideTableSchema.json
Creates a fourth way to define a table for analytic queries.  The four ways are:
1.  Specifying a physical database table by name
2. Extending an existing table
3. Specifying a SQL query
4. **NEW** - Specifying a maker class that constructs a SQL query similar to 3.
The new maker interface allows the modeler complete control to dynamically construct the table base on any part of the client query:
```java
@FunctionalInterface
public interface TableSQLMaker {
/**
* Constructs dynamic SQL given a specific client query.
* @param clientQuery the client query.
* @return A templated SQL query
*/
String make(Query clientQuery);
}
```
Instead of leveraging handlebars for dynamic table construction, this allows Elide the ability to validate table HJSON and also gives modelers a more powerful …
> Aggregation store dynamic table sql

- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java
Making Injector a bean so the Elide Apps can access them directly without relying on dictionary
Making Injector a bean so the Elide Apps can access them directly without relying on dictionary. The RefreshScope changes create a cyclic dependency if someone is trying to use a dictionary.injector in any hooks, etc.
existing tests pass
> Add Injector as a Bean

- elide-core/src/main/java/com/yahoo/elide/ElideSettings.java
- elide-core/src/main/java/com/yahoo/elide/ElideSettingsBuilder.java
- elide-graphql/pom.xml
- elide-graphql/src/main/java/com/yahoo/elide/graphql/ModelBuilder.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/QueryRunner.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/parser/GraphQLEntityProjectionMaker.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/FetcherFetchTest.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/ModelBuilderTest.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/PersistentResourceFetcherTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideConfigProperties.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/GraphQLControllerProperties.java
Related to #2638 
Phase 1 of enabling the Apollo Federation specification.  Phase 1 simply exposes Elide models so they can be discovered by Apollo federation gateways.   Phase 2 will add support for @key allowing subgraphs to reference Elide model types in their schemas.
> Minimum to expose _service.sdl for Apollo federation.

- elide-core/src/main/java/com/yahoo/elide/core/utils/coerce/CoerceUtil.java
- elide-core/src/test/java/com/yahoo/elide/core/utils/ClassScannerTest.java
- elide-core/src/test/java/com/yahoo/elide/core/utils/coerce/CoerceUtilTest.java
Resolves #2734
Before Serdes, Elide did type coercion only for a set of standard types - dates, enums, etc.  This logic still takes precedence even over user defined Serdes.
The developer should be able to override Elide's type coercion with their own Serde.
Unit Test
> Serdes now take precedence over type converters for enums.

- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java
Resolves #2761
Manually tested starting spring boot with graphQL enabled (and also disabled) to see if a bad enumeration prevents startup.  With this fix, it does not when graphQL is disabled.
> Only build query runner if graphQL is enabled

- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideSubscriptionConfiguration.java
Resolves #2786
Tested manually on a Spring Boot project by including/excluding the elide-graphql and toggling the elide.graphql.enabled configuration.
> Allow elide-graphql to be excluded when elide.graphql.enabled=false

- elide-core/src/main/java/com/yahoo/elide/core/security/permissions/expressions/AnyFieldExpression.java
- elide-core/src/main/java/com/yahoo/elide/core/security/permissions/expressions/BooleanExpression.java
- elide-core/src/main/java/com/yahoo/elide/core/security/permissions/expressions/Expression.java
- elide-core/src/main/java/com/yahoo/elide/core/security/permissions/expressions/ExpressionVisitor.java
- elide-core/src/main/java/com/yahoo/elide/core/security/permissions/expressions/SpecificFieldExpression.java
- elide-core/src/main/java/com/yahoo/elide/core/security/visitors/PermissionExpressionNormalizationVisitor.java
- elide-core/src/main/java/com/yahoo/elide/core/security/visitors/PermissionToFilterExpressionVisitor.java
- elide-core/src/test/java/com/yahoo/elide/parsers/expression/PermissionExpressionVisitorTest.java
This PR expands the ExpressionVisitor to cover root and leaf expression types added by Elide. Primary driver is to allow the creation of visitors after Elide has decorated the AST with its internal expression types.
* Adding explicit visit methods for specific and any field expressions to ExpressionVisitor.
* Added BooleanExpression to represent PASS and FAILURE scenarios.
> Refactor expression visitor

- elide-core/src/main/java/com/yahoo/elide/core/filter/Operator.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/FilterPredicateTest.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/OperatorTest.java
- elide-datastore/elide-datastore-jpql/src/main/java/com/yahoo/elide/datastores/jpql/filter/FilterTranslator.java
- elide-datastore/elide-datastore-jpql/src/test/java/com/yahoo/elide/datastores/jpql/filter/FilterTranslatorTest.java
Resolves #2788
Added negated operators for prefix, prefixi, postfix, postfixi, infix and infixi operators.
Excluding values that do not contain a specific prefix, postfix or infix is currently not possible; it raises a InvalidOperatorNegationException since there is no negated operator defined for these operators.
I have added unit tests similar to those for the prefix operator. I have also tested the change with real API queries using Postman.
> Add negated prefix, postfix and infix operators. (#2788)

- elide-datastore/elide-datastore-jpql/src/main/java/com/yahoo/elide/datastores/jpql/query/RootCollectionFetchQueryBuilder.java
- elide-datastore/elide-datastore-jpql/src/test/java/com/yahoo/elide/datastores/hibernate/hql/RootCollectionFetchQueryBuilderTest.java
Resolves #2844 
Applies distinct to queries with a many relationship regardless of whether it is a paginated query.
Updates the `testRootFetchWithJoinFilter` test with the new expectation that distinct will be applied to the query.
> fix: apply distinct for non-paginated queries with many relationship

- changelog.md
- elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
- elide-core/src/main/java/com/yahoo/elide/core/datastore/inmemory/Operation.java
- elide-core/src/main/java/com/yahoo/elide/parsers/expression/CanPaginateVisitor.java
- elide-core/src/main/java/com/yahoo/elide/utils/coerce/converters/EpochToDateConverter.java
- elide-core/src/test/java/com/yahoo/elide/core/LifeCycleTest.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/dialect/DefaultFilterDialectTest.java
- elide-core/src/test/java/com/yahoo/elide/jsonapi/JsonApiTest.java
- elide-spring/pom.xml
- pom.xml
Received NPE when creating a resource with type=null.
Cleaned up IDE warnings.
CVE-2021-44228 Bump log4j2 and slf4j
Invalid data should not cause NPE.  This will generate 500 Internal Server Error instead of 400 Invalid Request.
Included unit test.  Also local service testing.
> Do not throw NPE for create type: null (4.x)

- elide-core/src/main/java/com/yahoo/elide/core/utils/coerce/CoerceUtil.java
- elide-core/src/main/java/com/yahoo/elide/core/utils/coerce/converters/Serde.java
- elide-core/src/test/java/com/yahoo/elide/core/utils/coerce/CoerceUtilTest.java
- elide-core/src/test/java/com/yahoo/elide/core/utils/coerce/converters/ISO8601DateSerdeTest.java
- elide-core/src/test/java/com/yahoo/elide/core/utils/coerce/converters/InstantSerdeTest.java
- elide-core/src/test/java/com/yahoo/elide/core/utils/coerce/converters/OffsetDateTimeTest.java
- elide-core/src/test/java/com/yahoo/elide/core/utils/coerce/converters/TimeZoneTest.java
- elide-core/src/test/java/com/yahoo/elide/core/utils/coerce/converters/URLSerdeTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/timegrains/serde/DaySerdeTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/timegrains/serde/HourSerdeTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/timegrains/serde/ISOWeekSerdeTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/timegrains/serde/MinuteSerdeTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/timegrains/serde/MonthSerdeTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/timegrains/serde/QuarterSerdeTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/timegrains/serde/SecondSerdeTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/timegrains/serde/TimeSerdeTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/timegrains/serde/WeekSerdeTest.java
- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/timegrains/serde/YearSerdeTest.java
- elide-datastore/elide-datastore-jms/src/main/java/com/yahoo/elide/datastores/jms/JMSDataStore.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLConversionUtils.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLScalars.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/SerdeCoercing.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/subscriptions/hooks/SubscriptionFieldSerde.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/subscriptions/hooks/SubscriptionScanner.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/GraphQLScalarsTest.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/subscriptions/SubscriptionSerdeTest.java
Resolves #2852 
Added new deserialize method to Serde:
```java
default T deserialize(Class<?> type, S val) {
return deserialize(val);
}
```
> Updated Serde.deserialize to take the output class as an argument

- elide-bom/pom.xml
- elide-contrib/pom.xml
- elide-datastore/elide-datastore-hibernate3/pom.xml
- elide-datastore/elide-datastore-hibernate5/pom.xml
- elide-datastore/elide-datastore-multiplex/pom.xml
- elide-datastore/elide-datastore-search/pom.xml
- elide-example-models/pom.xml
- elide-integration-tests/pom.xml
- elide-spring/elide-spring-boot-autoconfigure/pom.xml
- elide-spring/pom.xml
- elide-standalone/pom.xml
- pom.xml
- suppressions.xml
Create the Elide Bill Of Materials.
See [Apache bill of materials (BOM) files](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Importing_Dependencies)
[See Spring doc](https://docs.spring.io/spring-framework/docs/4.2.0.RELEASE/spring-framework-reference/html/overview.html#overview-maven-bom)
[Jackson BOM](https://github.com/FasterXML/jackson-bom#jackson-bom)
[Gradle bom import](https://docs.gradle.org/current/userguide/platforms.html#sub:bom_import)
Synchronizing Elide jars will only require
```xml
<dependencyManagement>
<dependencies>
<dependency>
<groupId>com.yahoo.elide</groupId>
<artifactId>elide-bom</artifactId>
<version>4.8.1</version>
<type>pom</type>
<scope>import</scope>
</dependency>
</dependencies>
</dependencyManagement>
```
Built locally …
> Create Elide Bill Of Materials (4.x)

- elide-async/pom.xml
- elide-bom/pom.xml
- elide-core/pom.xml
- elide-datastore/elide-datastore-jms/pom.xml
- elide-integration-tests/pom.xml
- elide-model-config/pom.xml
- elide-spring/pom.xml
- elide-standalone/pom.xml
- elide-swagger/pom.xml
- elide-test/pom.xml
- pom.xml
Create the Elide Bill Of Materials.
See [Apache bill of materials (BOM) files](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Importing_Dependencies)
Update build to use dependency Bill Of Materials.
[See Spring doc](https://docs.spring.io/spring-framework/docs/4.2.0.RELEASE/spring-framework-reference/html/overview.html#overview-maven-bom)
[Jackson BOM](https://github.com/FasterXML/jackson-bom#jackson-bom)
[Gradle bom import](https://docs.gradle.org/current/userguide/platforms.html#sub:bom_import)
Synchronizing Elide jars will only require
```xml
<dependencyManagement>
<dependencies>
<dependency>
<groupId>com.yahoo.elide</groupId>
<artifactId>elide-bom</artifactId>
<version>${elide.version}</version>
<type>pom</type>
<scope>import</scope> …
```
> Create Elide Bill Of Materials (6.x)

- elide-async/pom.xml
- elide-bom/pom.xml
- elide-core/pom.xml
- elide-datastore/elide-datastore-jms/pom.xml
- elide-integration-tests/pom.xml
- elide-model-config/pom.xml
- elide-spring/pom.xml
- elide-standalone/pom.xml
- elide-swagger/pom.xml
- elide-test/pom.xml
- pom.xml
Create the Elide Bill Of Materials.
See [Apache bill of materials (BOM) files](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Importing_Dependencies)
Update build to use dependency Bill Of Materials.
[See Spring doc](https://docs.spring.io/spring-framework/docs/4.2.0.RELEASE/spring-framework-reference/html/overview.html#overview-maven-bom)
[Jackson BOM](https://github.com/FasterXML/jackson-bom#jackson-bom)
[Gradle bom import](https://docs.gradle.org/current/userguide/platforms.html#sub:bom_import)
Synchronizing Elide jars will only require
```xml
<dependencyManagement>
<dependencies>
<dependency>
<groupId>com.yahoo.elide</groupId>
<artifactId>elide-bom</artifactId>
<version>${elide.version}</version>
<type>pom</type>
<scope>import</scope> …
```
> Create Elide Bill Of Materials (7.x)

- elide-datastore/elide-datastore-inmemorydb/pom.xml
- elide-datastore/pom.xml
- elide-swagger/pom.xml
Be sure JUnit is test scope and not compile.  The scope must be defined in dependencies.
We do not want runtime dependency on JUnit
Local build
> Cleanup junit test dependencies (7.x)

- pom.xml
Bumps `version.jersey` from 3.1.0 to 3.1.1.
Updates `jersey-container-servlet` from 3.1.0 to 3.1.1
Updates `jersey-hk2` from 3.1.0 to 3.1.1
Updates `jersey-server` from 3.1.0 to 3.1.1
@aklish Dependabot got confused after so many changes.  I would still like to update the version.
> Bump version.jersey from 3.1.0 to 3.1.1

- elide-datastore/elide-datastore-inmemorydb/pom.xml
- elide-datastore/pom.xml
- elide-swagger/pom.xml
Be sure JUnit is test scope and not compile.  The scope must be defined in dependencies.
We do not want runtime dependency on JUnit
Local build
> Cleanup junit test dependencies (6.x)

- elide-async/pom.xml
- elide-bom/pom.xml
- elide-core/pom.xml
- elide-datastore/elide-datastore-aggregation/pom.xml
- elide-datastore/elide-datastore-hibernate3/pom.xml
- elide-datastore/elide-datastore-hibernate5/pom.xml
- elide-datastore/elide-datastore-inmemorydb/pom.xml
- elide-datastore/elide-datastore-multiplex/pom.xml
- elide-datastore/elide-datastore-search/pom.xml
- elide-datastore/pom.xml
- elide-integration-tests/pom.xml
- elide-model-config/pom.xml
- elide-spring/elide-spring-boot-autoconfigure/pom.xml
- elide-spring/pom.xml
- elide-standalone/pom.xml
- pom.xml
Create the Elide Bill Of Materials.
See [Apache bill of materials (BOM) files](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Importing_Dependencies)
Update build to use dependency Bill Of Materials.
[See Spring doc](https://docs.spring.io/spring-framework/docs/4.2.0.RELEASE/spring-framework-reference/html/overview.html#overview-maven-bom)
[Jackson BOM](https://github.com/FasterXML/jackson-bom#jackson-bom)
[Gradle bom import](https://docs.gradle.org/current/userguide/platforms.html#sub:bom_import)
Synchronizing Elide jars will only require
```xml
<dependencyManagement>
<dependencies>
<dependency>
<groupId>com.yahoo.elide</groupId>
<artifactId>elide-bom</artifactId>
<version>${elide.version}</version>
<type>pom</type>
<scope>import</scope> …
```
> Create Elide Bill Of Materials (5.x)

- elide-contrib/elide-swagger/pom.xml
- elide-core/pom.xml
- elide-datastore/elide-datastore-hibernate3/pom.xml
- elide-datastore/elide-datastore-hibernate5/pom.xml
- elide-datastore/elide-datastore-jpa/pom.xml
- elide-datastore/pom.xml
- elide-integration-tests/pom.xml
- elide-standalone/pom.xml
- pom.xml
Be sure JUnit is test scope and not compile.
We do not want runtime dependency on JUnit
Local build
> Cleanup junit test dependencies (4.x)

- elide-graphql/src/main/java/com/yahoo/elide/graphql/QueryRunner.java
Partial fix for #2912
Elide no longer instantiates WebApplicationException which removes the dependency on jersey-common and associated runtime errors (since Elide doesn't include this dependency). 
> Remove dependency on jersey-commons from GraphQL query runner.

- elide-async/src/test/java/com/yahoo/elide/async/service/storageengine/RedisResultStorageEngineTest.java
- elide-standalone/pom.xml
- elide-standalone/src/test/java/example/ElideStandaloneMetadataStoreMissingTest.java
- elide-standalone/src/test/resources/logback.xml
Removes unwanted exception logging for elide-standalone and elide-async tests in the build output.
- Adds hibernate validator dependencies to pom to remove one set of exceptions
- Disables test logging for ElideStandaloneMetadataStoreMissingTest exceptions 
- Disables test logging for RedisResultStorageEngineTest exceptions
> Removing unwanted exception traces for build logs

- elide-core/pom.xml
- elide-core/src/main/java/com/yahoo/elide/core/audit/LogMessageImpl.java
Upgrades from `javax.el` to `jakarta.el`.
The `tomcat-embed-el` implementation was picked over the glassfish RI due to https://github.com/spring-projects/spring-boot/issues/24744. This is inline with the current dependencies for Spring Boot where the `spring-boot-starter-validation` includes `tomcat-embed-el`.
Allows the use of a single EL implementation.
The pre-existing `LogMessageImplTest` continues to pass.
> Update to `jakarta.el`

- elide-async/src/main/java/com/yahoo/elide/async/service/AsyncExecutorService.java
- elide-async/src/test/java/com/yahoo/elide/async/service/AsyncExecutorServiceTest.java
- elide-datastore/elide-datastore-jms/src/main/java/com/yahoo/elide/datastores/jms/websocket/SubscriptionWebSocketConfigurator.java
- elide-graphql/pom.xml
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLEndpoint.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/QueryRunner.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/subscriptions/websocket/SubscriptionWebSocket.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/FetcherFetchTest.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/FetcherUpdateTest.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/GraphQLEndpointTest.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/PersistentResourceFetcherTest.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/subscriptions/SubscriptionWebSocketTest.java
- elide-integration-tests/src/test/java/com/yahoo/elide/async/integration/tests/framework/AsyncIntegrationTestApplicationResourceConfig.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAsyncConfiguration.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideSubscriptionConfiguration.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideResourceConfig.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideStandaloneSettings.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideStandaloneSubscriptionSettings.java
- elide-test/pom.xml
- pom.xml
Resolves #2954
- Sets the configured `DataFetcherExceptionHandler` for mutation and subscription
- Adds configuration for standalone
Modified existing tests with a spy to check that the configured `DataFetcherExceptionHandler` is called for errors.
> Fix setting `DataFetcherExceptionHandler`

- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/framework/AggregationDataStoreTestHarness.java
- elide-datastore/elide-datastore-jpa/src/main/java/com/yahoo/elide/datastores/jpa/JpaDataStore.java
- elide-datastore/elide-datastore-jpa/src/main/java/com/yahoo/elide/datastores/jpa/SupplierEntityManager.java
- elide-datastore/elide-datastore-jpa/src/test/java/com/yahoo/elide/datastores/jpa/JpaDataStoreHarness.java
- elide-datastore/elide-datastore-jpa/src/test/java/com/yahoo/elide/datastores/jpa/JpaDataStoreTest.java
- elide-datastore/elide-datastore-jpa/src/test/java/com/yahoo/elide/datastores/jpa/SupplierEntityManagerTest.java
- elide-datastore/elide-datastore-search/src/test/java/com/yahoo/elide/datastores/search/DependencyBinder.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/orm/jpa/BasicEntityManagerProxy.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/orm/jpa/EntityManagerProxySupplier.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/orm/jpa/PlatformJpaTransaction.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/orm/jpa/PlatformJpaTransactionSupplier.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/com/yahoo/elide/spring/config/ElideAutoConfigurationTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/com/yahoo/elide/spring/orm/jpa/BasicEntityManagerProxyTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/com/yahoo/elide/spring/orm/jpa/PlatformJpaTransactionTest.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideStandaloneSettings.java
Resolves #1118
- Adds a `JpaTransaction` implementation that integrates with Spring's `PlatformTransactionManager`.
- Adds a `EntityManagerSupplier` that supplies `EntityManager` proxies that will delegate to the one in the active transaction.
- Adds the autoconfiguration to configure a `JpaTransactionSupplier` and `EntityManagerSupplier`.
- Modified the `JpaDataStore` to change the retrieval of the `Metamodel` to get from the `EntityManagerFactory` instead.
Processing will now be able to join the ongoing transaction managed by Spring.
Added the relevant unit and integration tests.
> Add Spring `PlatformTransactionManager` aware transaction support

- elide-async/pom.xml
- elide-core/pom.xml
- elide-datastore/elide-datastore-aggregation/pom.xml
- elide-datastore/elide-datastore-jms/pom.xml
- elide-datastore/elide-datastore-jpa/pom.xml
- elide-datastore/elide-datastore-search/pom.xml
- elide-datastore/pom.xml
- elide-graphql/pom.xml
- elide-integration-tests/pom.xml
- elide-model-config/pom.xml
- elide-spring/elide-spring-boot-autoconfigure/pom.xml
- elide-spring/elide-spring-boot-starter/pom.xml
- elide-spring/pom.xml
- elide-standalone/pom.xml
- elide-swagger/pom.xml
- elide-test/pom.xml
- pom.xml
Updates to Spring Boot 3.1.0 and refactor the pom for consistency by moving dependency management to the parent pom.
Some of the hibernate dependencies were pointing to the old maven coordinates and some of the overrides are no longer required.
Tested by running the build and tests.
> Update to Spring Boot 3.1.0 and refactor pom

- elide-core/src/main/java/com/yahoo/elide/core/filter/Operator.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/predicates/FilterPredicate.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/predicates/HasMemberPredicate.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/predicates/HasNoMemberPredicate.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/OperatorTest.java
- elide-core/src/test/java/com/yahoo/elide/core/filter/expression/InMemoryFilterExecutorTest.java
- elide-datastore/elide-datastore-jpql/src/main/java/com/yahoo/elide/datastores/jpql/filter/HasMemberJPQLGenerator.java
- elide-datastore/elide-datastore-jpql/src/test/java/com/yahoo/elide/datastores/jpql/filter/HasMemberJPQLGeneratorTest.java
This adds support for `hasMember` predicate to evaluate collections in a to-many association that a `null` value is present.
This is the alternative to the changes for the `isNull` predicate which can be closed if this is acceptable.
Previously the `hasMember` predicate does not support checking null field values.
Added unit tests.
> Add support for `hasMember` predicate to evaluate `null` in collections

- elide-swagger/src/main/java/com/yahoo/elide/swagger/OpenApiBuilder.java
- elide-swagger/src/test/java/com/yahoo/elide/swagger/OpenApiBuilderTest.java
- elide-swagger/src/test/java/example/models/Agent.java
- elide-swagger/src/test/java/example/models/Author.java
Resolves #3022
The code was not taking into account the node type when determine the shortest path so it was comparing apples and oranges. Rather than group by root type  group by leaf type and name and calculate the shortest path to that named type across all roots.
Also the determination of shortest path was string length not the number of hops. Changed that to be the number of hops so that the naming of the relationships doesn't affect the length.
The swagger generation only included nodes one level deep (the nodes with the shortest path) and omitted deeper nodes. For asimple graph a->b->c the swagger would only include a (the root node) and b (the non-root node with the shortest path). It would omit c.
The unit tests have been updated to cover this scenario.
I confirm that this …
> Calcluate duplicate paths correctly (#3022)

- elide-graphql/src/main/java/com/yahoo/elide/graphql/subscriptions/websocket/SubscriptionWebSocket.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/subscriptions/SubscriptionWebSocketTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideSubscriptionConfiguration.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideStandaloneSubscriptionSettings.java
When the `elide-graphql` library is deployed as part of a war a `jakarta.servlet.ServletException` is thrown as the `SubscriptionWebSocket` is annotated with `@ServerEndpoint`  and classes with that annotation needs to have a no-arg public constructor according to the spec.
This converts the `SubscriptionWebSocket` from the annotation based model using `@ServerEndpoint` to the programmatic API based model extending `Endpoint`. The existing mechanism of registering the web socket already is following the programmatic API based model.
When deployed as part of a war on Jetty the following is thrown.
```
jakarta.servlet.ServletException: jakarta.websocket.DeploymentException: Cannot access default constructor for the class: com.yahoo.elide.graphql.subscriptions.websocket.SubscriptionWebSocket …
```
> Fix SubscriptionWebSocket for war deployments

- elide-swagger/src/main/resources/META-INF/native-image/com.yahoo.elide/elide-swagger/reflect-config.json
This fixes some incorrect native reflection hints for swagger.
Fixes for spring boot native.
Tested by compiling `elide-spring-boot-example` using `mvn -Pnative native:compile` and noting that the warnings for reflection configuration no longer appear.
> Fix swagger native hints

- elide-swagger/pom.xml
Updates the `jersey-hk2` dependency on the `elide-swagger` module to the `test` scope to be inline with the other modules.
The `jersey-hk2` dependency isn't required when using Spring but is being pulled in when the `elide-swagger` module is include.
Tested by ensuring existing tests pass and that the dependency is no longer included for the spring boot example application.
> Update swagger jersey-hk2 dependency to test

- elide-core/src/main/java/com/yahoo/elide/core/request/route/ApiVersionValidator.java
- elide-core/src/main/java/com/yahoo/elide/core/request/route/BasicApiVersionValidator.java
- elide-core/src/main/java/com/yahoo/elide/core/request/route/DelegatingRouteResolver.java
- elide-core/src/main/java/com/yahoo/elide/core/request/route/FlexibleRouteResolver.java
- elide-core/src/main/java/com/yahoo/elide/core/request/route/HeaderRouteResolver.java
- elide-core/src/main/java/com/yahoo/elide/core/request/route/MediaTypeParameterRouteResolver.java
- elide-core/src/main/java/com/yahoo/elide/core/request/route/MediaTypeProfileRouteResolver.java
- elide-core/src/main/java/com/yahoo/elide/core/request/route/NullRouteResolver.java
- elide-core/src/main/java/com/yahoo/elide/core/request/route/ParameterRouteResolver.java
- elide-core/src/main/java/com/yahoo/elide/core/request/route/PathRouteResolver.java
- elide-core/src/main/java/com/yahoo/elide/core/request/route/Route.java
- elide-core/src/main/java/com/yahoo/elide/core/request/route/RouteResolver.java
- elide-core/src/main/java/com/yahoo/elide/core/request/route/UriPrefixSupplier.java
- elide-core/src/test/java/com/yahoo/elide/core/request/route/BasicApiVersionValidatorTest.java
- elide-core/src/test/java/com/yahoo/elide/core/request/route/DelegatingRouteResolverTest.java
- elide-core/src/test/java/com/yahoo/elide/core/request/route/FlexibleRouteResolverTest.java
- elide-core/src/test/java/com/yahoo/elide/core/request/route/HeaderRouteResolverTest.java
- elide-core/src/test/java/com/yahoo/elide/core/request/route/MediaTypeParameterRouteResolverTest.java
- elide-core/src/test/java/com/yahoo/elide/core/request/route/MediaTypeProfileRouteResolverTest.java
- elide-core/src/test/java/com/yahoo/elide/core/request/route/NullRouteResolverTest.java
- elide-core/src/test/java/com/yahoo/elide/core/request/route/ParameterRouteResolverTest.java
- elide-core/src/test/java/com/yahoo/elide/core/request/route/PathRouteResolverTest.java
- elide-core/src/test/java/com/yahoo/elide/core/request/route/RouteTest.java
Adds the route resolvers for API Versioning
Support other methods for API Versioning
Added unit tests.
> Add route resolvers for API Versioning

- pom.xml
Resolves #3032
Resolves case where dependency check will flag out the dependency.
> Bump hjson.version from 3.0.0 to 3.0.1

- elide-datastore/elide-datastore-jpql/src/main/java/com/yahoo/elide/datastores/jpql/filter/CaseAwareJPQLGenerator.java
- elide-datastore/elide-datastore-jpql/src/main/java/com/yahoo/elide/datastores/jpql/filter/FilterTranslator.java
- elide-datastore/elide-datastore-search/pom.xml
- pom.xml
Uses the `CONCAT` function to make the field a string for the `LIKE` operators.
Hibernate now checks that the operand to the `LIKE` operator must be a string.
- https://github.com/hibernate/hibernate-orm/commit/935ac494dd19fc84672f64f5bd40b2b9ed7c76c3
- https://github.com/hibernate/hibernate-orm/blob/75f173a4a056c3091772079a0f95aa57ab71dad6/hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/SqmLikePredicate.java#L61-L62
Existing tests continue to pass.
> Bump hibernate.version from 6.2.7.Final to 6.3.1.Final

- elide-core/src/main/java/com/yahoo/elide/ElideError.java
- elide-core/src/main/java/com/yahoo/elide/ElideErrors.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/models/JsonApiError.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/models/JsonApiErrors.java
- elide-core/src/test/java/com/yahoo/elide/ElideErrorTest.java
- elide-core/src/test/java/com/yahoo/elide/jsonapi/models/JsonApiErrorTest.java
- elide-core/src/test/java/com/yahoo/elide/jsonapi/models/JsonApiErrorsTest.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/models/GraphQLError.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/models/GraphQLErrors.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/models/SourceLocationBuilder.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/models/GraphQLErrorTest.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/models/GraphQLErrorsTest.java
This separates the error message concerns for JSON API and GraphQL as their error message formats are different.
This particular PR only adds the error classes, a generic `ElideError` class that is intended to be mapped to the specialized `JsonApiError` or `GraphQLError` using a mapper class. This PR doesn't yet add or refactor the error mappers or exception handling mechanism.
The subsequent PRs after this are
- Add error mappers and refactor serializers
- Refactor response and exception handling
The existing `ErrorObjects` class somewhat follows the JSON API error format, but allows arbitrary attributes leading it to be used in different ways for JSON API and GraphQL which tends to make it generate error messages that do not conform to either specification.
For JSON API attributes that …
> Add generic, json api and graphql errors

- elide-graphql/pom.xml
- pom.xml
[Jakarta WebSocket 2.1](https://jakarta.ee/specifications/websocket/2.1/) has removed the copy of the jakarta.websocket.* classes from the jakarta.websocket-api jar and replaced the copy with a dependency on the jakarta.websocket-client-api jar.
This adds the jakarta.websocket-client-api dependency where needed.
Existing tests continue to pass.
> Bump jakarta.websocket-api from 2.0.0 to 2.1.1

- elide-datastore/elide-datastore-jms/src/main/java/com/yahoo/elide/datastores/jms/websocket/SubscriptionWebSocketConfigurator.java
- elide-datastore/elide-datastore-jms/src/main/java/com/yahoo/elide/datastores/jms/websocket/SubscriptionWebSocketConfiguratorBuilderCustomizer.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLEndpoint.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/subscriptions/SubscriptionModelBuilder.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/subscriptions/websocket/ConnectionInfo.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/subscriptions/websocket/RequestHandler.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/subscriptions/websocket/SubscriptionWebSocket.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideSubscriptionConfiguration.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/com/yahoo/elide/spring/config/ElideSubscriptionConfigurationTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/models/jpa/v2/ArtifactGroupV2.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/ControllerTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/SubscriptionTest.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/ElideStandalone.java
- elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideStandaloneSubscriptionSettings.java
- elide-standalone/src/test/java/example/ElideStandaloneSubscriptionTest.java
- elide-standalone/src/test/java/example/models/v2/PostV2.java
Adds support for GraphQL subscriptions to handle API versioning.
GraphQL subscriptions couldn't easily handle API versioning.
Added the appropriated tests and manually with modified example applications.
> Support api versioning for subscriptions

- elide-async/pom.xml
- elide-async/src/main/java/com/yahoo/elide/async/operation/JsonApiAsyncQueryOperation.java
- elide-async/src/main/java/com/yahoo/elide/async/operation/JsonApiTableExportOperation.java
- elide-async/src/test/java/com/yahoo/elide/async/service/AsyncExecutorServiceTest.java
- pom.xml
Upgrade from httpclient4 to httpclient5.
Reduce the total number of dependencies as there is a pre-existing transitive dependency on httpclient5 from elide-datastore-aggregation due to calcite.
Pre-existing tests continue to pass.
> Upgrade to httpclient5

- elide-core/src/test/java/com/yahoo/elide/core/dictionary/EntityDictionaryTest.java
There are some tests in this class which compare elements in 2 lists and unintentionally check for the order of the lists as well. Converting a collection to a list may return different orders of the list. Instead a better technique to check if all the elements in a list are present in a collection is to use the `containsAll` function
There are flaky tests detected in `EntityDictionaryTest.java` - 
- `testHiddenFields`
- `testGetIdAnnotationsSubClass`
- `testGetIdAnnotations`
These tests may sometimes fail even though the code under test may be working as expected.
**Reproduction of error**
Run maven tests with [NonDex](https://github.com/TestingResearchIllinois/NonDex) tool
```
mvn -pl elide-core edu.illinois:nondex-maven-plugin:2.1.7-SNAPSHOT:nondex …
```
> Fix flaky tests in EntityDictionaryTest.java

- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLConversionUtils.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLScalars.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLSettings.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/ModelBuilder.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/federation/EntitiesDataFetcher.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/federation/EntityTypeResolver.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/federation/FederationDefinitions.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/federation/FederationSchema.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/federation/FederationVersion.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/parser/GraphQLEntityProjectionMaker.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/FetcherFetchTest.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/ModelBuilderTest.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/federation/EntityTypeResolverTest.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/federation/FederationSchemaTest.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/GraphQLControllerProperties.java
- pom.xml
Resolves #2638
This adds support for the `@key` directive for Apollo Federation.
This is required for to resolve from a different subgraph onto the Elide subgraph.
Added the appropriate unit and integration tests.
This was also tested using the following example
- https://github.com/justin-tay/federation-jvm-elide-example
- https://github.com/justin-tay/elide-spring-boot-example/tree/apiversion_elide-7.x
> Add @key support for GraphQL Federation

- elide-core/pom.xml
- elide-core/src/test/java/com/yahoo/elide/jsonapi/JsonApiTest.java
There are some tests in `JsonApiTest` class which compare json strings and unintentionally check for the order of json elements as well. Converting a JSON to a string may return different orderings for the key-value pairs. Instead a better technique is to use Skyscreamer's [JSONAssert](https://github.com/skyscreamer/JSONassert)
There are flaky tests detected in JsonApiTest.java with the help of [NonDex](https://github.com/TestingResearchIllinois/NonDex) tool -
- `writeListIncluded`
- `writeSingleIncluded`
These tests may sometimes fail even though the code under test may be working as expected.
Setup the [NonDex](https://github.com/TestingResearchIllinois/NonDex) tool and run
```
mvn -pl elide-core edu.illinois:nondex-maven-plugin:2.1.7-SNAPSHOT:nondex …
```
> Use JSONAssert to compare JSON strings

- elide-core/src/main/java/com/yahoo/elide/core/dictionary/EntityDictionary.java
- elide-core/src/test/java/com/yahoo/elide/core/datastore/inmemory/InMemoryStoreTransactionTest.java
- elide-core/src/test/java/com/yahoo/elide/core/dictionary/EntityDictionaryTest.java
- elide-core/src/test/java/com/yahoo/elide/core/utils/ClassScannerTest.java
- elide-core/src/test/java/example/Right.java
- elide-core/src/test/java/example/Righter.java
Resolves #3172 (if appropriate)
Calculate the inverse relationship for inherited entities.
The delete lifecycle hooks do not trigger if you delete the many side of a oneToMany where the many side is a polymorphic type.
Added unit tests.
> Inverse relationship type calculation (#3172)

- elide-quarkus/deployment/src/main/java/com/yahoo/elide/extension/deployment/ElideExtensionProcessor.java
- elide-quarkus/deployment/src/test/java/com/yahoo/elide/extension/test/ElideExtensionTest.java
- elide-quarkus/deployment/src/test/resources/application.properties
- elide-quarkus/integration-tests/src/main/resources/application.properties
- elide-quarkus/pom.xml
- elide-quarkus/runtime/src/main/java/com/yahoo/elide/extension/runtime/ElideBeans.java
- Bumped the Quarkus version from 3.7.0 to 3.7.4 (latest)
- Made the extension report its name as just "elide", rather than "elide-extension", in line with other extension names. 
- Tweaked existing tests so they're testing that the elide.base-xxx settings are working. 
- Removed commented-out imports and a println statement.
Will be good to include the latest Quarkus version, and a consistent extension name, with the first Elide release containing the Quarkus extension.
Existing unit tests pass, and usage within my sample projects is unaffected by this change.
> Bump Quarkus Version, Small cleanup

- elide-datastore/elide-datastore-jpql/src/main/java/com/yahoo/elide/datastores/jpql/query/RootCollectionPageTotalsQueryBuilder.java
- elide-datastore/elide-datastore-jpql/src/test/java/com/yahoo/elide/datastores/hibernate/hql/RootCollectionPageTotalsQueryBuilderTest.java
Speed up regular count queries without joins
For large datasets, removing DISTINCT can significantly enhance performance.
Removing DISTINCT from count queries that do not involve joins.
Tests have been updated according to the changes made in the logic.
> Apply DISTINCT for RootCollectionPageTotalsQueryBuilder only on JOINS

- elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/EntityHydrator.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/AnnotationGraphQLFieldDefinitionDescriptionCustomizer.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/DefaultGraphQLFieldDefinitionCustomizer.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLConversionUtils.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLFieldDefinitionCustomizer.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLSettings.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/ModelBuilder.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/annotation/GraphQLDescription.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/subscriptions/SubscriptionModelBuilder.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/subscriptions/websocket/SubscriptionWebSocket.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/GraphQLDescription.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/ModelBuilderTest.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/subscriptions/SubscriptionDataFetcherTest.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/subscriptions/SubscriptionModelBuilderTest.java
- elide-graphql/src/test/java/example/Book.java
Resolves #3214
* Adds a `GraphQLFieldDefinitionCustomizer` to allow customization of the `GraphQLFieldDefinition`
* Adds a setting on the `GraphQLSettings` for the customization
As there is no standard annotation for this there is no default implementation.
```java
@Configuration
public class ElideConfiguration {
@Bean
GraphQLSettingsBuilderCustomizer graphqlSettingsBuilderCustomizer() {
return graphqlSettings -> graphqlSettings.graphqlFieldDefinitionCustomizer(
((fieldDefinition, parentClass, attributeClass, attribute, fetcher, entityDictionary) -> {
Description description = entityDictionary.getAttributeOrRelationAnnotation(parentClass,
Description.class, attribute);
if (description != null) {
fieldDefinition.description(description.value());
}
}));
}
}
```
Allows the customization of …
> Allow customization of GraphQLFieldDefinition

- elide-spring/elide-spring-boot-autoconfigure/pom.xml
Removes the `spring-boot-properties-migrator` from `elide-spring-boot-autoconfigure`.
The `spring-boot-properties-migrator` is used to detect deprecated Spring Boot properties and is largely a dev tool to be added when necessary. Having this dependency in `elide-spring-boot-autoconfigure` means unnecessary libraries are included for production.
Existing tests were run after the modifications.
> Remove spring-boot-properties-migrator

- elide-swagger/src/main/java/com/yahoo/elide/swagger/models/media/Resource.java
- elide-swagger/src/test/java/com/yahoo/elide/swagger/OpenApiIT.java
Resolves #3229
The additional attributes and relationships in Resource.java were being serialized into the generated swagger.
A lot of the tooling will just ignore these additional invalid fields. However tools like swagger codegen fail with errors like:
Updated the existing test assertions to check the structure of the generated schema.
> Remove attributes and relationships from swagger components (#3229)

- elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/NoCacheAggregationDataStoreIntegrationTest.java
- elide-quarkus/pom.xml
- elide-standalone/pom.xml
- pom.xml
Upgrades dependencies for compatibility with Spring Boot 3.3.0.
Spring Boot 3.3.0 targets Jetty 12.0.9. 
Spring Boot 3.3.0 `org.springframework.boot.web.embedded.jetty.JettyEmbeddedWebAppContext` is using Jetty 12.0.9 `org.eclipse.jetty.util.ClassMatcher`.
Older versions of Jetty with Spring Boot 3.3.0 results in `Caused by: java.lang.NoClassDefFoundError: org/eclipse/jetty/util/ClassMatcher`.
Existing tests continue to pass. Also tested by modifying `elide-spring-boot-example`.
> Upgrade dependencies

- elide-async/src/main/java/com/yahoo/elide/async/operation/TableExportOperation.java
- elide-async/src/test/java/com/yahoo/elide/async/service/storageengine/RedisResultStorageEngineTest.java
- elide-core/pom.xml
- elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java
- elide-core/src/main/java/com/yahoo/elide/core/filter/visitors/VerifyFieldAccessFilterExpressionVisitor.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/document/processors/IncludedProcessor.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/models/Data.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/parser/state/CollectionTerminalState.java
- elide-core/src/main/java/com/yahoo/elide/jsonapi/parser/state/RecordState.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistenceResourceTestSetup.java
- elide-core/src/test/java/com/yahoo/elide/core/PersistentResourceTest.java
- elide-core/src/test/java/com/yahoo/elide/jsonapi/models/DataTest.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/PersistentResourceFetcher.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/federation/EntitiesDataFetcher.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/subscriptions/SubscriptionDataFetcher.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/subscriptions/containers/SubscriptionNodeContainer.java
- pom.xml
Migrate from RxJava2 to Reactor.
As RxJava2 has been EOL it would be good to migrate to something else.
The following options were considered
* RxJava3
* Reactor
* Mutiny
Micronaut had also migrated from RxJava2 to Reactor instead of migrating to RxJava3. This would also align with Spring and reduce having an additional library if the Spring Reactive stack is used. The R2DBC drivers are implemented using Reactor.
Added tests and existing tests passed. Also tested with the elide-spring-boot-example.
> Migrate RxJava2 to reactor

- elide-core/src/main/java/com/yahoo/elide/core/datastore/inmemory/InMemoryStoreTransaction.java
- elide-core/src/test/java/com/yahoo/elide/core/datastore/inmemory/InMemoryStoreTransactionTest.java
Resolves #3257 
Fixes a bug where page totals were not being set for empty collections
This was usually correct, but if the page totals had been previously set - the pagination object seemed to be reused when querying graphql relationships with pageInfo - they would not be correctly reset for the next entity
Added unit test to verify
> Fix pagination set page totals to zero after non-zero query

- elide-async/pom.xml
- elide-core/src/main/java/com/yahoo/elide/core/security/User.java
- elide-datastore/elide-datastore-aggregation/pom.xml
- elide-datastore/elide-datastore-jms/pom.xml
- elide-graphql/pom.xml
- elide-quarkus/pom.xml
- elide-quarkus/runtime/pom.xml
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideSubscriptionConfiguration.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideSubscriptionScanningConfiguration.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/controllers/GraphqlController.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/controllers/JsonApiController.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/datastore/config/DataStoreBuilder.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/security/AuthenticationUser.java
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/security/HttpServletRequestUser.java
- elide-standalone/pom.xml
The following are the summary of the main changes. These changes don't affect users using `elide-spring-boot-starter` as that generally pulls all the modules.
**elide-async**
* Sets `elide-graphql` optional to allow users that just wish to use JSON-API. Users that use GraphQL would have included the `elide-graphql` dependency explicitly anyway.
**elide-datastore-aggregation**
* Sets `elide-graphql` and `elide-datastore-multiplex` to test scope as they are only used during testing.
**elide-graphql**
* Sets `jakarta.websocket-api`, `jakarta.websocket-client-api` and `jakarta.jms-api` to optional for users that wish to use GraphQL but not the subscription support.
**elide-spring-boot-autoconfigure**
* Adds a `HttpServletRequestUser` to be used in place of `AuthenticationUser` to remove a …
> Optimize required dependencies for modules

- elide-async/pom.xml
- elide-graphql/src/main/java/com/yahoo/elide/graphql/QueryRunner.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/parser/GraphQLEntityProjectionMaker.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/QueryRunnerTest.java
Instead of attempting to guess if the query text is a `mutation` by checking the starting characters of the line parse the `Document` as the `GraphQLEntityProjectionMaker` is going to need it anyway to make the `GraphQLProjectionInfo`. It is then simple to check if the `mutation` operation is present in the `Document`.
This for instance allows handling of cases where a `fragment` exists before the `mutation`.
```graphql
fragment postData on Post {
id
title
text
author {
username
displayName
}
}
mutation addPost($post: AddPostInput!) {
addPost(input: [$post]) {
post {
...postData
}
}
}
```
Modified the appropriate unit tests.
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright …
> Improve mutation determination

- elide-spring/elide-spring-boot-autoconfigure/README.md
- elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAsyncConfiguration.java
- elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/App.java
Resolves #3283 
This replaces the use of `@EntityScan` with `@AutoConfigurationPackage`
Using `@EntityScan` in a library breaks users that are relying on auto configuration.
Note that this fix will be a breaking change for existing users who specified `@EntityScan` as they now need to explicitly specify `AsyncQuery.class`. The `elide-spring-boot-example` has `@EntityScan` on the `App` which will cause `@AutoConfigurationPackage` to back off. This means they need to ensure that they also explicitly add `AsyncQuery.class` if they are using `@EntityScan` ie `@EntityScan(basePackageClasses = { App.class, AsyncQuery.class })`. I will separately make a PR to remove the `@EntityScan` annotation on `App` in `elide-spring-boot-example` when this gets merged.
The following is some context on why …
> Replace `@EntityScan` with `@AutoConfigurationPackage` for async

- elide-swagger/src/main/java/com/yahoo/elide/swagger/converter/JsonApiModelResolver.java
- elide-swagger/src/test/java/com/yahoo/elide/swagger/OpenApiBuilderTest.java
- elide-swagger/src/test/java/example/models/Book.java
Resolves #3301
Currently, OpenAPI swagger documentation supports the definition of extension properties in the @Schema annotation, it is built like a Map<String, Object> and generally allows the OpenAPI user to define customs properties on the documentation.
The reason I'm opening this feature is that I need to send more information to the FrontEnd point of my applications through OpenAPI to handle various situations, such as localized properties and others. By adding the extension property we are able to send all the necessary information and many more, leading to a more customizable experience for OpenAPI definition.
Aside from testing these changes by building some unit tests, I also applied the changes to my project and checked the openAPI documentation.
I confirm that this …
> Add support for extension property of OpenAPI 3_0 (#3301)

- pom.xml
Resolves #3305 
Upgrades Spring Boot from 3.3.3 to 3.4.0. Also upgrades HttpClient5 which was causing the test failure.
Existing tests continue to pass.
> Upgrade Spring Boot from 3.3.3 to 3.4.0

- elide-integration-tests/src/test/java/example/Parent.java
- elide-quarkus/deployment/pom.xml
- elide-quarkus/deployment/src/test/resources/application.properties
- elide-quarkus/pom.xml
- elide-quarkus/runtime/pom.xml
- pom.xml
Resolves #3310
Upgrades 6.5.2.Final to 6.6.3.Final.
This also upgrades Quarkus to the latest to support 6.6.x.
Spring Boot's managed dependencies are also now at 6.6.x.
Existing integration tests pass.
> Upgrade hibernate from 6.5.2.Final to 6.6.3.Final

- elide-quarkus/runtime/pom.xml
Replaced quarkus-**bootstrap**-maven-plugin with quarkus-**extension**-maven-plugin, which appears to be a drop in replacement, as per the following build-time deprecation warning:
`[WARNING]  Goal 'extension-descriptor' is deprecated: in favor of {@code io.quarkus:quarkus-extension-maven-plugin}.
<p>
Generates Quarkus extension descriptor for the runtime artifact.
<p>
<p/>
Also generates META-INF/quarkus-extension.json which includes properties of
the extension such as name, labels, maven coordinates, etc that are used by
the tools.
[WARNING] This Maven plugin was deprecated in favor of io.quarkus:quarkus-extension-maven-plugin:3.0.0.Beta1, please, update the artifactId of the plugin in your project configuration.`
Removes a warning during build time.
- I've been using the version built …
> Use quarkus-extension-maven-plugin

- elide-quarkus/deployment/src/test/java/com/yahoo/elide/extension/test/ElideExtensionTest.java
- elide-quarkus/deployment/src/test/java/com/yahoo/elide/extension/test/models/Book.java
- elide-quarkus/runtime/src/main/java/com/yahoo/elide/extension/runtime/ElideBeans.java
Rather than just calling `dictionary.scanForSecurityChecks()` we now call `elide.doScans()` instead. This causes the built-in type converters to be registered, whereas they weren't before. Security checks are still also registered, as before.
This solves the issue whereby the built in type converters were not being registered by the quarkus extension. For example, attempting to use OffsetDateTime as a field type resulted in a failure at runtime due to the type being unknown.
A simple new, passing test is added that filters on a OffsetDateTime field. I have confirmed the test failed before the change was implemented.
> Quarkus: do all scans (not limited to security checks)

- elide-core/src/main/java/com/yahoo/elide/core/utils/coerce/CoerceUtil.java
- elide-core/src/test/java/com/yahoo/elide/core/utils/coerce/CoerceUtilTest.java
Resolves #3363
When coercing to String the serialize method on the Serde is called.
Required when coercing to String.
Added tests in `CoerceUtilTest` and manually to verify no errors when using sorts for cursor based pagination.
> Fix coercing to String for Serdes

- elide-graphql/src/main/java/com/yahoo/elide/graphql/Entity.java
- elide-graphql/src/main/java/com/yahoo/elide/graphql/PersistentResourceFetcher.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/FetcherDeleteTest.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/FetcherRemoveTest.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/FetcherReplaceTest.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/FetcherUpdateTest.java
- elide-graphql/src/test/java/com/yahoo/elide/graphql/PersistentResourceFetcherTest.java
- elide-graphql/src/test/resources/graphql/responses/fetch/computedAttributes.json
- elide-graphql/src/test/resources/graphql/responses/fetch/fragmentOnConnection.json
- elide-graphql/src/test/resources/graphql/responses/fetch/fragmentOnEdges.json
- elide-graphql/src/test/resources/graphql/responses/fetch/fragmentOnNode.json
- elide-graphql/src/test/resources/graphql/responses/fetch/pageTotalsRelationship.json
- elide-graphql/src/test/resources/graphql/responses/replace/replaceNestedCollection.json
Resolves #3373 
* Allows the use of the `REMOVE` op on a to-one relationship without `ids` specified to remove the relationship.
* Allows the use of the `DELETE` op on a to-one relationship without `ids` specified to remove the relationship and delete the object.
* Returns `Optional.empty()` for `Entity.getId()` when attributes is `null` to prevent a NPE and allow the error message `UPDATE data objects must include ids` to be correctly generated.
It's currently not possible to remove a to-one relationship.
* `FetcherRemoveTest` was updated to test `REMOVE` on a to-one relationship
* `FetcherDeleteTest` was updated to test `DELETE` on a to-one relationship
* `FetcherUpdateTest` was updated to test the error message when `UPDATE` is used with a `null` object
* `FetcherReplaceTest` was …
> Fix graphql fetcher to allow REMOVE and DELETE for toOne relationship

- elide-core/pom.xml
- elide-core/src/main/java/com/yahoo/elide/core/dictionary/EntityBinding.java
- elide-core/src/test/java/com/yahoo/elide/core/dictionary/EntityBindingTest.java
Resolves #3340 
Adds support for using an annotation with the `@IdGeneratorType` meta-annotation.
Required to support custom id generation with Hibernate.
* `EntityBindingTest` was updated to ensure that `isIdGenerated` is true
* Manually tested that the id was generated using example project
> Support @IdGeneratorType
